MetaphorData/connectors

.github/workflows/cicd.yml
README.md
metaphor/google_directory/README.md
metaphor/snowflake/README.md

So users know how to use it.
- Add initial README file for snowflake
- Update various other README files
- Upgrade poetry to fix flakey CI: https://github.com/python-poetry/poetry/issues/3199

Add initial README file for Snowflake connector

---

metaphor/common/entity_id.py
metaphor/snowflake/extractor.py
poetry.lock
pyproject.toml
tests/common/test_entity_id.py
tests/snowflake/test_extractor.py

- Fill in the sourceInfo with snowflake url
- Update EntityId `str` to remove None values

Add Snowflake links to Snowflake datasets [ch1964]

---

metaphor/snowflake/usage/extractor.py
pyproject.toml

- Add account into snowflake dataset id

Fix snowflake ID in usage extractor by adding [ch3427]

---

metaphor/dbt/extractor.py
pyproject.toml
tests/dbt/data/expected_results.json
tests/dbt/test_extractor.py

- Add account into dataset id in DBT extractor

Fix snowflake ID in dbt extractor by adding [ch3428]

---

metaphor/snowflake/extractor.py
pyproject.toml

- Fill in DatasetStatistics by fetching row_count, table_size and last_modified time

Fetch snowflake table data last modified [sc-3548]

---

metaphor/postgresql/extractor.py
metaphor/snowflake/extractor.py
pyproject.toml

- Fetch table statistics for postgres and redshift
- Fix: MB = 10^6
- Tested against local postgres

Get table statistics in postgres and snowflake [sc-604]

---

metaphor/snowflake/usage/extractor.py
poetry.lock
pyproject.toml
tests/snowflake/usage/data/parse_query_log_result.json
tests/snowflake/usage/test_parser.py
tests/snowflake/usage/test_statistics.py

Design doc https://docs.google.com/document/d/11WnSxyVvd3I6Zsu4HxrYvA3EwqRHtQ_5OKT39d_BnHQ/edit?usp=sharing
- Add parser to retrieve and fill in table join stats

Parse Snowflake query log to get join table [sc-2883]

---

metaphor/snowflake/extractor.py
pyproject.toml

MCE validation error for datetime, it needs specific timezone info to pass validation.
- Add timezone info to datetime

Datetime errors in snowflake crawler [sc-3637]

---

metaphor/common/entity_id.py
metaphor/common/event_util.py
metaphor/looker/extractor.py
metaphor/looker/lookml_parser.py
poetry.lock
pyproject.toml
tests/looker/join/model1.model.lkml
tests/looker/test_extractor.py
tests/looker/test_lookml_parser.py

We have the new VirtualView models, time to fill in the data
- Update Looker connector to fetch explores and views
- Update dashboard upstream to also point to explores

update looker crawler to output looker explores

---

README.md
metaphor/bigquery/README.md
metaphor/google_directory/README.md
metaphor/snowflake/README.md

Because it's missing :)
As titled. Also fixed typos & format of Snowflake's README.

Add README for bigquery connector

---

metaphor/snowflake/README.md

The original instructions were incomplete and incorrect.
As titled. Tested by manually creating the user and run the connector using the new credential.

Update Snowflake user creation instructions

---

metaphor/dbt/extractor.py
poetry.lock
pyproject.toml
tests/dbt/data/shopify/manifest.json
tests/dbt/data/shopify/results.json

To support more details in dbt macro arguments
- Fill in macro arguments with name, type and description

Support Macro argument type description [sc-3904]

---

metaphor/common/extractor.py

To make it clear to the user.
As titled. Tested:
```
$ python -m metaphor.bigquery ~/Desktop/local/bigquery.yml 
...
2021-10-09 05:08:44,359 INFO - Fetched 9 entities
2021-10-09 05:08:44,378 INFO - Extractor ended successfully
```

Print message when extractor finishes successfully

---

README.md
metaphor/snowflake/usage/README.md
metaphor/snowflake/usage/extractor.py
pyproject.toml

Provide instructions on how to setup the connector.
As titled.
Tested locally:
```
$ python -m metaphor.snowflake.usage snowflake_usage.yml
...
2021-10-09 09:28:47,242 INFO - Fetched 470 entities
2021-10-09 09:28:47,391 INFO - Extractor ended successfully 
```

Add README for snowflake usage connector and drop hard-coded role

---

.github/workflows/codeql-analysis.yml

GitHub recommends it: https://github.com/MetaphorData/connectors/settings/security_analysis
As titled
https://github.com/MetaphorData/connectors/actions/runs/1367956203

Enable code analysis workflow recommended by GitHub

---

metaphor/common/extractor.py
metaphor/common/file_sink.py
metaphor/common/logging.py
metaphor/common/s3.py
metaphor/dbt/extractor.py
metaphor/google_directory/extractor.py
metaphor/looker/extractor.py
metaphor/postgresql/extractor.py
metaphor/slack_directory/extractor.py
metaphor/snowflake/extractor.py
metaphor/snowflake/profile/extractor.py
metaphor/snowflake/usage/extractor.py
pyproject.toml

To help debug any potential issues during the run.
All logs are written to a temp location before moving to the final destination or upload to s3 bucket as a zip.
Also need to fix the AWS role assuming code to make smart_open to actually make use the assumed credential.
Manually tested end-to-end to make sure that it writes but locally and to S3.

Add a config to write all logs as a zip file

---

metaphor/looker/config.py
metaphor/looker/extractor.py
tests/looker/config.yml
tests/looker/test_config.py

As part of https://github.com/MetaphorData/connectors/issues/76
As titled. Not bumping PyPI version on purpose.

Rename config key for consistency

---

metaphor/dbt/config.py
metaphor/dbt/extractor.py
tests/dbt/config.yml
tests/dbt/test_config.py
tests/dbt/test_extractor.py

As part of https://github.com/MetaphorData/connectors/issues/76
As titled. Also factored out the config class to its own file.
Tested locally:
```
$ python -m metaphor.dbt ~/Desktop/local/dbt.yml 
2021-10-29 11:47:05,528 INFO - Starting extractor DbtExtractor
2021-10-29 11:47:05,529 INFO - Fetching metadata from DBT repo
2021-10-29 11:47:05,648 INFO - Fetched 24 entities
2021-10-29 11:47:05,673 INFO - Extractor ended successfully
```

Rename camel case config keys to snake cases for consistency

---

metaphor/looker/extractor.py
poetry.lock
pyproject.toml

To extract the appropriate title & description from charts in Looker dashboards.
- Use `title` if specified, otherwise fallback to `id`
- Use `note_text` as description
Ran locally and manually verified the output

Set chart title & description

---

metaphor/postgresql/extractor.py
pyproject.toml

Surface more column info for user
- Fill in column data size and precision
- Rewrite the fetch_column and fetch_constraints to issue much less queries and improve speed.
Local crawler run, diff with previous result.
The MCE different is only in the max_length and precision fields and timestamps.

Capture field length for Redshift Postgres [sc-3506]

---

.github/workflows/cicd.yml

To help identify the commit that's associated with a particular PyPI version. This will also pave the way for automatic release note generation in the future.
As titled.
Since we don't have an existing `workflow_dispatch`, this can only be tested after merging.

Automatically tag commit after publishing a new version to PyPI

---

metaphor/postgresql/extractor.py
metaphor/redshift/extractor.py
pyproject.toml

The table size and row count doesn't work for redshift if using the postgres crawler, the results are always 0
Using the SSV TABLE INFO to get those information https://docs.aws.amazon.com/redshift/latest/dg/r_SVV_TABLE_INFO.html
Tested locally with tunnel to data env, both postgres and redshift crawler run successfully, result json passed eye examination.

Use SVV TABLE INFO to get table size for [sc-3610]

---

docs/develop.md
poetry.lock
pyproject.toml

As more developers move from Intel to Apple Silicon, we need to have proper instructions on how to develop and test the crawlers on M1 natively.
As titled.
Manually verified that all connectors run successfully without Rosetta.

Update depencdencies and instruction for M1

---

.github/workflows/cicd.yml
pyproject.toml

[Previous attempt](https://github.com/MetaphorData/connectors/pull/101) didn't work properly.
Do everything in JS instead of trying to wrangle with `grep`. Need to bump up PyPI version twice for testing.
Without tagging: https://github.com/MetaphorData/connectors/actions/runs/1450184593
With tagging: https://github.com/MetaphorData/connectors/actions/runs/1450196182

Fix PyPI version tagging

---

metaphor/common/extractor.py
pyproject.toml

It's currently printing the full precision, which makes it difficult to read, .e.g.
```
Fetched 0 entities, took 1235.893330335617 s
```
As titled.
```
Fetched 0 entities, took 1235.9 s
```

Format extractor run duration

---

README.md
metaphor/postgresql/README.md
metaphor/redshift/README.md
pyproject.toml

The instructions on how to use PostgreSQL & Redshift connectors are currently missing.
As titled. Also add a new `redshift` extra in case if its dependencies diverge from that of `postgresql` in the future.
N/A

Add README files for PostgreSQL & Redshift connectors

---

README.md

To showcase automated static code analyses.
As titled.
https://lgtm.com/projects/g/MetaphorData/connectors/context:python

Add LGTM & CodeQL badge

---

metaphor/looker/README.md
metaphor/tableau/README.md
metaphor/tableau/__main__.py
metaphor/tableau/config.py
metaphor/tableau/extractor.py
poetry.lock
pyproject.toml
tests/tableau/config.json
tests/tableau/config.yml
tests/tableau/test_config.py

To add Tableau to our support dashboard platforms
- Add crawler for tableau dashboard using REST API
- Fetches dashboards and charts. No data source connection yet
- Support both user-password and access token (recommended) auth
local run successfully against https://10ax.online.tableau.com/#/site/metaphordev451768 , using either password or token. 
Collected two dashboards and 15 charts.

Crawler for Tableau [sc-1336]

---

metaphor/dbt/extractor.py
pyproject.toml
tests/dbt/data/shopify/results.json

To fix the crawler output. Currently, the crawler could output duplicate entity ID in `sourceModels`, `sourceDatasets` or `owner` depending on the dbt `manifest.json`, which will break the uniqueness validation in Metaphor.
- Uniquify entity ID preserving order.
Uniquify `tests/dbt/data/shopify/results.json` manually and run tests successfully.

Ensure dbt crawler outputs unique entity IDs [sc-5857]

---

metaphor/tableau/extractor.py
poetry.lock
pyproject.toml

Missed the `platform` in tableau logical ID
- add `platform=DashboardPlatform.TABLEAU`
local run successfully, verified the MCE json

Tableau MCE missing platform [sc-5984]

---

README.md
metaphor/tableau/extractor.py
poetry.lock
pyproject.toml
tests/tableau/test_extractor.py

provide more Tableau chart info to users
- add chart url and preview image to crawler
unit test
local run against tableau online, and examined the MCE json.

Add preview image for Tableau chart [sc-6014]

---

metaphor/common/usage_util.py
metaphor/snowflake/usage/extractor.py
pyproject.toml

Parameters of `init_dataset` are not used properly.
Use `platform` as part of `DatasetLogicalID`.
Change type of `account` to `Optional[str]`
Local tests passed.

Improve `init_dataset` in UsageUtil [sc-6084]

---

metaphor/bigquery/usage/extractor.py
pyproject.toml

The connector currently fails to read the JSON key file from S3.
As titled.
Manually tested against S3.

Use smart_open instead of standard open to support S3 read/write

---

docs/model.md

Add initial documentation on how the data model works in the connectors.
As titled.
N/A

Add Data model documentation

---

metaphor/common/entity_id.py
metaphor/tableau/README.md
metaphor/tableau/config.py
metaphor/tableau/extractor.py
metaphor/tableau/query.py
pyproject.toml
tests/tableau/config.yml
tests/tableau/test_config.py
tests/tableau/test_extractor.py

Lineage info can help user understand the source data of the dashboards
- parse tableau upstream dataset using Metadata API (graphql)
unit tests
local run successfully, MCE looks good

Tableau Lineage [sc-5919]

---

metaphor/redshift/usage/README.md
metaphor/redshift/usage/__main__.py
metaphor/redshift/usage/config.py
metaphor/redshift/usage/extractor.py
pyproject.toml
tests/redshift/usage/config.json
tests/redshift/usage/config.yml
tests/redshift/usage/data/result.json
tests/redshift/usage/data/sample_log.json
tests/redshift/usage/test_config.py
tests/redshift/usage/test_extractor.py

To add Redshift usage crawler.
- Add `metaphor.reshift.usage.extractor.RedshiftUsageExtractor`
- Add testcases
The local test successfully.

Add Redshift usage crawler [sc-3968]

---

README.md

It's missing from the root README.
As titled
N/A

Add link to redshift usage connector

---

metaphor/postgresql/README.md
metaphor/postgresql/extractor.py
metaphor/redshift/README.md
metaphor/redshift/extractor.py
pyproject.toml

Using system catalogs to retrieve dataset information.
Rewrite `_fetch_table`, `_fetch_columns` and `_fetch_constraints`.
Manually test postgres and redshift connector, no different after refactoring.

Refactor redshift & postgres crawlers using system catalogs [sc-5078]

---

metaphor/common/s3.py

https://stackoverflow.com/questions/2057045/os-makedirs-doesnt-understand-in-my-path
As titled.
Manually tested by specifying `~` in the `directory` config.

Support tilde expansion when creating output directories

---

.pre-commit-config.yaml
metaphor/bigquery/README.md
metaphor/bigquery/config.py
metaphor/bigquery/extractor.py
metaphor/bigquery/profile/extractor.py
metaphor/bigquery/usage/extractor.py
metaphor/common/filter.py
metaphor/postgresql/extractor.py
metaphor/redshift/usage/extractor.py
metaphor/snowflake/extractor.py
metaphor/snowflake/profile/extractor.py
metaphor/snowflake/usage/extractor.py
tests/bigquery/test_config.py
tests/bigquery/test_extractor.py
tests/bigquery/usage/test_config.py
tests/common/test_filter.py

To use a general dataset filter.
Remove regular expression based filter, and apply general dataset filter.
Manually test BigQuery connector successfully.

Refactor filter for BigQuery crawler [sc-6267]

---

metaphor/snowflake/profile/README.md
metaphor/snowflake/profile/config.py
metaphor/snowflake/profile/extractor.py
tests/snowflake/profile/test_extractor.py

Apply sampling config for general profiling connector.
- Refactor Snowflake profile connector to use new sampling config.
Tests passed.

Refactor Snowflake sampling config [sc-6268]

---

pyproject.toml

We've covered all the breaking changes in https://github.com/MetaphorData/connectors/issues/95 except `pydantic`, which technically isn't really backward incompatible. Time to bump up the version!
As titled.
N/A

Bump up version to 0.10

---

metaphor/bigquery/usage/extractor.py
pyproject.toml

Accidentally remove a line in previous PR #136, did not test the connector manually after a refactor.
Add this line of code back and use a non-default variable name to prevent this happen.
Manually test BQ usage connector.

BigQuery usage crawler fail [sc-6363]

---

metaphor/bigquery/README.md
metaphor/dbt/README.md
metaphor/google_directory/README.md
metaphor/looker/README.md
metaphor/metabase/README.md
metaphor/postgresql/README.md
metaphor/redshift/README.md
metaphor/snowflake/README.md
metaphor/tableau/README.md

Updated the file sink README in https://github.com/MetaphorData/connectors/pull/138, but forgot to update each crawler README.
- Update readme for each crawler
n/a

update readme on output directory

---

metaphor/redshift/usage/extractor.py
pyproject.toml

A nonterminated connection causes an SSL transport error.
Close the connection after retrieving all usage.
Manually run Redshift usage connector successfully.

Redshift usage SSL error [sc-6388]

---

metaphor/common/extractor.py
pyproject.toml

Currently it's not printing it anywhere.
As titled.
Manually throw an exception to verify.

Print exception stack trace to stderr

---

metaphor/bigquery/lineage/extractor.py
metaphor/bigquery/utils.py
pyproject.toml
tests/bigquery/lineage/data/sample_log.json

the referenced tables in big query log may contain duplicates
- remove duplicates and self-referencing when parsing a log
unit tests

BQ lineage crawler needs to filter out duplicated [sc-6440]

---

metaphor/dbt/README.md
poetry.lock
pyproject.toml

pydantic is marked as an extra for dbt, so poetry did not include it as a required dependency.
- Remove the dbt extra to make pydantic required
- Update version for some libraries
published to testpypi, the setup.py in the package correctly shows the required dependency

Fix pydantic dependecy

---

metaphor/tableau/README.md

The reason for requiring admin role for Tableau crawler is inaccurate
- Update the reason for requiring admin role for Tableau crawler
n/a

Update README for tableau crawler permission

---

metaphor/tableau/README.md

Add information on how to check backfill status for Tableau Metadata API

---

metaphor/common/entity_id.py
metaphor/dbt/extractor.py
pyproject.toml
tests/dbt/data/trial_v3/catalog.json
tests/dbt/data/trial_v3/manifest.json
tests/dbt/data/trial_v3/results.json

[dbt alias](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/using-custom-aliases) is a useful feature that our customer may utilize.
- Use dbt alias name to replace dbt name when applicable.
tested on newly generated manifest and catalog using dbt 0.21, added alias in model
The processed MCEs only differ in order and has the alias name in target dataset.

Support DBT alias [sc-2527]

---

metaphor/tableau/query.py
pyproject.toml

Some fields are not used, need some clean-up.
- Remove unused fields in GQL query
local crawler run successfully, produced same results.

simplify Tableau graqhQL query

---

metaphor/tableau/README.md

As titled. Also slightly reworded the BQ project ID-name mapping.

Add Tableau API versions supported

---

metaphor/common/usage_util.py
metaphor/metabase/extractor.py
metaphor/postgresql/extractor.py
metaphor/redshift/extractor.py
metaphor/snowflake/extractor.py
pyproject.toml

DRY
- use the common `table_fullname` function
unit tests passed

small code refactoring

---

metaphor/metabase/extractor.py
pyproject.toml
tests/metabase/test_extractor.py

The previous crawler version doesn't handle the native SQL, so the chart upstream is incomplete
- Add support for native SQL in charts, and parse the upstream datasets
Used real-world data to test, the result matches the output of BQ crawler

Metabase upstream lineage not working [sc-6577]

---

metaphor/redshift/README.md

Clarify that permission must be granted in all databases of interest.

Add additional permission info for Redshift

---

.github/workflows/cicd.yml
.pre-commit-config.yaml
poetry.lock
pyproject.toml
tests/common/test_extractor.py

Keeping dev tools up-to-date
- update dev dependency versions
- add `bandit` for code security check
bandit is working for pre-commit check. Will see if the CI works

update dev dependency versions

---

metaphor/redshift/usage/README.md

To explain why and how to give required permissions to the user.

Update redshift usage connector with required permissions

---

metaphor/bigquery/extractor.py
metaphor/bigquery/profile/extractor.py
metaphor/snowflake/extractor.py
metaphor/snowflake/profile/extractor.py
pyproject.toml
tests/bigquery/expected.json

BQ array data type doesn't support `DISTINCT`
- Skip `DISTINCT` query on complex data types
unit test
added array and struct type in metaphor BQ instance to test out

Bigquery profiler failed to handle array [sc-6748]

---

metaphor/bigquery/profile/extractor.py
pyproject.toml

To remove debug use exception
- Bug fix
n/a

Add more context to BQ profiler when waiting on jobs to complete [sc-6765]

---

metaphor/bigquery/profile/extractor.py
pyproject.toml

Crawler is stuck if the client has an error response from API.
- Check future exceptions first.
n/a, cannot reproduce an API error

Catch future exception before use it [sc-6765]

---

metaphor/redshift/lineage/extractor.py
pyproject.toml

As title.
- Add a where clause to filter out the system table.
Run connector successfully.

Redshift lineage crawler should exclude pg_catalog.*

---

poetry.lock
pyproject.toml

PyYAML is currently brought in as a `dev` dependency but is required at runtime.
As titled.
Manually tested a few connectors.

Explicitly add PyYAML as a dependency

---

metaphor/bigquery/README.md
metaphor/bigquery/config.py
metaphor/bigquery/extractor.py
metaphor/bigquery/profile/extractor.py
pyproject.toml

As title.
- Call google API in parallel
- Run `metaphor.bigquery.profile` locally. Speed up from 60 sec to 8.8 secs with 10 concurrencies.
- Run `metaphor.bigquery` locally. Speed up from 22 secs to 3.3 secs with 10 concurrencies.
Both MCE files were manually checked, no different.

Improve BigQuery crawler performance [sc-6022]

---

.github/workflows/cicd.yml
poetry.lock
pyproject.toml

As title.
- Add `pytest-cov` to package.
- Add [MishaKav/pytest-coverage-comment](https://github.com/marketplace/actions/pytest-coverage-comment) to comment coverage report to PRs.
Coverage report comment shows in this PR.

Add Python code coverage [sc-3034]

---

metaphor/common/event_util.py
metaphor/dbt/extractor.py
metaphor/dbt/manifest_parser_v4.py
metaphor/dbt/util.py
poetry.lock
pyproject.toml
tests/dbt/data/trial_v4/manifest.json
tests/dbt/data/trial_v4/results.json

dbt crawler should extract metric information from dbt 1.0 manifest
- Add metric parser for dbt manifest v4
added metric to trial project and use the generated manifest in updated unit tests

 Extract metrics as entities from dbt 1 0 [sc-6331]

---

metaphor/snowflake/README.md

It was missing from the setup instruction
Manually tested

Add missing database-level grant statement

---

README.md

As title.
Add Power BI in the top-level readme.
n/a

Update top-level readme

---

metaphor/metabase/extractor.py
pyproject.toml

The response can be huge and can easily overwhelm the more important messages.
As titled.
Ran locally to verify

Log JSON responses as debug to avoid log spamming

---

metaphor/snowflake/profile/README.md

Add db variable to setup SQL

---

metaphor/power_bi/README.md

Improve setup instructions for Power BI

---

metaphor/power_bi/extractor.py
pyproject.toml

When there are multiple workspaces to process, it's quite likely that some will fail due to permission or other errors. It's better to finish processing all remaining workspaces instead stopping the whole process. 
As titled. Also log additional information for debugging purposes.
Manually tested.

Processing all Power BI workspaces even if there's exceptions

---

metaphor/looker/lookml_parser.py
pyproject.toml

It's very noisy and can produce 100s of MBs of logs when parsing large LookML projects.
As titled.
Manually verified.

Filter out lkml parser's debug logs

---

metaphor/looker/lookml_parser.py
pyproject.toml
tests/looker/view_extension/model.model.lkml

The current approach took a shortcut when extending views & explores and result in gaps in lineage.
Resolve view & explore extensions prior to computing the lineage. 
Unit tests

Refactor LookML view & explore extension to mimic the real behavior

---

README.md
metaphor/dbt/cloud/README.md
metaphor/dbt/cloud/__main__.py
metaphor/dbt/cloud/config.py
metaphor/dbt/cloud/extractor.py
pyproject.toml
tests/dbt/cloud/config.yml
tests/dbt/cloud/test_config.py
tests/dbt/cloud/test_extractor.py
tests/dbt/test_extractor.py

To extract dbt-related metadata directly from [dbt Cloud](https://docs.getdbt.com/docs/dbt-cloud/cloud-overview).
This connector is essentially a wrapper around the [dbt core connector](https://github.com/MetaphorData/connectors/blob/main/metaphor/dbt/README.md). It uses [dbt Cloud Admin API](https://docs.getdbt.com/docs/dbt-cloud/dbt-cloud-api/admin-cloud-api) to download `manifest.json` generated from the latest successful run for a particular job and pass the file to dbt core connector for further processing.
Added unit tests & manually verified.

Add dbt cloud connector

---

metaphor/power_bi/extractor.py
pyproject.toml

The URL fields are expected to have valid URLs.
- Set default to `None` if the API doesn't return a URL field
- Write the output of scan result to a temporary file to help debug issues. 
Manually verified & ingested the data.

Give correct default value for URLs

---

poetry.lock
pyproject.toml

Dependabot has shown several important/critical issues with airflow dependency.
- Update airflow version to latest, run poetry update
locally run several crawlers, they work fine

bump airflow version

---

metaphor/bigquery/lineage/extractor.py
metaphor/common/extractor.py
metaphor/looker/lookml_parser.py
metaphor/metabase/extractor.py
metaphor/snowflake/lineage/extractor.py
metaphor/snowflake/usage/extractor.py
metaphor/snowflake/utils.py
metaphor/tableau/extractor.py
pyproject.toml

There are a few logging calls that are not following Python's best practices.
- Replace `logger.error` + `traceback.print_exc` with `logger.exception` as the latter will include the stack trace by default
- Replace `logger.error` + `logger.exception` with `logger.exception`
- Do not pass the exception as a second argument to `logger.error` as this causes `TypeError: not all arguments converted during string formatting` on Python 3.8.
Ran a few connectors locally to verify.

Making logging more pythonic

---

metaphor/thought_spot/README.md

We need ThoughtSpot Everywhere Edition to run out connector.
Update the readme of ThoughtSpot.
n/a

Improve ThoughtSpot extractor documentation.

---

metaphor/thought_spot/README.md
metaphor/thought_spot/models.py
pyproject.toml

It currently crashes when encountering sheets with no visualization defined.
As titled. Also updated README with the required permission.
Manually tested against a production installation.

Fix ThoughtSpot connector to handle empty sheets

---

metaphor/bigquery/query/README.md
metaphor/bigquery/query/extractor.py
metaphor/common/query_history.py
metaphor/common/utils.py
metaphor/snowflake/query/README.md
metaphor/snowflake/query/__main__.py
metaphor/snowflake/query/config.py
metaphor/snowflake/query/extractor.py
metaphor/snowflake/utils.py
pyproject.toml
tests/common/test_query_history.py
tests/common/test_utils.py

Extract Snowflake recent query history.
- Add Snowflake extractor
- DRY refactoring
Manually run the crawler.

Add Snowflake recent queries crawler [SC-9050]

---

tests/dbt/data/trial_v1/manifest.json
tests/dbt/data/trial_v1/results.json
tests/dbt/data/trial_v2/manifest.json
tests/dbt/data/trial_v2/results.json
tests/dbt/data/trial_v3/manifest.json
tests/dbt/data/trial_v3/results.json
tests/dbt/data/trial_v4/manifest.json
tests/dbt/data/trial_v4/results.json
tests/dbt/data/trial_v5/manifest.json
tests/dbt/data/trial_v5/results.json

The dbt test data have fallen out of sync with the [trial](https://github.com/MetaphorData/dbt/tree/main/trial) project. This makes the diff of any future changes difficult to read.
Re-sync the test data with the latest state as of https://github.com/MetaphorData/dbt/pull/57
Unit tests.

Align test data with dbt project

---

docs/develop.md
metaphor/dbt/util.py

Some parts of the development wiki is outdated.
- Fix development docs
n/a

Fix dev docs

---

Dockerfile
docs/develop.md
pyproject.toml

To allow optional monitoring using Lumigo. See https://docs.lumigo.io/docs/containerized-applications for more details.
Also updated the developer doc.
Manually tested.

Install lumigo_opentelemetry when building the Docker image

---

metaphor/looker/README.md

Missed one entry in Looker config README
- add username in looker config git section
n/a

update looker README

---

metaphor/power_bi/extractor.py
pyproject.toml

Suspect `parse_power_query` throwing `IndexError`, we will not able to parse customized power query. We made a lot of assumptions in this helper function.
- Catch `IndexError` for further investigation.
Run the extractor locally.

list index out of range error for PowerBI [sc-9875]

---

metaphor/power_bi/extractor.py
pyproject.toml

To help debug issues.
Print the full output of Power BI REST API to debug log.
Manually tested.

Add extra debug logs for Power BI connector

---

metaphor/snowflake/extractor.py
pyproject.toml

To avoid crashing due to invalid SQL in `_fetch_table_info` for empty databases.
As titled. Also proactively catch and log exceptions when running the assembled query in `_fetch_table_info`, since a well-formed query can still fail against a shared database.
Manually tested against an empty database and a shared database.

Skip empty Snowflake databases to avoid crashing

---

metaphor/bigquery/extractor.py
pyproject.toml

The BigQuery REST API only returns DDLs for (materialized) views: https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#Table
We need to query against `INFORMATION_SCHEMA.TABLES` to get DDL https://cloud.google.com/blog/topics/developers-practitioners/spring-forward-bigquery-user-friendly-sql
- Fetch table DDL from `INFORMATION_SCHEMA.TABLES`
Tested locally against bigquery instance, verified DDL in MCE

Missing BQ SQL definition statements [sc-9930]

---

metaphor/common/docs/filter.md

Strings that start with `*` are treated as [YAML aliases](https://www.educative.io/blog/advanced-yaml-syntax-cheatsheet#anchors) and must therefore be quoted properly.

Quote wildcards in example config

---

metaphor/power_bi/extractor.py
metaphor/power_bi/power_query_parser.py
pyproject.toml
tests/power_bi/test_parse_power_query.py

We skip `NativeQuery` currently. This pr will try to retrieve the SQL from NativeQuery, then use SQL parser to get the source dataset.
- Add a function to parse `NativeQuery`
- Merge power query related code into `PowerQueryParser`
Run PowerBI crawler locally.

Support Power BI lineage based on NativeQuery

---

metaphor/power_bi/extractor.py
poetry.lock
pyproject.toml
tests/power_bi/expected.json
tests/power_bi/test_extractor.py

To better organize Power BI dashboards, reports, and datasets based on the workspace & app they belong to.
As titled. Also refactored the tests for improved consistency.
Manually tested against a production Power BI deployment.

Extract PowerBI workspace & app info

---

metaphor/power_bi/power_query_parser.py
pyproject.toml

There is one if-else case not assign the variable.
- Throw an exception in that case
- Small refactor on catching errors
Verified the crawler locally.

PowerBI: local variable 'platform' referenced before assignment

---

.dockerignore
Dockerfile
pyproject.toml

To keep the open-source version clean.
As titled. Also added `.dockerignore` to speed up the build and remove source code after installation to reduce image size.
Manually built the image.

Remove lumigo dependency

---

metaphor/common/file_sink.py
tests/common/configs/config.yml
tests/common/test_config.py
tests/common/test_file_sink.py

Because it was spelled incorrectly.
As titled. 
> Note: The minor version will be bumped up along with other breaking changes in https://github.com/MetaphorData/connectors/issues/142
Unit tests

Rename "bach_size" to "batch_size" in FileSinkConfig

---

metaphor/power_bi/extractor.py
pyproject.toml
tests/power_bi/expected.json

https://github.com/MetaphorData/connectors/pull/301 missed adding workspace ID & name to Power BI datasets.
As titled. Also dropped `PowerBIExtractor.parse_power_query` as it has been moved to `power_query_parser.py` .
Manually tested against product and verified the output.

Add workspace id & name to Power BI datasets

---

metaphor/__main__.py
metaphor/bigquery/extractor.py
metaphor/snowflake/__init__.py
pyproject.toml

To add debugging process
- Add logging from config file path
- Add missing snowflake CLI
tested in local run

Log more crawler run information

---

pyproject.toml

As we've already dropped slack & google directory connectors, it's time to clean up the dependencies.
As titled.
N/A

Remove unused dependencies and extras

---

metaphor/redshift/lineage/extractor.py
pyproject.toml
tests/redshift/lineage/data/result.json
tests/redshift/lineage/test_extractor.py

As title.
- Check if object is a string before calling `rstrip`
```
$ metaphor redshift.lineage configs/redshift_lineage.yml
```
Verified the command without error, output MCE is correct.

Redshift lineage "AttributeError: 'NoneType' object has no attribute 'rstrip'

---

metaphor/bigquery/lineage/README.md
metaphor/bigquery/lineage/config.py
metaphor/bigquery/query/README.md
metaphor/bigquery/query/config.py
metaphor/bigquery/usage/README.md
metaphor/bigquery/usage/config.py
metaphor/redshift/query/README.md
metaphor/redshift/query/config.py
metaphor/redshift/usage/README.md
metaphor/redshift/usage/config.py
metaphor/snowflake/lineage/README.md
metaphor/snowflake/lineage/config.py
metaphor/snowflake/query/README.md
metaphor/snowflake/query/config.py
metaphor/snowflake/usage/README.md
metaphor/snowflake/usage/config.py
pyproject.toml
tests/snowflake/lineage/test_config.py
tests/snowflake/usage/test_config.py

A 30-day lookback period seems excessive as a default. 7 days of lineage/usage/queries is sufficient in most cases.
As titled. Also updated tests and READMEs.
Unit tests.

Reduce the default lookback_days to 7 for various connectors

---

docs/migration.md

To provide information related to breaking changes and guides on migration.

Add initial migration guide

---

metaphor/bigquery/README.md

Give concrete instructions on how to properly specify the multi-line private key in config.

Add information on BigQuery private key in config

---

metaphor/postgresql/extractor.py
pyproject.toml

To capture the DDL used to create a view.
Fetch the view definition from `pg_catalog.views` table.
Tested locally against a production deployment.

Add support for PostgreSQL & Redshift view definitions

---

README.md
metaphor/manual/metadata/README.md
metaphor/manual/metadata/__init__.py
metaphor/manual/metadata/config.py
metaphor/manual/metadata/extractor.py
pyproject.toml
tests/manual/metadata/config.yml
tests/manual/metadata/expected.json
tests/manual/metadata/test_config.py
tests/manual/metadata/test_extractor.py

To support the attachment of custom metadata to tables.
As titled.
Manually ran the connector and verified the output.

Add custom metadata connector

---

README.md

Add link to Metaphor

---

metaphor/thought_spot/extractor.py
metaphor/thought_spot/utils.py
poetry.lock
pyproject.toml

The tags can be a useful metadata to extract.
As titled. Also added extra debug logs.
Manually verified against a production instance.

Extract tags for ThoughtSpot Liveboards & Answers

---

metaphor/power_bi/extractor.py
metaphor/power_bi/power_bi_client.py
poetry.lock
pyproject.toml
tests/power_bi/expected.json
tests/power_bi/test_extractor.py

The description for measures is an important metadata for the end users.
As titled.
Tested against a production deployment.

Capture descriptions for Power BI measures

---

metaphor/bigquery/README.md
metaphor/bigquery/config.py
metaphor/bigquery/extractor.py
metaphor/bigquery/logEvent.py
metaphor/common/query_history.py
metaphor/snowflake/extractor.py
pyproject.toml
tests/bigquery/config.yml
tests/bigquery/expected.json
tests/bigquery/lineage/test_parser.py
tests/bigquery/query/test_parser.py
tests/bigquery/sample_log.json
tests/bigquery/test_config.py
tests/bigquery/test_extractor.py

fetch audit logs from big query for server side processing
- fetch audit logs from big query
tested locally against BIgQuery instance.

BigQuery query log crawler [sc-12584]

---

metaphor/power_bi/README.md
metaphor/power_bi/config.py
metaphor/power_bi/extractor.py
metaphor/power_bi/power_query_parser.py
pyproject.toml
tests/power_bi/test_parse_power_query.py

We cannot parse the source table from PBI DAX in some cases. The reason is we didn't handle the control character before parsing the SQL.
- Provide a optional snowflake account in config
- Unescape control char correctly
- Add tests to cover.
Tests.
Manually verified the MCEs

Improve PBI DAX parser for native queries

---

metaphor/manual/governance/README.md
metaphor/manual/lineage/README.md
metaphor/manual/metadata/README.md
metaphor/redshift/query/README.md

Fix links in doc

---

metaphor/glue/README.md

Improve Glue README

---

metaphor/unity_catalog/README.md
metaphor/unity_catalog/config.py
metaphor/unity_catalog/extractor.py
metaphor/unity_catalog/models.py
pyproject.toml
tests/unity_catalog/expected.json
tests/unity_catalog/test_extractor.py

The models we use was not representing the API response, and dataset filter is missing
- Update model to support `View` table type.
- Add dataset filter support in config.
Run crawler locally, and verified the MCE.

Improve unity catalog crawler

---

README.md

Link logo to the main website

---

metaphor/unity_catalog/models.py
pyproject.toml
tests/unity_catalog/expected.json
tests/unity_catalog/test_extractor.py

To extract `generation` for tables/views
- Update models
- Sort `Table` attributes alphabetically
- Unit tests
- Verified the output

Display generation in custom metadata

---

metaphor/snowflake/extractor.py
poetry.lock
pyproject.toml

Capture the snowflake account info required in the dataset ID
- fill `account` field in snowflake query log
verified in local run

add account in snowflake query log

---

metaphor/unity_catalog/extractor.py
metaphor/unity_catalog/models.py
metaphor/unity_catalog/utils.py
pyproject.toml
tests/unity_catalog/expected.json
tests/unity_catalog/test_extractor.py

Extract lineage information provided by Databricks
- Extract Table/Column lineage from Databricks API
- Use low-level `perform_query` to request the correct endpoint.
- Add tests
Unit tests, ingested the MCE to latest dev environment.

Lineage from Unity Catalog

---

metaphor/bigquery/profile/extractor.py
pyproject.toml
tests/bigquery/profile/test_extractor.py

The logical id name is case-sensitive for bigquery.
- As title
Unit tests

Revert normalized name for bigquery

---

metaphor/snowflake/extractor.py
poetry.lock
pyproject.toml

capture snowflake default DB and schema in query log, for SQL parsing usage
- fetch default DB and schema for a query
tested locally against snowflake instance.

add default db and schema in query log [sc-13621]

---

metaphor/common/file_sink.py
pyproject.toml

As title.
Including timestamp in the output log filename.
Verified on a local crawler run.

Downloaded log file name should encode date

---

metaphor/power_bi/extractor.py
poetry.lock
pyproject.toml
tests/power_bi/expected.json
tests/power_bi/test_extractor.py

No reason to keep both app and non-app version of dashboards
- Merge app information into non-app version
- Use `poetry` 1.2 to generate lock file. `poetry lock --no-update`
Unit tests. Compared before after, we have 8 assets with app enabled in our PowerBI, verified that we reduce 8 asset after the change.

Merge app non app version of pbi dashboards

---

README.md
metaphor/thought_spot/README.md

As titled. Also added the link to the root README.

Improve ThoughtSpot's README

---

README.md
metaphor/manual/governance/README.md
metaphor/manual/governance/config.py
metaphor/manual/governance/extractor.py
poetry.lock
pyproject.toml
tests/manual/governance/config.yml
tests/manual/governance/expected.json
tests/manual/governance/test_config.py

To support manually assigning one or multiple descriptions to a table using the `manual.governance` connector.
As titled.
Manually ran the connector and verified the output.

Add asset description to manual.governance connector

---

.github/workflows/ci.yml
metaphor/thought_spot/extractor.py
metaphor/thought_spot/models.py
metaphor/thought_spot/utils.py
metaphor/unity_catalog/extractor.py
poetry.lock
pyproject.toml
tests/thought_spot/data/connections.json
tests/thought_spot/data/tables.json
tests/thought_spot/expected.json
tests/unity_catalog/expected.json

To provide column level lineage
As title
- Unit tests.
- Run connector locally, ingested all 25 MCEs without errors

Column level lineage for TS tables

---

metaphor/thought_spot/extractor.py
metaphor/thought_spot/models.py
poetry.lock
pyproject.toml
tests/thought_spot/data/answers.json
tests/thought_spot/data/liveboards.json
tests/thought_spot/expected.json

Reuse `FieldMapping` to get the lineage between chart and columns
- Get `ReferenceColumn` and fill out the `fieldMapping`
- Fill out `entity_upstream` field in `Dashboard`
Unit tests, local run

Column level lineage between dashboard and data object

---

metaphor/common/file_sink.py
pyproject.toml
tests/common/test_file_sink.py

To provide a way to directly access to the storage with a `FileSink`
As title.
An unit test added

Create public methods for writing/deleting files

---

.github/workflows/ci.yml

The current coverage report doesn't include explicit coverage for new & modified files, which is more actionable than overall coverage.
As titled. Based on https://github.com/orgoro/coverage
https://github.com/MetaphorData/connectors/actions/runs/3472940644/jobs/5804392560

Use orgoro/coverage@v3 for coverage reporting

---

pyproject.toml

https://github.com/MetaphorData/connectors/pull/420 forgot to bump up the version.

Bump up version

---

.github/workflows/cd.yml

To make the badge and historical trend work.
As titled.
https://github.com/MetaphorData/connectors/actions/runs/3503504810
https://coveralls.io/github/MetaphorData/connectors

Publish coverage to coveralls when merging PRs

---

metaphor/dbt/manifest_parser.py
pyproject.toml
tests/dbt/data/trial_v1/manifest.json
tests/dbt/data/trial_v1/results.json
tests/dbt/data/trial_v2/manifest.json
tests/dbt/data/trial_v2/results.json
tests/dbt/data/trial_v3/manifest.json
tests/dbt/data/trial_v3/results.json
tests/dbt/data/trial_v4/manifest.json
tests/dbt/data/trial_v4/results.json
tests/dbt/data/trial_v5/manifest.json
tests/dbt/data/trial_v5/results.json
tests/dbt/data/trial_v6/manifest.json
tests/dbt/data/trial_v6/results.json
tests/dbt/data/trial_v7/manifest.json
tests/dbt/data/trial_v7/results.json

https://github.com/MetaphorData/connectors/pull/271 added the ability to tag tables using dbt's `meta` field. This PR extends it to the column-level.
- Parse tags from column's `meta` field
- Align the database name (`dev_db`) in test data files for all dbt versions  
Unit tests

Support column level tagging in dbt via meta

---

poetry.lock
pyproject.toml

Update metaphor-models to bring in new DQ vendor enum

---

metaphor/power_bi/extractor.py
pyproject.toml

Some reports or dashboards are missing, the reason is we would merge app and non-app version into a app version dashboard. However, in the current code, we merge multiple time which could remove the version which was already merged.
- Move merging code to the end
Verified the missing report is in the MCE

Power bi crawler miss some entity

---

metaphor/synapse/README.md
metaphor/synapse/extractor.py
metaphor/synapse/workspace_client.py
pyproject.toml

set the steps to creat non-admin user
add readMe for create non-admin user
manual test

Identify necessary permission to query synapse [sc-14890]

---

metaphor/tableau/extractor.py
pyproject.toml
tests/tableau/test_extractor.py

The URL returned from the API may not be reachable, especially in the case of Tableau on-prem.
As titled.
Manually verified against a production instance.

Construct Tableau base URL from server_url & site_name from config

---

metaphor/tableau/extractor.py
pyproject.toml
tests/tableau/test_extractor.py

https://github.com/MetaphorData/connectors/pull/446 replaced the URLs for data sources & views but missed the dashboards.
As titled.
Manually verified against a production deployment.

Use server URL provided in config for Tableau dashboards

---

metaphor/common/file_sink.py
pyproject.toml
tests/airflow_plugin/lineage/test_backend.py
tests/common/test_file_sink.py

To capture each run metadata and log
- Sink all output file in a run-specific folder
Updated tests and verified locally.

Save crawler run metadata and log file in a run-specific folder

---

metaphor/mssql/README.md

add the support MSSQL version description  in ReadMe
same as above
Manual test and see on the [Github](https://github.com/MetaphorData/connectors/blob/jerryhuang9816/sc-15561/add-the-version-support-description-for-mssql/metaphor/mssql/README.md)

add version support description

---

.github/workflows/ci.yml
Dockerfile
README.md
metaphor/mysql/README.md
metaphor/mysql/extractor.py
poetry.lock
pyproject.toml

Docker image build is failing.
- Use pure-python mysql library for SQLAlchemy
- Add docker build step in CI
- Add link to mysql crawler in top-level readme.
Verified locally with identical result.

Fix MySQL cd pipeline

---

poetry.lock
pyproject.toml

sqlalchemy is missing in the latest docker image
- Add sqlalchemy in `pyproject.toml`
Verified in local docker environment
```
pip install <path_to_connector>[all]
metaphor mysql <config_file>
```
No importError after change

Add sqlalchemy in dependency

---

metaphor/common/filter.py
metaphor/mssql/README.md
metaphor/mssql/config.py
metaphor/mssql/extractor.py
metaphor/synapse/README.md
metaphor/synapse/config.py
metaphor/synapse/extractor.py
pyproject.toml
tests/common/test_filter.py
tests/mssql/config_with_filter.yml
tests/mssql/expected_with_filter.json
tests/mssql/test_config.py
tests/mssql/test_extractor.py
tests/synapse/config_with_filter.yml
tests/synapse/expected_with_filter.json
tests/synapse/test_config.py
tests/synapse/test_extractor.py

allow client can specify databases, schemas, and tables to crawl  in the connector
- implement DatasetFilter in MSSQL, Synapse connector
- add `filter` parameter to config
- unit test
- manual test

dataset filter implementation 

---

metaphor/tableau/extractor.py
poetry.lock
pyproject.toml

Newer version of tableau SDK has stricter typing, e.g. many fields are now `Optional[str]` instead of `str`, which breaks the mypi checks
- upgrade tableau SDK to latest
- fix various mypi issues
tested against tableau server in local and compared the output json

Upgrade Tableau SDK breaks MyPy checks [sc-9826]

---

metaphor/bigquery/extractor.py
metaphor/bigquery/logEvent.py
metaphor/synapse/extractor.py
poetry.lock
pyproject.toml
tests/bigquery/expected.json
tests/bigquery/lineage/test_parser.py
tests/bigquery/sample_log.json
tests/synapse/expected_sqlpool_with_query_log.json
tests/synapse/expected_with_query_log.json

the default dataset and statement type can be used by CLL parser to return better results
- Extract default dataset for BigQuery log if available
- map query statement type to Enum
unit tests
tested locally against BigQuery instance

BigQuery log capture default dataset and statement type [sc-16989]

---

metaphor/thought_spot/extractor.py
pyproject.toml
tests/thought_spot/data/data_objects.json
tests/thought_spot/expected.json

The table lineage was not included in the previous PR.
- as title
Add tests

Lineage for thought spot sql view

---

metaphor/fivetran/extractor.py
metaphor/fivetran/models.py
poetry.lock
pyproject.toml
tests/fivetran/data/v1__metadata__connectors.json
tests/fivetran/expected.json

To fill the logo url for Fivetran crawler
as title
unit test

Add connector logo url to the fiveTranConnector

---

metaphor/snowflake/extractor.py
metaphor/snowflake/lineage/extractor.py
metaphor/snowflake/profile/extractor.py
pyproject.toml

Same as https://github.com/MetaphorData/connectors/pull/504 but for various Snowflake connectors.
As titled.
Tested against a production instance & manually verified the MCEs.

Normalize PrivateLink Snowflake account names for Snowflake connectors

---

metaphor/common/utils.py

https://github.com/MetaphorData/connectors/pull/509 missed the commit that improves the documentation for `chunk_by_size` function.
As titled.
N/A

Improve comments for chunk_by_size

---

metaphor/snowflake/extractor.py
pyproject.toml
tests/snowflake/test_extractor.py

Support column level Snowflake tags  
- extract tags for columns from snowflake
> Note that the [TAG_REFERENCES View](https://docs.snowflake.com/en/sql-reference/account-usage/tag_references) takes up to 2hr to populate
tested locally against snowflake instance, and verified MCE

Support column level Snowflake tags [sc-18488]

---

docs/migration.md
pyproject.toml

Bumped up the version and added the migration doc.

Release v0.12

---

metaphor/airflow_plugin/README.md

Improve Airflow doc

---

README.md
docs/docker.md
metaphor/common/docs/output.md

Improve document for Docker usage

---

README.md
metaphor/monte_carlo/README.md

Fix various typos in README

---

metaphor/synapse/README.md

Improve instructions for Synapse

---

metaphor/monte_carlo/README.md

Improve instructions for Monto Carlo connector

---

metaphor/tableau/extractor.py
metaphor/tableau/query.py
pyproject.toml
tests/tableau/expected.json
tests/tableau/test_extractor.py

#543 added support for the nested project for tableau dashboard, but forgot to do the same for tableau datasources.
- add support for the nested project of tableau datasources.
tested against tableau server and verified the MCE

add tableau project hierarchy to datasources

---

metaphor/power_bi/power_bi_client.py
pyproject.toml

We will get a workspace scan result without `name` and `type` for not existing workspace.
- Make these two field optional in the model
Verified against production env.

PowerBI crawler parsing error on not existing workspace

---

.github/workflows/backup.yml

To ensure that the repo is backed up to S3 daily.
As titled.
New GitHub workflow can only be tested after merging.

Backup repo to S3

---

metaphor/common/entity_id.py
metaphor/common/event_util.py
poetry.lock
pyproject.toml
tests/common/test_file_sink.py

`metaphor-models` 0.22 dropped `person` from MCE.
As titled. Also fixed imports & tests. 
Unit tests.

Update metaphor-models to 0.22

---

poetry.lock
pyproject.toml

To bring in the latest model changes, namely dropping of unused fivetran fields.
As titled.
Manually verified against a production Fivetran instance.

Update metadata-models to 0.23

---

metaphor/common/event_util.py
poetry.lock
pyproject.toml
tests/airflow_plugin/lineage/test_backend.py

Bring in the latest version of `metaphor-models`.
- Update `metaphor-models` to 0.25
- Replace `fastjsonschema` with `jsonschema` as the former has a serious bug that corrupts the object being validated. The latter is also far more popular and supports a variety of JSON schema specs.
Manually ran a few connectors against production instances.

Update metaphor-models to 0.25

---

poetry.lock
pyproject.toml

To bring in the latest models.
As titled.
Unit tests

Update metaphor-models to 0.26

---

docs/custom.md
examples/custom_dashboard.py
examples/custom_dq.py
examples/custom_lineage.py
metaphor/common/runner.py
pyproject.toml

To demonstrate how to write a custom dashboard connector.
As titled. Also use the opportunity to
- Move all examples out of the markdown file to a dedicated folder for automated checking & formatting
- Add an optional`s3_auth_config` argument to `metaphor_file_sink_config` 
- Change the default value of `is_metaphor_cloud` to `False` for `metaphor_file_sink_config` 
Verified the examples end-to-end locally.

Add example for a custom dashboard connector

---

metaphor/power_bi/extractor.py
metaphor/thought_spot/extractor.py
pyproject.toml
tests/power_bi/expected.json
tests/thought_spot/expected.json

As title, to fill out generic dashboard type
- Fill out `DashboardType`
Update unit tests, verified end-to-end with API ingestion

Fill out DashboardType field

---

examples/custom_dashboard.py

It wasn't running correctly out of the box.
As titled. Also showcase how to set the `structure` field and S3 auth credentials.
Verified the example end-to-end.

Fix custom dashboard example

---

metaphor/azure_data_factory/extractor.py
metaphor/common/utils.py
poetry.lock
pyproject.toml
tests/azure_data_factory/expected.json
tests/azure_data_factory/test_extractor.py
tests/common/test_utils.py

To extract information of a ADF pipeline
- Add `AzureSqlDatabase` support
- Populate pipeline information
Update unit tests and verified generated MCE with a pipeline (Task[Snowflake -> AzureSqlTable] -> Copy[AzureSqlTable -> AzureBlob])

Extract ADF pipeline & MSSQL dataset

---

metaphor/azure_data_factory/extractor.py
metaphor/common/entity_id.py
pyproject.toml
tests/azure_data_factory/expected.json

To build the relation between pipeline and dataset upstream.
- as title
unit tests

Fill out upstream pipeline id

---

.github/workflows/ci.yml

Codecov seems to provide a better coverage tool.
As titled.
Will find out how it is after the PR is merged.

Add codecov for coverage reporting

---

.github/workflows/cd.yml
.github/workflows/ci.yml

Forgot to add Codecov to CD in https://github.com/MetaphorData/connectors/pull/594.
As titled.
https://github.com/MetaphorData/connectors/actions/runs/6162524072

Add Codecov to CD

---

.github/workflows/cd.yml
.github/workflows/ci.yml
README.md

Codecov output [looks decent](https://app.codecov.io/gh/MetaphorData/connectors/tree/main). Time to ditch coverall.
As titled.
https://github.com/MetaphorData/connectors/actions/runs/6164485211?pr=597

Drop codecov

---

metaphor/thought_spot/extractor.py
metaphor/thought_spot/models.py
metaphor/thought_spot/utils.py
poetry.lock
pyproject.toml
tests/thought_spot/data/connections.json
tests/thought_spot/data/data_objects.json
tests/thought_spot/expected.json

The search metadata endpoint throw 500 when getting connection information. The support teams suggest us to use the new endpoint.
- Change model and use new endpoint
- Update ThoughtSpot REST client to the latest
1. unit tests updated
2. Verified against our environment and the extracted metadata before and after is identical
3. Verified against customer environment and didn't get any API error.

[ThoughtSpot] Use new connection endpoint

---

metaphor/azure_data_factory/extractor.py
metaphor/common/api_request.py
metaphor/power_bi/extractor.py
metaphor/power_bi/power_bi_client.py
poetry.lock
pyproject.toml
tests/azure_data_factory/test_extractor.py
tests/power_bi/data/user_subscriptions.json
tests/power_bi/expected.json
tests/power_bi/test_extractor.py
tests/power_bi/test_power_bi_client.py

To get Dashboard/Report subscription information from PowerBI
- As title, extract data
- Update ADF crawler for the model change
Add unit tests
Run the crawler against our PowerBI instance.

Extract PBI subscription metadata

---

metaphor/power_bi/extractor.py
metaphor/power_bi/power_bi_client.py
metaphor/power_bi/power_query_parser.py
poetry.lock
pyproject.toml
tests/power_bi/data/dataflow_1.json
tests/power_bi/expected.json
tests/power_bi/test_extractor.py
tests/power_bi/test_parse_power_query.py
tests/power_bi/test_power_bi_client.py

To extract Power BI Dataflow metadata, and lineage created by the dataflow
- Model PBI Dataflow as Metaphor pipeline
- Parse table lineage from dataflow definition
Ingested MCE generated to dev.
Unit tests

Get Power BI dataflow metadata

---

metaphor/power_bi/extractor.py
poetry.lock
pyproject.toml
tests/power_bi/expected.json

Get the link to PBI Dataflow
as title
Verified the generated URL is valid

Power BI dataflow url

---

metaphor/common/utils.py
metaphor/power_bi/extractor.py
metaphor/power_bi/power_bi_client.py
poetry.lock
pyproject.toml
tests/common/test_utils.py
tests/power_bi/expected.json
tests/power_bi/test_extractor.py

To get more metadata from Power BI APIs
- Add owner/modifier information
- Add endorsement information
Unit tests

Power BI report dashboard owner editor metadata

---

metaphor/snowflake/extractor.py
pyproject.toml
tests/snowflake/test_extractor.py

Based on https://docs.snowflake.com/en/sql-reference/account-usage/query_history, we should set 
- `rows_read` to `ROWS_PRODUCED`
- `rows_written` to `ROWS_INSERTED` or `ROWS_UPDATED`
As titled.
Verified the output against a production instance.

Fix Snowflake rows read & written exraction

---

metaphor/power_bi/power_bi_client.py
pyproject.toml
tests/power_bi/data/workspace_scan.json
tests/power_bi/test_power_bi_client.py

The name and description could be null or undefined.
- Make field optional with default `None`
Unit test added.
Verified against production environment.

Fix Power BI dataflow model errors

---

metaphor/common/file_sink.py
poetry.lock
pyproject.toml

To help debugging S3 file sink issue
- add more logs to file sink
- bump boto3 to latest version
n/a

add more logs to file sink

---

metaphor/common/file_sink.py
metaphor/common/storage.py
pyproject.toml

Help with debugging some potential S3 sink issues
- add more logging the S3 sink
n/a

add more logging the S3 sink

---

metaphor/azure_data_factory/extractor.py
metaphor/monte_carlo/extractor.py
metaphor/power_bi/extractor.py
metaphor/tableau/extractor.py
metaphor/thought_spot/extractor.py
pyproject.toml

```
DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
```
As titled.
Unit tests

Replace deprecated logger.warn function with logger.warning

---

metaphor/dbt/cloud/config.py
metaphor/dbt/cloud/extractor.py
tests/dbt/cloud/config_legacy.yml
tests/dbt/cloud/test_config.py

We've long migrated from `job_id` to `job_ids`.
As titled. Will bump up the minor version once all [breaking changes](https://github.com/MetaphorData/connectors/issues/523) are merged.
Manually verified against a production instance.

Drop job_id from dbt cloud config

---

docs/migration.md
pyproject.toml

All [breaking changes](https://github.com/MetaphorData/connectors/issues/523) have been merged. Time to bump up the minor version.
As titled. Also added migration notes.
N/A

Bumping up version to 0.13

---

poetry.lock
pyproject.toml

In an attempt to fix the following error on Linux: 
```
File "/usr/local/lib/python3.8/site-packages/oscrypto/_openssl/_libcrypto_cffi.py", line 44, in <module>
raise LibraryNotFoundError('Error detecting the version of libcrypto')
```
As titled.

Update snowflake-connector-python to latest version

---

.github/workflows/ci.yml

Enable GitHub [Merge Queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue) for CI.

Enable merge queue

---

metaphor/tableau/extractor.py
poetry.lock
pyproject.toml
tests/tableau/expected.json

To prepare for server-side SQL parsing
- fill in the `query` field in datasource
unit test
verified MCE after running the crawler

Fill in Tableau datasource query [sc-20693]

---

metaphor/tableau/extractor.py
poetry.lock
pyproject.toml
tests/tableau/expected.json

To get enough context for SQL parsing
- add source `platform` and `account` info for custom SQL
unit test
tested against Tableau server and verified MCE

add platform and account for tableau datasource custom query

---

metaphor/power_bi/extractor.py
poetry.lock
pyproject.toml
tests/power_bi/expected.json

The crawler part of adding workspace to the AH
- Fill out workspace id in `Pipieline`
- Extract PBI dataflow `Hierarchy`
Update tests. Verified end-to-end, the AH looks good.

Add workspace to pbi data flow asset hierarchy

---

metaphor/power_bi/extractor.py
metaphor/power_bi/power_bi_client.py
poetry.lock
pyproject.toml
tests/power_bi/data/dataflow_transactions.json
tests/power_bi/expected.json
tests/power_bi/test_extractor.py
tests/power_bi/test_power_bi_client.py

Get last refresh like we did for PBI dataset
Get last success refresh time from the API.
Verified the output MCE

Get Power BI dataflow last refresh

---

metaphor/common/utils.py
metaphor/unity_catalog/extractor.py
metaphor/unity_catalog/models.py
poetry.lock
pyproject.toml
tests/common/test_utils.py
tests/unity_catalog/expected.json
tests/unity_catalog/test_extractor.py

As titled. Also fill out the `source_info` field to point the dataset to the corresponding page on Databircks.

Move UC-specific metadata from CustomMetadata to dedicated fields

---

metaphor/power_bi/extractor.py
metaphor/power_bi/power_bi_client.py
pyproject.toml
tests/power_bi/expected.json
tests/power_bi/test_extractor.py

To capture creator(configuredBy) and create date for PBI datasets
as title
Unit tests, verified local run generated correct MCE

Extract platform detail for pbi datasets

---

metaphor/snowflake/config.py
metaphor/snowflake/extractor.py
pyproject.toml
tests/snowflake/test_extractor.py

Sometimes there can be queries that insert a huge amount of raw data that should be ignored.
As titled.

Add config to filter out large queries from Snowflake query logs

---

metaphor/power_bi/extractor.py
poetry.lock
pyproject.toml
tests/power_bi/expected.json

We need to show the actors even if they are not in Metaphor system. If we only captured `personId` we would not be able to get unknown person information.
Fill email in actorInfo
Unit test

Get email address for the power bi view activity

---

metaphor/dbt/manifest_parser.py
pyproject.toml

Some dbt models are missing the raw/complied SQL code in the generated MCE.
Use `hasattr` to test the existence of version-specific fields instead of relying on logic based on `isinstance`. The latter is more error-prone and more difficult to reason, which led to the original bug.

Fix missing SQL code in dbt models

---

metaphor/custom/governance/README.md
metaphor/custom/governance/config.py
metaphor/custom/governance/extractor.py
poetry.lock
pyproject.toml
tests/custom/governance/config.yml
tests/custom/governance/expected.json
tests/custom/governance/test_config.py

For tags we already have support for both table-level and column-level, but for descriptions only table-level is currently supported. This PR aims to implement column-level descriptions.
Tracked with [SC22046](https://app.shortcut.com/metaphor-data/story/22046).
- Implemented the parsing logic.
- Updated custom.governance readme with example.
-
Ran unit tests locally.

Support column descriptions for `custom.governance` extractor

---

metaphor/common/query_history.py
metaphor/snowflake/extractor.py
metaphor/unity_catalog/extractor.py
pyproject.toml
tests/common/test_query_history.py

Simliar to https://github.com/MetaphorData/connectors/pull/660, but for Unity Catalog.
As titled. Also factor out common code to an until method.

Set email field in UC query log if it contains a valid email address

---

metaphor/common/filter.py
pyproject.toml
tests/common/test_filter.py

`DatasetFilter`'s schema filter doesn't support wildcard patterns. This PR addresses that.
Use `fnmatch` to match patterns instead of simple existential checks.
Wrote unit test to test against the new logic.

Fix schema filter glob condition

---

pyproject.toml

I forgot.
As titled.
trust me.

bump version for dbt test result crawler

---

metaphor/azure_data_factory/extractor.py
pyproject.toml

Need this information to improve the ADF crawler to support sources like SFTP, REST resource.
- Add json_dump for pipelines
unit test

Capture ADF pipeline information

---

metaphor/dbt/artifact_parser.py
metaphor/dbt/util.py
tests/dbt/data/metaphor_subscriptions_v10/results.json

In `run_results.json` it is possible for the test results to not have column names. Allow this in the connector code.
as titled.
N/A.

Fix parse dbt test error: assert -> return if test.column_name not found

---

pyproject.toml

Because I suck QQ
As titled
No

Bump version for SC-22335

---

docs/develop.md

macOS users need to install `freetds` manually.

Add macOS setup instructions

---

.github/PULL_REQUEST_TEMPLATE.md
.github/scripts/check_version.sh
.github/scripts/compare_versions.py
.github/workflows/ci.yml
pyproject.toml

If there's actual changes in the repo we want to make sure the version number has been bumped.
- Added CI action and script.
- Added checklist section in PR template.

Add CI check for updated version on actual code change

---

metaphor/snowflake/extractor.py
metaphor/snowflake/utils.py
poetry.lock
pyproject.toml
tests/snowflake/test_extractor.py

Snowflake streams can and should be parsed as datasets.
As titled.
- Unit test
- Tested end to end on personal dev

Implement connector logic to parse Snowflake streams

---

metaphor/snowflake/utils.py
pyproject.toml

We didn't include all possible snowflake table types in the enum, which could cause the connector to fail.
As titled.
N/A.

Include all possible table types in the enum

---

metaphor/snowflake/extractor.py
poetry.lock
pyproject.toml
tests/snowflake/test_extractor.py

For `systemTags` to be valid aspect, `Hierarchy.system_tags` has to be an object instead of a simple array.
As titled.
- Tested with ingester on personal dev
- Unit test

Change hierarchy systemTags type

---

metaphor/snowflake/extractor.py
pyproject.toml

Because it should be case sensitive, but isn't.
Fixes that.
Unit test.

`Hierarchy.logiclId.path` is case sensitive

---

metaphor/dbt/artifact_parser.py
metaphor/dbt/extractor.py
metaphor/dbt/util.py
pyproject.toml
tests/dbt/data/metaphor_subscriptions_v10/manifest.json
tests/dbt/data/metaphor_subscriptions_v10/results.json
tests/dbt/data/metaphor_subscriptions_v10/run_results.json

We cannot find the materialized dataset if the dataset was not initialized before. So we can't extract the DQ status for some datasets.
- Init dataset before using it
- add `test_results.json` to debug file
Unit test

Fix dbt test result parser

---

metaphor/snowflake/config.py
metaphor/snowflake/extractor.py
metaphor/snowflake/lineage/config.py
metaphor/snowflake/profile/config.py
pyproject.toml
tests/common/test_utils.py
tests/snowflake/test_accessed_object.py
tests/snowflake/test_config.py
tests/snowflake/test_extractor.py

Snowflake connector crashes when fetching 
- Fix logic error in Streams staleness parsing & improve tests.
- Improve robustness in Streams row counting
- Add configs for Snowflake Streams and refactor the config class hierarchy.

Fix various bugs related to Snowflake Streams

---

metaphor/snowflake/utils.py
pyproject.toml

Story details: https://app.shortcut.com/metaphor-data/story/22517
Reference: https://docs.snowflake.com/en/sql-reference/sql/show-streams#output

fix: [sc-22517] Support "External Table" source for Snowflake streams

---

metaphor/common/event_util.py
metaphor/common/sink.py
pyproject.toml

Validating MCEs sequentially is too slow, gotta do this in parallel.
Uses concurrent.future.ThreadPoolExecutor to validate the records in parallel.
Ran crawler locally.

Use ThreadPoolExecutor to speed up MCE validation time

---

metaphor/snowflake/extractor.py
metaphor/snowflake/utils.py
pyproject.toml
tests/snowflake/test_extractor.py

We found a table type that isn't supposed to be a valid value, and it's causing the crawler to break.
Only parse the recognizable values.
Unit test.

If snowflake table type is not a known values, don't parse it into Dataset

---

metaphor/dbt/artifact_parser.py
pyproject.toml
tests/dbt/data/jaffle_v10/results.json
tests/dbt/data/metaphor_subscriptions_v10/results.json
tests/dbt/data/trial_v4/results.json
tests/dbt/data/trial_v5/results.json
tests/dbt/data/trial_v6/results.json
tests/dbt/data/trial_v7/results.json
tests/dbt/data/trial_v8/results.json
tests/dbt/data/trial_v9/results.json

To populate `AssetStructure` for DBT model views.
- Added logic to keep track of model's directories and name.
Unit test.

Add assetStructure to dbt model views

---

metaphor/snowflake/extractor.py
pyproject.toml
tests/snowflake/test_extractor.py

Snowflake db & schema level tags should respect filter settings.
Added logic to filter out excluded system tags.
- Unit test.
- Tested locally.

Snowflake system tags should respect filter settings

---

metaphor/looker/extractor.py
metaphor/looker/lookml_parser.py
pyproject.toml
tests/looker/expected.json
tests/looker/test_extractor.py
tests/looker/test_lookml_parser.py

To populate `AssetStructure` for lookml dashboards and virtual views.
As titled.
Unit test.

Add assetStructure to lookml dashboards and virtual views

---

README.md

Add top-level link for Kafka

---

metaphor/tableau/extractor.py
pyproject.toml
tests/tableau/test_extractor.py

Forgot to actually skip ignored workbooks.
Added single `continue` to make loop skip excluded stuff.
Unit test was broken, hence not catching the bug. Fixed it and now it will exclude the workbooks in `Personal Space`.

Fix tableau excluded projects bug

---

metaphor/power_bi/extractor.py
metaphor/power_bi/models.py
pyproject.toml

`users` field in workspace could be null
- Make it optional
Verified against production env

Make users in PBI models optional

---

metaphor/snowflake/extractor.py
pyproject.toml
tests/snowflake/test_extractor.py

In snowflake, tags follow the below inheritance:
`database -> schema -> table -> column`
In other words, a tag on a database should also be a tag for every column within that database.
See https://docs.snowflake.com/en/user-guide/object-tagging#tag-lineage for more info.
Modified the logic for tag inheritance.
Tested end to end: https://www.loom.com/share/0957a7f6fcac456ebcd7caaeefd06b9c

Snowflake tag inheritance

---

.github/workflows/cd.yml

Our hive crawler requires `libsasl2-dev` be installed. Our cd workflow did not have it so it was breaking constantly.
Install the dependency for cd workflows.
No need.

Add libsasl2-dev library to cd workflow

---

metaphor/dbt/artifact_parser.py
pyproject.toml
tests/dbt/data/ride_share/expected.json
tests/dbt/data/ride_share/manifest.json
tests/dbt/data/ride_share/run_results.json

dbt snapshots can also be an upstream for other dbt models.
Added a single line to be able to select snapshots as models' entity upstream.
Tested locally and modified unit test.

dbt model lineage should parse snapshot as valid entity upstream

---

metaphor/monte_carlo/config.py
metaphor/monte_carlo/extractor.py
pyproject.toml
tests/monte_carlo/expected.json
tests/monte_carlo/test_extractor.py

When MC monitors time out, it is treated as an error, which can lead to confusion.
As titled.

Add configs to ignore MC timeout errors by default

---

metaphor/snowflake/profile/extractor.py
pyproject.toml

Snowflake profile connector starts failing with the following error:
```
2024-01-17 13:42:39:ERROR:metaphor:too many values to unpack (expected 11)
File "/Users/marslan/Metaphor/connectors/metaphor/common/runner.py", line 51, in run_connector
entities = connector.run_async()
File "/Users/marslan/Metaphor/connectors/metaphor/common/base_extractor.py", line 38, in run_async
File "/Users/marslan/.pyenv/versions/3.9.18/lib/python3.9/asyncio/runners.py", line 44, in run
File "/Users/marslan/.pyenv/versions/3.9.18/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
File "/Users/marslan/Metaphor/connectors/metaphor/snowflake/profile/extractor.py", …
```

Handle extra columns returned from Snowflake SHOW COLUMNS command

---

metaphor/azure_data_factory/extractor.py
pyproject.toml
tests/azure_data_factory/test_extractor.py

`duration_in_ms` could be `None` and cause crawler fail
- Use `safe_float`
Unit test covered

float argument must be a string or a number

---

.github/workflows/backup.yml
.github/workflows/cd.yml
.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml

To fix https://github.com/MetaphorData/connectors/security/code-scanning/43 & other related security warnings.

Limit workflow token permissions

---

poetry.lock
pyproject.toml

To fix
- https://github.com/MetaphorData/connectors/security/dependabot/74
- https://github.com/MetaphorData/connectors/security/dependabot/72
- https://github.com/MetaphorData/connectors/security/dependabot/73
As titled.
Verify snowflake connector against production.

Update snowflake-connector-python to fix cryptography vulnerabilities

---

metaphor/azure_data_factory/extractor.py
metaphor/bigquery/extractor.py
metaphor/power_bi/extractor.py
metaphor/power_bi/models.py
metaphor/power_bi/power_bi_client.py
metaphor/synapse/extractor.py
poetry.lock
pyproject.toml
tests/power_bi/expected.json
tests/power_bi/test_extractor.py

Some power query expression needs parameters to derive the physical dataset
- add query to fetch PowerBI dataset parameters
- The compiled model has changed TypeEnum to LogType
unit test
Tested against metaphor and customer environment

Extract PBI dataset parameters [sc-25094]

---

.pre-commit-config.yaml
metaphor/alation/extractor.py
metaphor/alation/schema.py
metaphor/bigquery/extractor.py
metaphor/common/filter.py
metaphor/custom/data_quality/extractor.py
metaphor/glue/extractor.py
metaphor/looker/lookml_parser.py
metaphor/mssql/extractor.py
metaphor/postgresql/extractor.py
metaphor/power_bi/extractor.py
metaphor/power_bi/power_bi_utils.py
metaphor/tableau/extractor.py
metaphor/thought_spot/extractor.py
metaphor/thought_spot/models.py
metaphor/trino/extractor.py
metaphor/unity_catalog/extractor.py
poetry.lock
pyproject.toml
tests/snowflake/test_extractor.py

There are some differences between the dev tools versions and the version used in pre-commit, causing confusions when throwing an error in commit.
And also, the new black style for nested `if-else` does look better than before.
- bring dev tools versions up to date
local precommit

bring dev dependencies up to date

---

metaphor/metabase/extractor.py
pyproject.toml

Make it easier to debug than looking at the raw log.
As titled.

Log Metabase API responses to files

---

metaphor/metabase/extractor.py
poetry.lock
pyproject.toml

Add more info about chart query for SQL parsing
- add default database schema in metabase chart query
run crawler locally against metaphor instance

add default database schema in metabase chart query

---

metaphor/metabase/extractor.py
poetry.lock
pyproject.toml

Previous PR #804 missed some info
- add platform and account info in Chart query
tested against metaphor instance

add platform and account info in Chart query

---

metaphor/looker/lookml_parser.py
pyproject.toml

Currently there's no visibility into LookML parsing, which makes it difficult to debug.
As titled.
Verified against a production instance:

Log parsed LookML to simplify debugging

---

metaphor/dbt/cloud/client.py
metaphor/dbt/cloud/extractor.py
pyproject.toml
tests/dbt/cloud/test_client.py

In the infinite loop I forgot to update payload's offset field, so it's always getting the same thing if no successful run is found. If no successful run was found for a job, then we simply skip it.
Fix the abovementioned bug.
- Tested locally.

[sc-25569] dbt cloud client infinite loop should update offset in payload

---

metaphor/azure_data_factory/extractor.py
pyproject.toml

It's using the incorrect enum.
As titled.
Verified the output `run.metadata` against a production instance.

Use the correct enum for Azure Data Factory connector

---

metaphor/bigquery/config.py
metaphor/redshift/config.py
metaphor/snowflake/config.py
metaphor/synapse/config.py
metaphor/tableau/config.py
metaphor/unity_catalog/config.py
pyproject.toml

This fixes #827 .
Use `default_factory` for dataclass fields.
Tested with Python 3.11.6.

[sc-25918] Support Python 3.11

---

metaphor/snowflake/lineage/extractor.py
pyproject.toml

Some [extras](https://python-poetry.org/docs/pyproject/#extras) were not defined correctly.
- `power_bi` & `snowflake` extras no longer need `sql-metadata` 
- `thought_spot` extra had a typo and needs `sqllineage` 
Manually tested by installing the extra and running the connector.

Fix extra dependencies

---

metaphor/thought_spot/utils.py
pyproject.toml
tests/thought_spot/expected.json

Using the wrong hierarchy IDs in #837 #836 
- Add prefix path segment "THOUGHT_SPOT"
Update unit tests

Fix ThoughtSpot virtual hierarchy id

---

metaphor/metabase/extractor.py
metaphor/power_bi/extractor.py
pyproject.toml
tests/metabase/expected.json
tests/power_bi/expected.json

To deprecate platform-specific hierarchy names, we need to start to fill `hierarchyInfo.name`
- as title
update tests

Start to fill hierarchy name

---

metaphor/looker/lookml_parser.py
poetry.lock
pyproject.toml
tests/looker/test_lookml_parser.py

sql-metadata parser may stuck at certain SQL queries.
- don't do SQL parsing at crawler, but send the raw query in MCE for server-side processing.
Unit tests
tested against Looker instance, and verified the MCE

looker crawler stuck in LookML parsing [sc-25902]

---

metaphor/unity_catalog/README.md
metaphor/unity_catalog/config.py
metaphor/unity_catalog/extractor.py
metaphor/unity_catalog/utils.py
pyproject.toml

Currently, we run SQL on a SQL warehouse for metadata. This PR is to support running SQL on a compute cluster.
- Add an optional configuration to set the cluster path for a cluster
Verified against Metaphor Databricks env.

Support Databricks cluster based extractors

---

metaphor/snowflake/extractor.py
poetry.lock
pyproject.toml
tests/snowflake/test_extractor.py

We can comment on a Snowflake database or schema, and we should extract these comments to hierarchies.
- Extract database and schema level comment from `information_schema`
Add unit tests
Verified the description shows up on the hierarchy page.

Extract Snowflake database/schema level comment

---

metaphor/common/runner.py
pyproject.toml

Connectors are not outputting the complete log to files.
Refactor `run_connector` so that the logs are written at the very end. Also simplify the logic by creating a `FileConfig` that writes to a local temp directory if not specified.
Verified that the output stays identical (other than the additional log entries) before & after the change.

Fix missing logs in output

---

metaphor/bigquery/README.md

Drop duplicated permissions from doc

---

metaphor/dbt/cloud/config.py
metaphor/dbt/cloud/extractor.py
pyproject.toml
tests/dbt/cloud/config.yml
tests/dbt/cloud/test_config.py

https://github.com/MetaphorData/connectors/pull/872 added `meta_key_tags` config to dbt core but forgot to add it to dbt cloud as well.
As titled.
Verified end-to-end against a product instance.

Extend meta_key_tags support to dbt cloud

---

metaphor/bigquery/extractor.py
metaphor/common/models.py
metaphor/common/utils.py
metaphor/custom/data_quality/extractor.py
metaphor/glue/extractor.py
metaphor/hive/extractor.py
metaphor/postgresql/extractor.py
metaphor/s3/extractor.py
metaphor/snowflake/extractor.py
metaphor/unity_catalog/extractor.py
metaphor/unity_catalog/utils.py
pyproject.toml
tests/bigquery/expected.json
tests/glue/expected.json
tests/s3/expected.json
tests/snowflake/test_extractor.py

Since we deprecate `statistics.lastUpdated`, we need to populate `sourceInfo.lastUpdated`
- Update util `to_dataset_statistics`
- Refactor time util function
Unit tests passed

Snowflake crawler to populate sourceInfo

---

metaphor/thought_spot/models.py
pyproject.toml

It's possible that TMLs we fetched do not have fields that are required in the class. To address that, we add `default_factory` to the field in question.
This was discovered in our staging environment.
Add default factory for `TMLObject.answer.table.ordered_column_ids`

[sc-27090] Add default factory for `TMLObject.answer.table.ordered_column_ids`

---

metaphor/metabase/README.md

update metabase readme

---

metaphor/dbt/generated/dbt_manifest_v11.py
metaphor/dbt/generated/dbt_manifest_v12.py
metaphor/dbt/generated/dbt_run_results_v5.py
pyproject.toml

There's a new field `cumulative_type_params`, without it in our generated manifest models our crawlers will break.
Regenerate the dbt manifest models by running `generate_all_models.sh`.
Tested with QA configs locally.

[sc-27305] Regenerate dbt manifest models

---

metaphor/looker/README.md
metaphor/looker/config.py
metaphor/looker/extractor.py
pyproject.toml
tests/looker/expected_alternative.json
tests/looker/test_extractor.py

User may have different base URL to view content on Looker than the base URL for fetching metadata
- Add optional config field.
Unit test

User should specify alternative looker source url

---

metaphor/looker/extractor.py
pyproject.toml
tests/looker/expected.json
tests/looker/expected_alternative.json
tests/looker/test_extractor.py

Only next-gen dashboards have the correct `mailUrl`.
- Use legacy prefix if the dashboard is not support "next"
Unit tests and verified the MCE

Some looker dashboard url is incorrect

---

tests/common/process_query/test_process_query.py

To ensure important PII is all scrubbed from `WHERE` clauses, two test cases are added.
Added tests to ensure all PII is redacted in `WHERE ... IN ...` and `WHERE ... OR ...` expressions.
Added tests.

chore: Add tests to ensure PII in `WHERE ... IN ...` is redacted

---

metaphor/dbt/util.py
pyproject.toml
tests/dbt/data/databricks/manifest.json
tests/dbt/test_util.py

dbt supports databricks, we should support that as well.
`adapter_type = "databricks"` means `platform = DataPlatform.UNITY_CATALOG`.
Added simple test.

[sc-27539] Map DATABRICKS adapter_type to `DataPlatform.UNITY_CATALOG`

---

metaphor/unity_catalog/profile/README.md

Fix broken links in docs

---

metaphor/unity_catalog/profile/extractor.py
pyproject.toml
tests/unity_catalog/profile/test_extractor.py

To make the UC profile crawler more robust
- Catch the exception
Unit tests.

Handle permission issues gracefully in UC crawler

---

metaphor/unity_catalog/extractor.py
pyproject.toml
tests/unity_catalog/expected.json
tests/unity_catalog/snapshots/test_extractor/test_init_dataset/table.json
tests/unity_catalog/test_extractor.py

To show the ownership information from Unity Catalog.
As titled. Will create a follow-up PR to add the same for catalogs & schemas, which require some refactoring.

Extract system contacts for Unity tables

---

metaphor/dbt/generated/dbt_manifest_v12.py
pyproject.toml

DBT changed their schema again, so we need to regenerate the classes again.
Regenerate v12 manifest classes based on latest DBT schema.
Run crawler locally. No more pydantic validation errors.

[sc-27685] Generate dbt v12 manifest classes

---

metaphor/common/fieldpath.py
metaphor/database/config.py
metaphor/database/extractor.py
metaphor/mysql/config.py
metaphor/mysql/extractor.py
metaphor/oracle/README.md
metaphor/oracle/__init__.py
metaphor/oracle/config.py
metaphor/oracle/extractor.py
poetry.lock
pyproject.toml
tests/database/config.yml
tests/database/expected.json
tests/database/test_config.py
tests/database/test_extractor.py
tests/mysql/expected.json
tests/oracle/config.yml
tests/oracle/expected.json
tests/oracle/expected_query_logs.json
tests/oracle/test_config.py
tests/oracle/test_extractor.py

To support Oracle database.
- Refactor the MySQL extractor into a generic extractor that uses SQLAlchemy to get the metadata.
- Basic table/view/materialized view information
- table/column comment
- DDL
- query history but Oracle only keeps the history for a very short time
End-to-end test on dev. (Only the ingestion part)
Unit tests added

Oracle crawler

---

metaphor/hive/extractor.py
pyproject.toml
tests/hive/expected.json

Without structure, metaphor will recognize the dataset as an incomplete asset.
Added `structure` field for Hive datasets.
Updated unit test.

[sc-27386] Hive datasets need to have structure

---

metaphor/common/sql/dialect.py
metaphor/common/sql/table_level_lineage/table.py
metaphor/common/sql/table_level_lineage/table_level_lineage.py
metaphor/informatica/extractor.py
metaphor/oracle/extractor.py
pyproject.toml
tests/common/sql/table_level_lineage/test_select_dialect_specific.py
tests/oracle/expected_query_logs.json
tests/oracle/test_extractor.py

`sources` field in `QueryLog` is mandatory, otherwise it would now show in Metaphor.
- Use `extract_table_level_lineage` to get sources.
- Make query log extractor more scalable
Update unit tests

Parse sources from oracle query logs

---

metaphor/redshift/utils.py
pyproject.toml
tests/redshift/test_utils.py

Skip Redshift serverless system database
As title
Run the crawler without any filter against Redshift serverless endpoint

Skip redshift system database

---

metaphor/postgresql/profile/README.md

Add one line of SQL in the Postgres Profile connector readme.

Improve documentation

---

metaphor/common/sql/process_query/process_query.py
pyproject.toml

Logging unprocessable queries to stdout is too much, just log to debug and have them in the log file.
Log the unprocessable queries to debug.
N/A.

[sc-28370] Log to debug for unprocessable queries

---

metaphor/postgresql/extractor.py
pyproject.toml
tests/postgresql/test_extractor.py

A missing case in #970 
- Skip cloud watch log entry does not match the format.
Successfully finished while running against `postgres.data`

Fix postgres query log

---

metaphor/postgresql/extractor.py
metaphor/postgresql/log_parser.py
pyproject.toml

It's hard to debug if the log parsing fails.
- Add log when failure
n/a

Add more logging for postgres crawler query parsing

---

metaphor/redshift/extractor.py
pyproject.toml

Query logs that reference nonexistent datasets should not be ignored, otherwise lineage that has more than 1 generated tables between the real upstream and downstream datasets will not work.
Keep query logs that reference only nonexistent datasets in our collected results.
N/A.

[sc-29047] Do not drop query logs referencing nonexisting tables

---

README.md
metaphor/s3/README.md

Update s3 README doc

---

metaphor/mongodb/README.md
metaphor/mongodb/config.py
metaphor/mongodb/extractor.py
pyproject.toml
tests/mongodb/test_extractor.py

1. The MongoDB crawler readme does not contain required permissions.
2. System databases should always be ignored.
- Added required permissions in Readme
- Always ignore system databases.
N/A.

[sc-29398] Improve MongoDB crawler documentation and config

---

metaphor/common/sql/table_level_lineage/table_level_lineage.py
metaphor/postgresql/extractor.py
pyproject.toml

So we can process lineage on the server side
- Filter out invalid sources and targets
- Improve log
Verified against dev postgres instance

Should extract query log that have incomplete sources/targets

---

metaphor/great_expectations/extractor.py
pyproject.toml
tests/great_expectations/expected_basic_sql.json
tests/great_expectations/expected_snowflake.json

As titled.
- Updated `DataQualityMonitor.dataset` from a name to an entity id.
- Updated test expected results.
- Tested end-to-end on stage:

[sc-29678] `DataQualityMonitor.dataset` is an entity ID, not a name

---

metaphor/openapi/config.py
metaphor/openapi/extractor.py
pyproject.toml
tests/openapi/config.yml
tests/openapi/test_config.py
tests/openapi/test_extractor.py

As title
- Refactor the extraction
- Support multiple OAS in config
Unit test, and verified locally

Support multiple OpenAPI json in one crawler

---

metaphor/looker/README.md
metaphor/looker/config.py
metaphor/looker/extractor.py
metaphor/looker/lookml_parser.py
pyproject.toml
tests/looker/test_lookml_parser.py

Some Looker model may have invalid connection and raise value error
- add config to allow bypassing certain model files from parser
Tested on customer environment

Looker crawler is failed to load model [sc-30007]

---

metaphor/dbt/cloud/client.py
metaphor/dbt/cloud/extractor.py
metaphor/dbt/cloud/parser/common.py
pyproject.toml
tests/dbt/cloud/data/list_project.json

A few issues were observed when running https://github.com/MetaphorData/connectors/pull/1052 against more complex dbt projects.
- Reduce the discovery API page size to avoid hitting HTTP 502 due to large responses.
- Make `connection_id` & `connection` fields optional, despite the latter being [documented as required](https://docs.getdbt.com/dbt-cloud/api-v3#/operations/List%20Projects).
- Ignore exceptions (e.g. missing `connection` field or unexpected connection type) thrown when parsing projects/environments to avoid crashing the entire crawler.
Verified against a few complex production environments.

Fix various dbt cloud connector issues

---

metaphor/dbt/cloud/parser/common.py
metaphor/dbt/cloud/parser/model_parser.py
metaphor/dbt/cloud/parser/source_parser.py
metaphor/dbt/util.py
pyproject.toml
tests/dbt/cloud/data/expected.json
tests/dbt/cloud/data/get_models.json
tests/dbt/cloud/data/get_sources.json
tests/dbt/cloud/test_extractor.py

In some cases the model-referenced dataset is not created by source parser, causing the model tests not able to be attached to the dataset. We should create an empty dataset to attach data quality to. 
- create an empty dataset to attach data quality from model tests if the dataset doesn't exist after parsing all the sources.
- some code refactoring 
tested against metaphor dbt instance.

dbt test results not updated [sc-30043]

---

metaphor/dbt/cloud/extractor.py
metaphor/dbt/cloud/parser/model_parser.py
pyproject.toml

To simplify code handling the dbt meta parsing
- minor refactoring of the dbt model parser code
tested against metaphor instance

simplify dbt parser code

---

Dockerfile

[poetry 2.x](https://pypi.org/project/poetry) broke the current CI/CD: https://github.com/MetaphorData/connectors/actions/runs/12639124150/job/35217508410
```
ERROR: failed to solve: process "/bin/sh -c poetry export     --without dev     --all-extras     --format=requirements.txt     --output=requirements.txt" did not complete successfully: exit code: 1
Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c poetry export     --without dev     --all-extras     --format=requirements.txt     --output=requirements.txt" did not complete successfully: exit code: 1
```
As titled.
Let CI do its job.

Fix CI by using poetry 1.x

---

metaphor/quick_sight/client.py
metaphor/quick_sight/extractor.py
pyproject.toml

For better track the progress of the crawler
- add a bit more logging to quicksight crawler
tested against metaphor instance.

add more logging to quicksight

---

metaphor/thought_spot/models.py
pyproject.toml

ThoughtSpot seemed to have changed its API, leading to model validation errors like:
```
2025-01-13 06:01:33:ERROR:metaphor:3 validation errors for list[Connection]
0.details.tags.0.isDeleted
Field required [type=missing, input_value={'id': '528e246a-ecf3-4ed... 'To Be Decommissioned'}, input_type=dict]
For further information visit https://errors.pydantic.dev/2.6/v/missing
0.details.tags.0.isHidden
Field required [type=missing, input_value={'id': '528e246a-ecf3-4ed... 'To Be Decommissioned'}, input_type=dict]
For further information visit https://errors.pydantic.dev/2.6/v/missing
0.details.tags.0.isDeprecated
Field required [type=missing, input_value={'id': '528e246a-ecf3-4ed... 'To Be Decommissioned'}, input_type=dict]
For further information visit …
```

Fix ThoughtSpot Tags model validation

---

metaphor/quick_sight/extractor.py
pyproject.toml

To avoid flooding the log
- minor update the logging of quicksight
n/a

minor update to logging message
