MetaphorData/connectors

metaphor/dbt/extractor.py, metaphor/looker/extractor.py, metaphor/looker/lookml_parser.py, pyproject.toml, tests/dbt/data/expected_results.json, tests/looker/test_extractor.py, tests/looker/test_lookml_parser.py
Since we added "account" to Snowflake DatasetID, we need to also update the lineage references to add account info
- Update lineage reference  in DBT and LOOKER to add "account"  to DatasetID
=> Fix Looker crawler lineage dataset ID [sc-3553]

metaphor/looker/lookml_parser.py, pyproject.toml, tests/looker/test_lookml_parser.py
Previous fix https://github.com/MetaphorData/connectors/pull/30 didn't actually filled the account in DatasetId, fixed it here
- Add account in DatasetId 
- Test run crawler locally, verify the generated dataset ID matches snowflake crawler
=> Fix datasetID account

metaphor/postgresql/extractor.py, pyproject.toml
`InsufficientPrivilegeError: Operation not allowed on schema "pg_internal"` .
pg_internal can't be accessed by user account, and we shouldn't crawl its metadata anyway. 
- Exclude postgres internal schemas from crawler.
=> Redshift crawler privilege error [sc-3633]

metaphor/dbt/dbt_model.py, metaphor/dbt/extractor.py, pyproject.toml, tests/dbt/data/expected_results.json, tests/dbt/data/manifest.json
dbt crawler is failing to parse the output of the newly added shopify dbt project: https://github.com/MetaphorData/dbt/pull/19
```
2021-09-28 06:07:22,736 ERROR - Read manifest json error: 'column_name'
File "/usr/local/lib/python3.7/site-packages/***/dbt/extractor.py", line 66, in extract
self._manifest = DbtManifest.from_json_file(config.manifest)
File "/usr/local/lib/python3.7/site-packages/***/dbt/dbt_model.py", line 71, in from_json_file
return from_json(cls, fin.read())  # type: ignore
File "/usr/local/lib/python3.7/site-packages/serde/json.py", line 29, in from_json
return from_dict(c, de.deserialize(s, **opts), reuse_instances=False)
File "/usr/local/lib/python3.7/site-packages/serde/de.py", line 311, in from_dict
return from_obj(cls, o, …
```
=> Fix DBT manifest test metadata parsing error

metaphor/dbt/extractor.py, pyproject.toml, tests/dbt/data/catalog.json, tests/dbt/data/expected_results.json
dbt's catalog may sometimes contain `null` as column type. This causes an issue when ingesting the MCEs which expects `nativeType` to be an non-empty string.
As titled.
=> Use default placeholder value when column native type is not set

metaphor/dbt/extractor.py, pyproject.toml, tests/dbt/data/expected_results.json, tests/dbt/data/manifest.json
dbt crawler will fail to parse the manifest & catalog when the `test_metadat` is `None` with the following error.
```
2021-09-23 23:42:25,154 INFO - Starting extractor DbtExtractor
2021-09-23 23:42:25,154 INFO - Fetching metadata from DBT repo
File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/usr/local/lib/python3.7/site-packages/***/dbt/__main__.py", line 6, in <module>
cli_main("DBT metadata extractor", DbtRunConfig, DbtExtractor)
File "/usr/local/lib/python3.7/site-packages/***/common/cli.py", line 27, in cli_main
extractor.run(config=config_cls.from_yaml_file(args.config))
File …
```
=> Fix incorrect expection on dbt test_metadata

metaphor/bigquery/extractor.py, metaphor/common/api_sink.py, metaphor/common/event_util.py, metaphor/common/extractor.py, metaphor/common/file_sink.py, metaphor/common/sink.py, metaphor/dbt/extractor.py, metaphor/google_directory/extractor.py, metaphor/looker/extractor.py, metaphor/looker/lookml_parser.py, metaphor/postgresql/extractor.py, metaphor/slack_directory/extractor.py, metaphor/snowflake/extractor.py, metaphor/snowflake/usage/extractor.py, pyproject.toml
To avoid flooding the log with error and causing confusion https://app.shortcut.com/metaphor-data/story/3635/log-non-fetal-issues-in-snowflake-usage-crawler-as-warning-instead-of-error
- Adopt best practice to getLogger with module name, instead of getting the root logger
- Disable the error logging from sql_metadata, replace with own logging
=> Log non fetal issues in snowflake usage crawler [sc-3635]

metaphor/snowflake/extractor.py, pyproject.toml
Snowflake connector currently will scan all tables/views from all databases regardless what's specified in the config.
As titled. We can introduce a list of allowed databases in the config file as a breaking change in 0.6:  https://github.com/MetaphorData/connectors/issues/13
Note: While the behavior is backward incompatible, it's considered as a bug fix. 
Verified by running it locally:
```
$ python -m metaphor.snowflake ~/Desktop/local/snowflake.yml
2021-10-04 21:18:57,948 INFO - query: [USE ACME]
...
2021-10-04 21:19:31,522 INFO - Fetched 43 entities
```
=> Limit Snowflake connector to extract metadata only from the database specified in the config

pyproject.toml
Forgot to bump version 😞  in https://github.com/MetaphorData/connectors/pull/47
Bump version to 0.5.2
=> bump version for dbt crawler

metaphor/bigquery/extractor.py, metaphor/postgresql/__main__.py, metaphor/postgresql/extractor.py, metaphor/slack_directory/extractor.py, tests/postgresql/test_config.py
Better naming, https://github.com/MetaphorData/connectors/issues/13
- Rename `PostgresqlExtractor` & `PostgresqlRunConfig` to `PostgreSQLExtractor` & `PostgreSQLRunConfig`
=> Rename postgres crawler [sc-3946]

metaphor/looker/extractor.py, metaphor/looker/lookml_parser.py, tests/looker/test_lookml_parser.py
Dashboard upstream should only point to looker explore, not directly to dataset anymore, this can cause confusion to user.
Part of https://github.com/MetaphorData/connectors/issues/13
- remove the `upstreamDatasets` in DashboardLineage
- Fix `upstreamVirtualView` ids with full qualified name
Generated MCE, previous:
```
"upstream": {
"sourceDatasets": [
"DATASET~181EB317DD87BD5543C8A97135ACB5DF",
"DATASET~A34DC6FC69D7DFD3DF8285D8DF783F41",
"DATASET~A2A14D0D4832E92DEEAB2F956F663CA4",
"DATASET~061D5F960D9BA1F5924A79D02F97FC74",
"DATASET~C16EEFC9FD8BC362B0845968CB507915",
"DATASET~5BEED87BC99D8304FA8001DFC1886AC7",
"DATASET~02B06B1D7327E2EACAE839C29A4F6199"
],
"sourceVirtualViews": [
"VIRTUAL_VIEW~0E01187CB192E747D521A3FC30F68DDD",
"VIRTUAL_VIEW~777C53F683F220F1835C683CEF5670EC", …
```
=> Drop dataset virtual view dual writing in [sc-3948]

README.md
Users encounter the following error on zsh:
```
% pip install metaphor-connectors[all]
zsh: no matches found: metaphor-connectors[all]
```
As square brackets have special meaning in zsh, we need to put the package name in quotes to make it work on both bash & zsh.
```
% pip install "metaphor-connectors[all]"
...
Successfully installed metaphor-connectors-0.6.1
```
=> Add quotes to pip package name

metaphor/snowflake/extractor.py, pyproject.toml
To show unique and PK constraint on UI
- fetch unique constraints and PK columns and attach to corresponding table
local runCrawler
```
[
{
"dataset": {
"entityType": "DATASET",
"logicalId": {
"account": "ooa97392",
"name": "demo_db.metaphor.cycle_hire",
"platform": "SNOWFLAKE"
},
"schema": {
"aspectType": "DATASET_SCHEMA",
"fields": [
{
"fieldPath": "RENTAL_ID",
"nativeType": "NUMBER",
"nullable": false,
"precision": 38.0
},
...
],
"schemaType": "SQL",
"sqlSchema": {
"materialization": "TABLE",
"primaryKey": [
"BIKE_ID",
"RENTAL_ID"
],
},
"entityId": "",
"latest": false
},
...
},
{
"dataset": {
"entityType": "DATASET",
"logicalId": {
"account": "ooa97392",
"name": "demo_db.dbt_dev.netflix",
"platform": "SNOWFLAKE"
},
"schema": {
"aspectType": "DATASET_SCHEMA",
"fields": [
{ …
```
=> Crawl unique column constraint for Datasets [sc-4137]

metaphor/common/s3.py
https://github.com/MetaphorData/connectors/pull/89 that causes the connector to crash with the following error when `assume_role_arn` is not specified:
```
[ERROR] AttributeError: 'NoneType' object has no attribute 'client'
File "/var/task/functions/bigquery/handler.py", line 12, in handle
return handle_api(event, context, BigQueryExtractor)
File "/var/task/common/handler.py", line 32, in handle_api
events = actor.run(config=run_config)
File "/tmp/sls-py-req/metaphor/common/extractor.py", line 72, in run
file_sink.sink(events)
File "/tmp/sls-py-req/metaphor/common/sink.py", line 25, in sink
return self._sink(valid_records)
File "/tmp/sls-py-req/metaphor/common/file_sink.py", line 63, in _sink
s3_session=self.s3_session,
File …
```
=> Fix crashing when assume_role_arn is not specified

metaphor/redshift/__main__.py, metaphor/redshift/config.py, metaphor/redshift/extractor.py, pyproject.toml, tests/redshift/test_config.py
https://github.com/MetaphorData/connectors/pull/92 missed adding the required files to make redshift connector a proper python module.
As titled. Also fixed the naming of the extractor and config classes.
```
$ python -m metaphor.redshift ~/Desktop/local/redshift.yml
Log file: /var/folders/mj/nctx1fsn2cg7rdssx505z4pr0000gn/T/tmp9ztonis2.log
**** <class 'metaphor.redshift.config.RedshiftRunConfig'>, {'host': 'localhost', 'database': 'metaphor', 'user': 'root', 'password': 'uG9n_UELKPY83PB-PKF7Ey.A', 'output': {'file': {'path': '~/Desktop/local/mce/redshift.json'}}}
Starting extractor RedshiftExtractor
Fetching metadata from DataPlatform.REDSHIFT host localhost
Connecting to DB metaphor
Databases: ['metaphor', 'dev', 'padb_harvest']
Connecting to DB metaphor
DB metaphor has tables …
```
=> Add missing __init__.py & __main__.py for redshift connector

metaphor/common/extractor.py, metaphor/snowflake/profile/extractor.py, metaphor/snowflake/usage/README.md, metaphor/snowflake/usage/config.py, metaphor/snowflake/usage/extractor.py, pyproject.toml, tests/snowflake/usage/data/parse_query_log_result.json, tests/snowflake/usage/test_parser.py
Usage crawler is taking too long to parse large number of SQL queries
- Use snowflake access_history to get the query table and columns, instead of parsing SQL
- NOTE: since the query joins access_history table with query_history table, each query can be slow (few seconds for our case). Running small batch with many concurrency actually makes it slower, because each query will do the joining computation again. Prefer large batch size with fewer batches, as it's much faster.
- NOTE 2: The table joining stats is not available, as there is no joining and columns info in the access history
local test run with 30 days lookback on DEMO_DB and ACME, took 25-30s, mostly DB query time
=> Improve Snowflake usage crawler [sc-4639]

metaphor/snowflake/README.md, metaphor/snowflake/auth.py, pyproject.toml
Tag each query from connector with a tag, so its easier to do analysis.
- Add optional config `query_tag` and add it in Snowflake session parameter
Run snowflake connector locally, the query history show the recent queries all tagged with "MetaphorData"
=> snowflake crawler should add query tag in [sc-4105]

metaphor/dbt/extractor.py, pyproject.toml, tests/dbt/data/trial_v3/catalog.json
The connect crashes when it encounters a "seed node" in catalog.json:
```
File "/Users/marslan/.pyenv/versions/3.8.12/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/Users/marslan/.pyenv/versions/3.8.12/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/Users/marslan/Metaphor/connectors/metaphor/dbt/__main__.py", line 6, in <module>
cli_main("DBT metadata extractor", DbtRunConfig, DbtExtractor)
File "/Users/marslan/Metaphor/connectors/metaphor/common/cli.py", line 27, in cli_main
extractor.run(config=config_cls.from_yaml_file(args.config))
File "/Users/marslan/Metaphor/connectors/metaphor/common/extractor.py", line 65, in run
events: List[MetadataChangeEvent] = …
```
=> Fix catalog parsing by ignoring seeds

metaphor/snowflake/profile/extractor.py, pyproject.toml, tests/snowflake/profile/test_extractor.py
The snowflake profiler is running very slow, taking hours if not forever to run for customers.
- Drop the stddev calculation to speed up the profiling
Run locally against ACME and DEMO_DB, took 257s the first run, and 38s the second run. Seems Snowflake is caching the query result
=> Drop variant calculation in snowflake profiler [sc-5938]

metaphor/snowflake/profile/README.md, metaphor/snowflake/profile/config.py, metaphor/snowflake/profile/extractor.py, metaphor/snowflake/utils.py, pyproject.toml, tests/snowflake/profile/test_extractor.py
The snowflake profiler is currently doing full table scan, which can be very slow for large tables. We should provide the option to do random sampling on the data. 
- Add the capability and config to do random sampling based on percentage.
Tested on dribble data with 1% sampling, finished `ANALYTICS` DB in 30min.
Update: finished dribble `RAW` and `ANALYTICS` in just under 1hr
=> Speed up snowflake profiler using approximation [sc-5603]

metaphor/bigquery/config.py, metaphor/bigquery/extractor.py, metaphor/bigquery/usage/config.py
BigQueryRunConfig should be a module itself for consistency.
Move BigQueryRunConfig to `config.py` from `extractor.py`
Local tests passed.
=> Move BigQueryRunConfig to a separate file [sc-6062]

metaphor/tableau/extractor.py, pyproject.toml, tests/tableau/test_extractor.py
Using view name to construct chart URL is not safe, as it may contain empty space or unescaped char. 
- Use API provided content_url to construct the chart URL
successfully ingested tableau MCE on dev-yi without error
=> MCE validation error url must be an URL address [sc-6065]

.pre-commit-config.yaml, metaphor/bigquery/__main__.py, metaphor/bigquery/usage/__main__.py, metaphor/common/cli.py, metaphor/dbt/__main__.py, metaphor/google_directory/__main__.py, metaphor/looker/__main__.py, metaphor/metabase/__main__.py, metaphor/postgresql/__main__.py, metaphor/redshift/__main__.py, metaphor/redshift/usage/__main__.py, metaphor/slack_directory/__main__.py, metaphor/snowflake/__main__.py, metaphor/snowflake/profile/__main__.py, metaphor/snowflake/usage/__main__.py, metaphor/tableau/__main__.py
The extract class already has a method to get the corresponding config class so there's no need to specify it explicitly.
As titled. Also fixed missing dependency for mypy pre-commit hook (See https://github.com/pre-commit/mirrors-mypy/issues/50 for more details).
Selectively ran a few connectors locally to verify.
=> Derive config class name directly in CLI

.pre-commit-config.yaml, metaphor/common/README.md, metaphor/common/file_sink.py, metaphor/common/s3.py, pyproject.toml, tests/common/config.json, tests/common/config.yml, tests/common/test_config.py, tests/common/test_file_sink.py
Current the file sink config specifies the MCE json file path, but the log file and metadata file path are derived from the json path. This is unclear to the user and unsafe.
Part of https://github.com/MetaphorData/connectors/issues/95
- Change the file sink config to specify the directory instead, and the MCE file, as well as log and metadata, are all written to the same directory.
- Fix issues with pre-commit hook
file written to local directory and S3 dev-yi
=> refactor crawlers output config to only specify [sc-6338]

metaphor/tableau/README.md, metaphor/tableau/config.py, metaphor/tableau/extractor.py, pyproject.toml, tests/tableau/config.yml, tests/tableau/test_config.py
Generating preview images can take a long time and result in an excessively large output for a large number of views.
Add a config option to disable the feature.
Manually tested against Tableau cloud with preview enabled & disabled.
=> Add config to disable preview images for Tableau connector

metaphor/metabase/extractor.py, pyproject.toml
Some customers are using Metabase with redshift data source.
- Add redshift in support data platform in metabase crawler
Local run successfully, verified the dataset id matches Redshift crawler
=> Add redshift support for Metabase [sc-6232]

metaphor/bigquery/lineage/extractor.py, metaphor/tableau/README.md, metaphor/tableau/config.py, metaphor/tableau/extractor.py, pyproject.toml, tests/tableau/config.yml, tests/tableau/config_no_optional.yml, tests/tableau/test_config.py
The Tableau API is returning the BigQuery project name as database name. This is not consistent with BQ crawler which uses project ID.
- Add optional config to allow the user to provide the big query project ID, since it's difficult, hacky and unreliable to parse the info from the Tableau data sources API response.
- Add more logs in zip file to aid the debugging of missing lineage
tested on local run, and verified the dataset ID matches the one from BQ crawler
=> Tableau lineage BigQuery use project Id [sc-6500]

metaphor/common/usage_util.py, pyproject.toml, tests/bigquery/usage/data/result.json, tests/bigquery/usage/test_extractor.py, tests/common/test_usage_util.py
The calculated percentile for example like [1, 1, 1, 1, 5] is not reasonable, as all "1"s are 80%
- Use rank mode instead of weak mode in percentile rank calculation. Details see https://www.notion.so/metaphordata/Calculation-of-Percentile-de54e81b70cd46f5a093cb373a72a4cc
unit tests for all covered cases
=> Usage percentile doesn t work well when the [sc-6372]

metaphor/dbt/extractor.py, pyproject.toml
As described in https://docs.getdbt.com/reference/resource-properties/identifier, `identifier` is the real table name, whereas `name` is just for dbt's internal references. The two are often the same and that's why the connector has worked in many cases in the past.
As titled.
Manually tested against a real-world dbt manifest.
=> Use "identity" instead of "name" when building dataset ID

metaphor/tableau/extractor.py, pyproject.toml, tests/tableau/test_extractor.py
In many cases the Tableau GQL upstreamTables `fullName` field contains the correct dataset fullname, especially for BQ, it's using the correct project id instead of the project name. We can try this field first, with fallback to table `name` and `schema` field
- Update the Tableau upstream table name parsing logic to use `fullName` first, before falling back to `name` and `schema`
- Dedupe the upstream datasets
- unit tests
- tested with production data GQL response
=> Use upstream table fullName

metaphor/bigquery/extractor.py, metaphor/bigquery/lineage/README.md, metaphor/bigquery/lineage/config.py, metaphor/bigquery/lineage/extractor.py, metaphor/bigquery/utils.py, pyproject.toml, tests/bigquery/lineage/config.yml, tests/bigquery/lineage/data/view_result.json, tests/bigquery/lineage/test_config.py, tests/bigquery/lineage/test_extractor.py
The BigQuery view should have upstream lineage pointing to the queried tables, but the current lineage crawler doesn't handle that.
- Fetch BQ view definition and parse the SQL to get upstream tables. 
- Make two toggles in BQ lineage config for enabling view lineage and log lineage
unit tests
tested locally against metaphor BQ instance, view lineage is correct
=> Missing BQ lineage for views [sc-6663]

metaphor/dbt/catalog_parser_v1.py, metaphor/dbt/extractor.py, metaphor/dbt/manifest_parser_v3.py, metaphor/dbt/manifest_parser_v4.py, metaphor/dbt/util.py, pyproject.toml, tests/dbt/data/trial_v4/catalog.json, tests/dbt/data/trial_v4/manifest.json, tests/dbt/data/trial_v4/results.json, tests/dbt/test_extractor.py
[dbt 1.0](https://docs.getdbt.com/docs/guides/migration-guide/upgrading-to-1-0-0) introduced some breaking changes, the current parser won't work
- forked the manifest parser to v3 and v4, to support incompatible schema
- refactor the catalog parser to a separate file too
The existing parser tests all passed. Added the v4 parser tests using json generated with dbt 1.0
=> Support dbt 1 0 [sc-5881]

metaphor/postgresql/extractor.py, pyproject.toml
Cannot run Redshift crawler with minimum privilege.
- `pg_total_relation_size` needs extra permission when parameter is table name. Use object ID of relation to solving this problem.
- Run Redshift crawler with an ordinary user successfully
- Run PostgresSQL crawler successfully with the correct result.
=> Redshift crawler still needs permission to actual schema [sc-6686]

metaphor/postgresql/extractor.py, pyproject.toml, tests/postgresql/test_extractor.py
When parsing precision, max_length from `fotmat_type` could cause `IndexError` for some reason. According to the document, `character varying` and `character` should be at least 1.
- Add try-catch to safely parse `format_type`.
n/a
=> Redshift crawler index of out bound issue [sc-6687]

.flake8, .github/workflows/cicd.yml, .pre-commit-config.yaml, metaphor/common/entity_id.py, metaphor/dbt/manifest_parser_v3.py, metaphor/dbt/manifest_parser_v4.py, poetry.lock, pyproject.toml
[flakehell](https://github.com/life4/flakehell) has been archived, and no more updates since a year ago. And it also doesn't work well with the latest flake8, preventing us from updating flake8 version. The included tests pycodestyle  and pyflakes are supported by flake8 out of the box.
- use plain flake8 to replace flakehell, also update its version
- fix flake8 detected issues, e.g. code too complex for dbt parse, restructure the codes
- update pre-commit hook and CI
pre-commit hook is working fine and much faster than before, since the flake8 hook checks the updated files, not the entire directory.
=> remove flakehell

metaphor/bigquery/profile/extractor.py, pyproject.toml, tests/bigquery/profile/test_extractor.py
Possibly due to column naming being a reserved keyword of BQ
- escape all column names 
updated unit tests
run locally against metaphor BQ instance
=> Bigquery profiler syntax error [sc-6749]

.pre-commit-config.yaml, metaphor/looker/lookml_parser.py, poetry.lock, pyproject.toml
Bring versions up to date. Latest sql-metadata has improved alias handling.
- update sql-metadata and pre-commit versions
- latest version of sql-metadata seems more strict on table names and skipped names like `${abc.xyz}` instead of stripping the `${}` automatically as the previous version does. Being strict is reasonable from SQL parsing perspective, but for lkml SQL references, we have to strip the brackets ourselves.
- A little optimization by storing the view upstream with the raw view, so we don't need to parse it again during cross-referencing.
Fixed unit tests. 
Run locally against metaphor looker instance.
=> update sql-metadata and pre-commit versions

metaphor/bigquery/profile/extractor.py, pyproject.toml
Currently, connector logs every second when waiting on jobs to complete and did not have enough context about the processing status.
- Log every 10 seconds but wake up every second to check if all jobs are completed
- Log number of jobs left and done.
- Handle Google cloud client API error, log the error and skip the table.
- Prevent the connector would keep running forever by properly handling exceptions in the callback.
Manually raise an exception in `parse_result`, the connector complete as normal.
=> Add more context to BQ profiler when waiting on jobs to complete [sc-6765]

metaphor/common/storage.py, pyproject.toml
the previous implementation of S3 list-objects doesn't support pagination, so if there are more than 1000 items in the bucket sub-directory, some items won't be fetched.
- add pagination support in `list_files`
- tested locally against dev s3 bucket, used small batch size to force pagination, works well.
=> Handle pagination is S3 list objects [sc-6783]

README.md, metaphor/redshift/lineage/extractor.py, pyproject.toml, tests/redshift/lineage/data/result.json, tests/redshift/lineage/data/result_view.json
As title.
- Use entity IDs for source datasets.
- Small refactor.
- Fix tests.
- Run redshift lineage connector successfully, manually checked output.
=> Redshift lineage should use entity IDs for sourceDatasets [sc-6830]

metaphor/postgresql/profile/extractor.py, pyproject.toml, tests/postgresql/profile/test_extractor.py
Redshift profiler gets `ERROR:metaphor.common.extractor:Numeric data overflow (addition)`. Root cause most likely is calculating the average when the sum of column exceeds `bigint` range.
- Cast to float before calculating the average.
- Handle some SQL errors to keep the connecter finished smoothly.
Run connector locally.
=> Redshift profiler overflow [sc-6825]

metaphor/common/storage.py, tests/common/test_storage.py
Local storage threw an error when the directory doesn't exist, also it doesn't expand `~`
- Add directory expansion and existence check. 
Tested locally 
unit test
=> FileNotFoundError for crawlers [sc-6870]

metaphor/bigquery/usage/extractor.py, pyproject.toml, tests/bigquery/usage/data/sample_log.json
Sometimes the BQ logs TableResources contains table names with partition attached, it may also contain temporary tables. Need to do sanitization before we collect the data.
- strip table partition and skip temporary tables in BQ usage crawler
- add logging to show progress
unit tests to cover those cases
tested against production env
=> Do not crawl BQ partitioned tables [sc-6868]

metaphor/snowflake/auth.py, pyproject.toml
For best practice mentioned in https://drive.google.com/file/d/16V4DH5t5YUiv2ABD_i57gGL1QHm4tki9/view, we should set `application='PartnerName_ToolName’`
- add application name in the snowflake connection
tested the snowflake crawler locally against metaphor instance.
=> Add application to snowflake connector [sc-6880]

metaphor/postgresql/profile/extractor.py, pyproject.toml
Error `Runtime.ImportModuleError: Unable to import module 'functions.redshift.profile.handler': No module named 'black'`
- Fix PostgreSQL profiler import
local crawler run
=> fix profiler import

.pre-commit-config.yaml, metaphor/snowflake/usage/extractor.py, poetry.lock, pyproject.toml
After previous PR https://github.com/MetaphorData/connectors/pull/200, there is not need to use pyserde anymore, we can rely only on pydantic to do serde
- refactor pyserde dataclass to pydantic dataclass
- remove pyserde from dependency
Local run snowflake usage crawler successfully
=> remove Pyserde 

metaphor/common/base_config.py, pyproject.toml, tests/common/test_config.py
It is better to use `parse_obj_as`, instead of using dataclass constructor.
- Use `pydantic.parse_obj_as` after yaml loaded.
Run a connector successfully.
=> Use pydantic.parse_obj_as

README.md, metaphor/common/usage_util.py, metaphor/postgresql/usage/README.md, metaphor/postgresql/usage/__main__.py, metaphor/postgresql/usage/config.py, metaphor/postgresql/usage/extractor.py, pyproject.toml
To extract usage metadata from PostgreSQL database.
PostgreSQL did not record queries in the database but it can be configured to log to a file. We did not use the log parsing approach because it is more complicated to specify the log path or the log format.
PostgresSQL has a built-in [statistic collector](https://www.postgresql.org/docs/12/monitoring-stats.html#PG-STAT-ALL-TABLES-VIEW). We can easily extract basic usage metadata from it. 
Local run connector successfully.
=> Add PostgreSQL usage crawler

metaphor/snowflake/auth.py, pyproject.toml
Sometimes the snowflake session param `quoted_identifiers_ignore_case` https://docs.snowflake.com/en/sql-reference/identifiers-syntax.html#controlling-case-using-the-quoted-identifiers-ignore-case-parameter is set to True by server, causing quoted identifier to be converted to UPPERCASE. This causes error when matching the entities.
- explicitly set quoted_identifiers_ignore_case = False when creating snowflake session. 
tested against snowflake instances.
=> Set quoted_identifiers_ignore_case explicitly to avoid case conversion for quoted identifiers

metaphor/snowflake/usage/extractor.py, pyproject.toml, tests/snowflake/usage/test_parser.py
pydantic validation does not allow unexpected fields in a model. Previous python build-in dataclass simply ignores extra fields. 
The Snowflake access history has different object structures https://docs.snowflake.com/en/user-guide/access-history.html , especially when it's copying for a STAGE or a local file. 
- Add potential fields of access history log in the model as optional with default None
- Check for only table/view `objectDomain` before further processing
tested against snowflake instances.
=> Snowflake usage crawler error [sc-7154]

metaphor/snowflake/extractor.py, pyproject.toml
While it's possible to use dots in Snowflake dataset/schema/table names, it breaks many of the assumptions in the connector. 
This is a temporary workaround by ignoring these tables. The proper fix will require a major refactoring of `LogicalDatasetID` to include database, schema, and table name as separate fields.
Manually tested against production.
=> Ignore any Snowflake dataset/schema/table that contains a dot in its name

metaphor/snowflake/profile/config.py, metaphor/snowflake/profile/extractor.py, metaphor/snowflake/utils.py, pyproject.toml, tests/snowflake/profile/config.yml, tests/snowflake/profile/test_config.py, tests/snowflake/profile/test_extractor.py
The current profiler can take an exceedingly long time to run against a large number of tables.
This PR introduced 2 optimizations:
1. Make profiling of each type of column statistics configurable and disable the expensive statistics (unique count, average, standard deviation)  by default.
2. Batch process the entire `information_schema.columns` instead of issuing individual queries for each table. This reduces the time from 10+ minutes to 10s for 1000 tables.
Finished profiling against 1500 tables within 10 mins, instead of hours w/o the optimization.
=> Optimize Snowflake profiler performance

metaphor/power_bi/README.md, metaphor/power_bi/extractor.py, pyproject.toml, tests/power_bi/expected.json, tests/power_bi/test_extractor.py
[Read-only Power BI admin APIs](https://docs.microsoft.com/en-us/power-bi/enterprise/read-only-apis-service-principal-authentication#method) is a subset of [Power BI REST APIs](https://docs.microsoft.com/en-us/rest/api/power-bi/) that are [specifically designed](https://powerbi.microsoft.com/en-us/blog/announcing-new-admin-apis-and-service-principal-authentication-to-make-for-better-tenant-metadata-scanning/) for metadata extraction. 
By using the admin APIs exclusively, we no longer need to
1. Grant the service principal access to Power BI API
2. Add the service principal to each workspace
It also allows us to extract metadata from personal workspaces (aka "My workspace").
- Replace all existing non-admin API calls with their admin counterpart
- Update README with simplified instructions …
=> Simplify Power BI connector setup by using read-only admin APIs exclusively

metaphor/power_bi/extractor.py, pyproject.toml, tests/power_bi/expected.json
As title
- Write URL to `sourceInfo`.
Manually test PowerBI crawler.
=> URL field on DashboardInfo is deprecated write to sourceInfo.mainUrl instead [sc-7604]

metaphor/looker/config.py, metaphor/looker/lookml_parser.py, pyproject.toml, tests/looker/config.yml, tests/looker/sql_table_name/model.model.lkml, tests/looker/sql_table_name/view.view.lkml, tests/looker/test_config.py, tests/looker/test_lookml_parser.py
Currently the Looker connector doesn't work with BigQuery connection as the config file requires the `account` field to be specified. It also fails to remove back-ticks in [sql_table_name](https://docs.looker.com/reference/view-params/sql_table_name-for-view) and generates invalid dataset IDs.
Make `account` field optional in config file and strip back-ticks when normalizing dataset names.
Unit tests.
=> Support BigQuery & handle quotes in sql_table_name

metaphor/looker/extractor.py, metaphor/metabase/extractor.py, pyproject.toml
We must not write a URL to this field because `DashboardInfo.url` is deprecated.
- Use `SourceInfo.main_url` instead
Run `Looker` and `Metabase` crawler successfully
=> Remove deprecated dashboard.url

metaphor/common/README.md
To make it clear that the environment variables to set when outputting to S3.
=> Add notes on AWS environment variables

metaphor/snowflake/usage/extractor.py, pyproject.toml
Seen some invalid snowflake dataset name in DB, and it's from the usage crawler. E.g. demo_db.public."dev_db.dbt_yi.test1"
- filter out invalid dataset name in log parsing
local run snowflake usage crawler, no invalid dataset names
=> Invalid Snowflake table name [sc-8756]

metaphor/snowflake/extractor.py, pyproject.toml
Query to snowflake account_usage views contains results for all DBs, so we should only do it once, not for each DB.
- Move snowflake tags query outside each DB iteration, and only run once.
Run it successfully at local, checked the output MCE
=> duplicate snowflake tags [sc-9457]

metaphor/bigquery/logEvent.py, pyproject.toml
Turns out not every [Query job](https://cloud.google.com/bigquery/docs/reference/auditlogs/rest/Shared.Types/BigQueryAuditMetadata#BigQueryAuditMetadata.JobConfig.Query) is guaranteed to have a `destinationTable` specified, e.g. a SCRIPT statement (i.e calling a stored procedure).
Ignore log entries that don't have a `desitnationTable` set.
Locally ran the connector to verify.
=> Fix Bigquery audit log parsing to handle QUERY jobs without a destination table

metaphor/thought_spot/extractor.py, metaphor/thought_spot/models.py, metaphor/thought_spot/utils.py, poetry.lock, pyproject.toml
Extract information about computed: `optional_type` representing a column is computed or not,`formula` stores the expression in TML code. The `formula` maybe is not very accurate since the TML could be auto generated or user defined. 
- Extract computed column metadata
- Run crawler in local and MCEs is correct.
=> Extract computed column from ThoughtSpot [SC-9521]

.github/workflows/cd.yml, Dockerfile, README.md
There is a delay (sometime hours) before the newly published package on PyPI becomes available. As a result, the current Docker image build process ends up installing the previous version.
Refactor Dockerfile and the CD pipeline to install directly from the latest source and tag it with the correct version number.
CD: https://github.com/MetaphorData/connectors/actions/runs/2599490786
Published: https://hub.docker.com/r/metaphordata/connectors/tags
=> Build Docker image directly from source instead of from PyPI

metaphor/snowflake/auth.py, pyproject.toml, tests/snowflake/config_missing_credentials.yml, tests/snowflake/config_with_key.yml, tests/snowflake/test_config.py
To ensure either password or private key is set in the config
- add pydantic validator to ensure either password or private key is set in the config
unit tests of the configs
=> Add pydantic validtor to snowflake auth config

metaphor/bigquery/config.py, metaphor/common/docs/git_repo.md, metaphor/common/git.py, metaphor/looker/README.md, metaphor/looker/config.py, metaphor/looker/extractor.py, poetry.lock, pyproject.toml, tests/common/test_git.py, tests/looker/config2.yml, tests/looker/config_missing_lookml.yml, tests/looker/test_config.py
Provides the capability to fetch LookML project from git repo
- use GitPython to clone LookML repo
- Update config
locally run crawler with access token
=> Use GitPython to crawl Looker repo [sc-5045]

metaphor/tableau/extractor.py, pyproject.toml
If set `disable_preview_image: true`, we didn't populate the preview image, but when building chart preview URL, it still fetches the `view.preview_image` field, which will throw this error if not populated. This doesn't affect the crawler output, just produces many unnecessary error messages.
- Check if preview disabled when building chart preview URL
Locally tested the crawler with preview disable, no errors.
=> Tableau crawler preview error [sc-9553]

metaphor/tableau/extractor.py, pyproject.toml
The `database` field under `DatabaseTable` can be null in the Metadata graphql API response. And seems unstable for `extract` data, as sometimes this field is missing, not always.
- Add check for null database, we are not parsing those `extract` data anyway.
tested locally without issue. I was able to reproduce this issue today with the previous code.
=> Tableau failed to parse workbook upstream [sc-9732]

metaphor/snowflake/README.md, metaphor/snowflake/auth.py, pyproject.toml, tests/snowflake/config.yml, tests/snowflake/config_with_key.yml, tests/snowflake/test_config.py
To allow users to connect using a different role, in case the default one doesn't work.
As titled. Also simplify the `connect` method.
Locally tested with & without the `role` config set.
=> Add optional role config for Snowflake connectors

metaphor/bigquery/config.py, metaphor/common/git.py, metaphor/common/utils.py, metaphor/looker/config.py, metaphor/snowflake/auth.py, pyproject.toml, tests/common/test_utils.py
Factor out common validation logic and make sure that it checks exactly one, not at least one.
As titled.
Unit tests.
=> Add must_set_exactly_one util method for config validation

metaphor/bigquery/README.md, metaphor/common/docs/filter.md, metaphor/common/docs/output.md, metaphor/common/filter.py, metaphor/dbt/README.md, metaphor/dbt/cloud/README.md, metaphor/google_directory/README.md, metaphor/looker/README.md, metaphor/manual/governance/README.md, metaphor/manual/lineage/README.md, metaphor/postgresql/README.md, metaphor/redshift/README.md, metaphor/snowflake/README.md, metaphor/snowflake/extractor.py, pyproject.toml, tests/common/test_filter.py
Sometimes it's useful to include/exclude databases/schemas/tables using wildcard (glob) patterns. For example, use `staging_*` to filter out all tables with a `staging_` prefix.
- Refactor `filter.include_table` to support glob patterns
- Move filter config doc to `common/docs` for consistency
Unit test and manually tested against production.
=> Support using glob patterns in filters

metaphor/common/extractor.py, pyproject.toml, tests/common/test_extractor.py
To prevent a stuck or mis-configured connector from running forever.
The original plan was to add a common `timeout` config option with a default value. However, it turns out that doing so [is difficult before Python 3.10](https://stackoverflow.com/questions/51575931/class-inheritance-in-python-3-7-dataclasses). Since this is more of a fail-safe mechanism than a configuration option, overriding it using an environment variable seems like a perfectly acceptable solution.
```
% TIMEOUT=2 python -m metaphor.bigquery ~/Desktop/local/bigquery.yml
...
File "/Users/marslan/.pyenv/versions/3.9.6/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/Users/marslan/.pyenv/versions/3.9.6/lib/python3.9/runpy.py", …
```
=> Add timeout to extractor execution

metaphor/power_bi/extractor.py, pyproject.toml
Power BI crawler is crashing with the following error:
```
GET https://api.powerbi.com/v1.0/myorg/admin/apps failed, {"error":{"code":"InvalidRequest","message":"This API expects $top query option to be provided."}}
```
Add the required `$top` parameter missed in https://github.com/MetaphorData/connectors/pull/301.
=> Add required $top parameter when querying PowerBI apps

metaphor/power_bi/extractor.py, pyproject.toml, tests/power_bi/test_extractor.py
A typo in the modeling, so the column data type always use the default value.
- Fix the typo and update the test case.
Verified the output of crawler.
=> PowerBI crawler didn't parse column data type [sc-10527]

.github/workflows/cd.yml
So the image can be imported in a sem-ver fashion, e.g. `metaphordata/connectors:0.10`.
As titled.
Manually invoked the CD workflow and verified the tags on Docker Hub: https://hub.docker.com/r/metaphordata/connectors/tags
=> Add major & minor version tags to published Docker image

metaphor/bigquery/README.md, metaphor/bigquery/config.py, metaphor/bigquery/extractor.py, pyproject.toml
The program is stuck at fetching table information from API. This is likely caused by resource contention with 2 levels of `executor.map` within the same thread pool, we used `executor.map`  to concurrently get datasets, and within that `executor.map` we use another map to get each table concurrently.
Refactoring the top-level to be a for-loop solved the problem.
- refactoring the threadpool `executor.map` to only used in to fetch tables within a dataset
- update readme to add `BigQuery Job User` permission which is needed for creating query job for table DDL.
- reduce the default concurrency from 10 to 5, as I run into warming `Connection pool is full, discarding connection: bigquery.googleapis.com. Connection pool size: 10`. Tested multiple times and this doesn't have a noticeable …
=> BQ crawler timing out [sc-10766]

metaphor/common/extractor.py, pyproject.toml, tests/common/test_extractor.py
Remove the custom timeout logic added in https://github.com/MetaphorData/connectors/pull/302 as it's better to implement this at a higher level (e.g. a launch script) using [signal](https://docs.python.org/3/library/signal.html) instead of in the connectors themselves.
As titled.
Manually verified that the connector still runs as expected.
=> Remove custom timeout logic

metaphor/bigquery/lineage/README.md, metaphor/bigquery/lineage/config.py, metaphor/bigquery/lineage/extractor.py, pyproject.toml, tests/bigquery/lineage/config.yml, tests/bigquery/lineage/data/result.json, tests/bigquery/lineage/data/sample_log.json, tests/bigquery/lineage/test_config.py, tests/bigquery/lineage/test_extractor.py, tests/bigquery/lineage/test_parser.py
We currently filter out BigQuery query log entries where the destination table appears in the source tables. This can lead to undesirable missing lineage.
Add a config option to control if self-reference should be filtered out, instead of dropping the query log entry altogether.
Verified against production.
=> Add option to filter self-loops in BigQuery lineage

metaphor/bigquery/profile/README.md, metaphor/bigquery/profile/config.py, metaphor/bigquery/profile/extractor.py, metaphor/common/column_statistics.py, metaphor/common/docs/column_statistics.md, metaphor/snowflake/profile/README.md, metaphor/snowflake/profile/config.py, pyproject.toml, tests/bigquery/profile/test_extractor.py
BigQuery profiler can take a long time to run for large tables. Disable computing of expensive column statistics like we did for Snowflake profiler https://github.com/MetaphorData/connectors/pull/227.
- Move `ColumnStatistics` class to `metaphor.common` package and add README file
- Add `column_statistics` config and construct BigQuery profiling query based on the settings 
Tested again production. A previous run that timed out after an hour now completed in 15 minutes.
=> Speed up BigQuery profiler by turning off expensive column statistics by default

metaphor/snowflake/usage/extractor.py, pyproject.toml
ambiguous column name 'USER_NAME' when using user filter
- add table qualifier for the 'USER_NAME' column
tested against production instance
=> Snowflake usage ambiguous column name USER [sc-11092]

metaphor/bigquery/extractor.py, pyproject.toml
used python `dict[]` by mistake, which throws keyerror if the key is not found. 
- use `dict.get()` since we are checking for `None` value in the next line
tested against production instance.
=> BigQuery KeyError snapshot sync configuration [sc-11102]

metaphor/bigquery/README.md, metaphor/bigquery/config.py, metaphor/bigquery/extractor.py, metaphor/bigquery/profile/extractor.py, pyproject.toml, tests/bigquery/config.yml, tests/bigquery/test_config.py
To allow running BigQuery jobs using a project ID different from the default.
As titled.
Manually tested against a production deployment.
=> Add optional job_project_id config to BigQuery crawlers

metaphor/bigquery/lineage/README.md, metaphor/snowflake/lineage/README.md, metaphor/snowflake/lineage/config.py, metaphor/snowflake/lineage/extractor.py, pyproject.toml, tests/snowflake/lineage/data/parse_object_dependencies_result.json, tests/snowflake/lineage/test_config.py, tests/snowflake/lineage/test_parser.py
the `access_history` doesn’t contain any table to view lineage, since creating a view by query does not actually write any data.
- use the `object_dependencies` view to get table to view direct relationship. https://docs.snowflake.com/en/user-guide/object-dependencies.html#label-object-dependencies-view-query
tested against our snowflake instance and verified the output JSON
=> Missing snowflake view lineage [sc-11489]

metaphor/power_bi/power_query_parser.py, pyproject.toml, tests/power_bi/test_parse_power_query.py
It's possible to specify database, schema, and table name without using the double quotation marks in PAX, e.g. 
```
let
Source = Snowflake.Databases("<account>", DATA_WAREHOUSE, [CreateNavigationProperties=null, ConnectionTimeout=null, CommandTimeout=null]),\
DB_PRD_REPORTING_Database = Source{[Name=DATABASE,Kind="Database"]}[Data],
EDW_Schema = DB_PRD_REPORTING_Database{[Name="EDW",Kind="Schema"]}[Data],
SITE_VW_View = EDW_Schema{[Name="SITE_VW",Kind="View"]}[Data],
...
```
In this case, the only way to extract the name of the database (`DB_PRD_REPORTING`) is from the variable name (`DB_PRD_REPORTING_Database`). 
As titled.
Manually verified against the production deployment.
=> Improve PAX parsing to handle names without quotes

metaphor/postgresql/extractor.py, metaphor/snowflake/extractor.py, pyproject.toml
`fieldName` will be required once all data has been populated
- update dataset crawlers to add fieldName for `SchemaField`
locally run crawlers and check output
=> crawlers fill in fieldName for each column [sc-11564]

metaphor/snowflake/extractor.py, pyproject.toml
Snowflake connector is currently broken with the following error:
```
ERROR:metaphor.common.extractor:year 51193146 is out of range
File "/usr/local/lib/python3.8/site-packages/metaphor/common/extractor.py", line 50, in run
entities = asyncio.run(self.extract(config))
File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
File "/usr/local/lib/python3.8/site-packages/metaphor/snowflake/extractor.py", line 91, in extract
self._fetch_table_info(conn, tables)
File "/usr/local/lib/python3.8/site-packages/metaphor/snowflake/extractor.py", line 231, in _fetch_table_info
dataset.statistics.last_updated = …
```
=> Fix Snowflake connector to work with the new timestamp unit

metaphor/power_bi/power_query_parser.py, pyproject.toml, tests/power_bi/test_parse_power_query.py
The current parser implementation adds extra spaces for the Redshift database names, e.g. for the following DAX expression
```
let
Source = AmazonRedshift.Database("url:5439", "db" )
public = Source{[Name="public"]}[Data]
table1 = public{[Name="table"]}[Data]
in
table1'
```
the parser returns a dataset name ` db .public.test`
Strip off the extra spaces.
Tested against a production deployment.
=> Fix Power BI DAX parsing for Redshift sources

metaphor/power_bi/extractor.py, metaphor/power_bi/power_query_parser.py, pyproject.toml, tests/power_bi/test_parse_power_query.py
Power BI connector throws the following error while parsing Redshift native queries:
```
File "/Users/marslan/Metaphor/connectors/metaphor/power_bi/extractor.py", line 396, in map_wi_datasets_to_virtual_views
source_datasets.extend(PowerQueryParser.parse_source_datasets(expression))
File "/Users/marslan/Metaphor/connectors/metaphor/power_bi/power_query_parser.py", line 176, in parse_source_datasets
return PowerQueryParser.parse_native_query(power_query)
File "/Users/marslan/Metaphor/connectors/metaphor/power_bi/power_query_parser.py", line 162, in parse_native_query
tables = PowerQueryParser.parse_tables(parameters[1])
File "/Users/marslan/Metaphor/connectors/metaphor/power_bi/power_query_parser.py", line 147, in parse_tables
assert (
AssertionError: …
```
=> Fix Power BI native query parsing for Redshift

metaphor/postgresql/extractor.py, metaphor/redshift/README.md, metaphor/redshift/extractor.py, pyproject.toml
To support external tables from Redshift Spectrum.
- Extract metadata from [SVV_EXTERNAL_*](https://docs.aws.amazon.com/redshift/latest/dg/r_SVV_EXTERNAL_TABLES.html)
- The lineage, query and usage connector need extra work to support external tables.
Run `metaphor redshift configs/redshift.yml` and `metaphor redshift.profile configs/redshift_profile.yml` and verified the output.
=> Add support for redshift spectrum [sc-11994]

metaphor/dbt/generated/dbt_manifest_v5.py, metaphor/dbt/generated/dbt_manifest_v6.py, pyproject.toml
While the JSON schema specifies that the `name` field of the `docs` block is [required](https://schemas.getdbt.com/dbt/manifest/v5/index.html#docs_additionalProperties_name), in reality it can be `null` for some special cases, e.g.
```
"docs":
{
"<project>.None":
{
"unique_id": "<id>",
"package_name": "<package>",
"root_path": "/tmp/jobs/<job_id>/target",
"path": "README.md",
"original_file_path": "docs/README.md",
"name": null,
"block_contents": "## content\n  ## supports markdown"
},
...
}
``` 
This can lead to the following error when validating `manifest.json`:
```
File "/Users/marslan/Metaphor/connectors/metaphor/common/extractor.py", line 50, in run
entities = asyncio.run(self.extract(config))
File …
```
=> Fix dbt's JSON schema to match the reality

metaphor/snowflake/accessed_object.py, pyproject.toml, tests/snowflake/lineage/test_parser.py, tests/snowflake/usage/test_parser.py
The Snowflake AccessHistory parser throws the following error:
```
File "/usr/local/lib/python3.8/site-packages/metaphor/snowflake/lineage/extractor.py", line 157, in _parse_access_logs
self._parse_access_log(base_objects_accessed, objects_modified, query)
File "/usr/local/lib/python3.8/site-packages/metaphor/snowflake/lineage/extractor.py", line 171, in _parse_access_log
source_objects = parse_raw_as(List[AccessedObject], objects_accessed)
File "pydantic/tools.py", line 82, in pydantic.tools.parse_raw_as
File "pydantic/tools.py", line 38, in pydantic.tools.parse_obj_as
File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for …
```
=> Make column ID optional when parsing Snowflake's AccessObject

metaphor/power_bi/README.md, metaphor/power_bi/extractor.py, pyproject.toml, tests/power_bi/expected.json, tests/power_bi/test_extractor.py
Power BI's [REST API](https://docs.microsoft.com/en-us/rest/api/power-bi/) doesn't include any visualization information (charts) for [reports](https://docs.microsoft.com/en-us/power-bi/fundamentals/service-basic-concepts#reports). However, the name of the pages (tabs) in the report is considered a good proxy for the visualizations and should therefore be mapped to charts.
As titled. Use the [Get Pages in Group](https://docs.microsoft.com/en-us/rest/api/power-bi/reports/get-pages-in-group) API to retrieve the information, which requires additional permissions. 
Tested against a production deployment.
=> Map Power BI report pages to charts

metaphor/common/logger.py, metaphor/thought_spot/utils.py
`logger` module can be imported multiple time, and different loggers use the same output file. The last logger output will overwrite other logs.
- Change file logger mode from 'w' to 'a'
Run ThoughtSpot connector locally to verified.
=> Improve logger

metaphor/snowflake/README.md, metaphor/snowflake/extractor.py, pyproject.toml
shared inbound databases don't support get_ddl()
- fetch the `shared` DB info
- Ignore shared DB when get_ddl()
tested locally fetching 'SNOWFLAKE' database
=> Ignore shared databases when retrieving DDLs [sc-12169]

metaphor/snowflake/extractor.py, pyproject.toml
For a snowflake database with a large number of tables, the query to get table info including DDL can get exceedingly long. 
- Cap the number of tables info to fetch in one query to 100
tested against snowflake instance, and verified the output is the same as before.
=> Statement exhausted compilation resources [sc-13029]

metaphor/redshift/extractor.py, pyproject.toml
Currently the Redshift connect will bail out completely if it hits any issue (e.g. permission) when crawling a specific database.
As titled.
=> Catch Redshift connectors errors without failing the whole process

metaphor/snowflake/auth.py, pyproject.toml, tests/snowflake/config.yml, tests/snowflake/test_config.py
Allows users to change to set the Snowflake warehouse to use instead of relying on the default warehouse.
As titled.
Manually verified against a production instance.
=> Add an optional "warehouse" config to Snowflake connectors

metaphor/redshift/lineage/extractor.py, pyproject.toml
`stl_query` didn't contain the full query. The sql parse may throw parsing error.
- Join [SQL_QUERYTEXT](https://docs.aws.amazon.com/redshift/latest/dg/r_STL_QUERYTEXT.html) for full query text.
- Catch the exception and log it.
Run crawler against dev and prod environment.
=> Improve Redshift lineage

metaphor/dbt/manifest_parser_v5.py, metaphor/dbt/manifest_parser_v6.py, pyproject.toml, tests/dbt/data/trial_v4/results.json, tests/dbt/data/trial_v5/results.json, tests/dbt/data/trial_v6/results.json
Missed the `timestamp` field from dbt metric
- retrieve timestamp field
unit testes
=> add more dbt metadata to metrics page [sc-13485]

metaphor/airflow_plugin/lineage/entity.py, metaphor/bigquery/extractor.py, metaphor/bigquery/profile/extractor.py, metaphor/common/entity_id.py, metaphor/common/usage_util.py, metaphor/dbt/manifest_parser_v3.py, metaphor/dbt/manifest_parser_v5.py, metaphor/dbt/manifest_parser_v6.py, metaphor/dbt/util.py, metaphor/glue/extractor.py, metaphor/metabase/extractor.py, metaphor/postgresql/extractor.py, metaphor/postgresql/profile/extractor.py, metaphor/postgresql/usage/extractor.py, metaphor/power_bi/power_query_parser.py, metaphor/redshift/extractor.py, metaphor/snowflake/extractor.py, metaphor/snowflake/lineage/extractor.py, metaphor/snowflake/profile/extractor.py, metaphor/thought_spot/extractor.py, metaphor/unity_catalog/extractor.py, pyproject.toml, tests/bigquery/expected.json, tests/bigquery/profile/test_extractor.py, tests/common/test_entity_id.py, tests/glue/expected.json, tests/snowflake/profile/test_extractor.py
Fill out the three level `DatasetStructure` to enable the next step of showing case sensitive name. Potentially we can support name with dots.
- Fill out the field for `Bigquery`, `Snowflake`, `Redshift`, `PostgreSQL`, and `Glue`.
- Use `dataset_fullname` to fill out the logical id as possible
- Unit tests.
- Run `Snowflake`, `Bigquery`, and `Redshift` crawler on local, ingest the MCEs, and verified the result on Metaphor.
=> Fill dataset structure from crawler

metaphor/snowflake/extractor.py, metaphor/snowflake/utils.py, pyproject.toml
Non-enterprise snowflake accounts won't have access to the `access_history` view to get access logs.
- check if the `access_history` view is available, if not, only fetch the raw query text from `query_history`
tested against snowflake instance. Tested with the `has_access_history` set to both true and false.
=> Remove dependency on Snowflake Enterprise [sc-13398]

metaphor/looker/extractor.py, metaphor/looker/lookml_parser.py, pyproject.toml
It's possible to create malformed dashboards in Looker which causes the Looker SDK to throw errors when deserializing returned the API content.
Catch and ignore SDK errors when encountering malformed dashboards. Also changed to the shared logger in `lookml_parser.py`.
Manually tested against a production instance containing malformed dashboards.
=> Ignore malformed Looker dashboards

metaphor/dbt/catalog_parser_v1.py, metaphor/dbt/cloud/extractor.py, metaphor/dbt/manifest_parser_v3.py, metaphor/dbt/manifest_parser_v5.py, metaphor/dbt/manifest_parser_v6.py, metaphor/dbt/util.py, pyproject.toml, tests/dbt/cloud/test_extractor.py, tests/dbt/data/trial_v4/results.json, tests/dbt/data/trial_v5/results.json, tests/dbt/data/trial_v6/results.json
To be able to show direct link to the dbt metric docs page from metaphor UI
- generate metric URL from base URL and metric id
- fix dbt cloud URL, it uses `job` instead of `run` now.
Tested the dbt cloud crawler locally, and verified the URLs.
=> populate DBT metric URL [sc-13231]

metaphor/common/file_sink.py, metaphor/common/logger.py, metaphor/dbt/cloud/extractor.py, metaphor/dbt/extractor.py, pyproject.toml, tests/common/test_file_sink.py
To make it easier to debug.
As titled. Also added `manifest.json` & `catalog.json` to `log.zip` for `dbt` & `dbt.cloud` connectors.
Ran the connector locally and verified the content of the zip file:
=> Allow adding debug files to log.zip

metaphor/manual/governance/README.md, metaphor/manual/governance/config.py, metaphor/manual/governance/extractor.py, poetry.lock, pyproject.toml, tests/manual/governance/config.yml, tests/manual/governance/expected.json, tests/manual/governance/test_config.py
To allow users to manually specify governed tags at the column-level.
- Add `column_tags` to `DatasetGovernance` config class
- Map `column_tags` to `column_tag_assignments` field in `TagAssignment`
- Update tests & README
Unit tests + manually verified the output.
=> Add column-level tagging to manual governance connector

metaphor/common/entity_id.py, metaphor/common/models.py, pyproject.toml, tests/common/test_models.py
The dataset name specified in the config, e.g. for [manual.governance](https://github.com/MetaphorData/connectors/blob/main/metaphor/manual/governance/README.md) connector, are not normalized, which can lead to IDs that don't match the actual table.
As titled.
Tested end-to-end against a production deployment.
=> Normalize dataset name specified in configs

metaphor/common/base_config.py, metaphor/common/docs/env_var.md, metaphor/common/variable.py, pyproject.toml, tests/common/test_variable.py
This makes it easier to specify sensitive configs (e.g. password, secrets) using environment variables, especially in the context of https://github.com/MetaphorData/connectors-action, where the only possible way to pass GitHub secrets is via environment variables.
As titled.
Unit tests
=> Add support for environment variable substitution in config files

docs/apple_silicon.md, docs/develop.md
`poetry install -E all` failed on M1 with the following error similar to https://github.com/pymssql/pymssql/issues/727
As titled.
Manually verified the build on M1.
=> Add M1-specific build instruction for pymssql

.github/workflows/ci.yml
Some existing files have very low coverage or not easily testable, this will prevent PRs from being blocked unnecessarily long.
=> Disable coverage threshold for modified files

metaphor/snowflake/README.md, metaphor/snowflake/config.py, metaphor/snowflake/extractor.py, metaphor/snowflake/profile/extractor.py, metaphor/snowflake/utils.py, pyproject.toml, tests/snowflake/profile/test_extractor.py, tests/snowflake/test_extractor.py
The account_usage views have significant delay which can cause the crawler not able to fetch any information after a table recreation. 
- revert back to use information_schema to fetch metadata
tested against snowflake instance.
=> rollback snowflake crawler to use information [sc-15044]

metaphor/snowflake/lineage/extractor.py, pyproject.toml
Some customers may have a lot of query logs on tables that are filtered out by config, causing a flood of info logs and drowning the useful info. 
- use debug instead of info for logging filtered tables
n/a
=> reduce unnecessary log in snowflake lineage crawler

metaphor/tableau/extractor.py, metaphor/tableau/graphql_utils.py, metaphor/tableau/query.py, pyproject.toml, tests/tableau/test_extractor.py, tests/tableau/test_graphql_utils.py
Tableau's [Metadata API](https://help.tableau.com/current/api/metadata_api/en-us/index.html) places a [limit](https://help.tableau.com/current/api/metadata_api/en-us/docs/meta_api_errors.html#:~:text=might%20be%20incomplete.-,NODE_LIMIT_EXCEEDED,-Warning) on the number of nodes returned. When exceeded, it'll return partial results, which can lead to incomplete lineage.
An example of the corresponding GraphQL error: 
```
"errors": [
{
"message": "Showing partial results. The request exceeded the 20000 node limit. Use pagination, additional filtering, or both in the query to adjust results.",
"extensions": {
"severity": "WARNING",
"code": "NODE_LIMIT_EXCEEDED",
"properties": {
"nodeLimit": 20000
}
}
}
]
```
Add [pagination](https://help.tableau.com/current/api/metadata_api/en-us/docs/meta_ap …
=> Add pagination to Tableau Metadata API

metaphor/power_bi/extractor.py, metaphor/power_bi/power_bi_client.py, metaphor/power_bi/power_query_parser.py, pyproject.toml
Depending the workspace processing order, the crawler may crash when processing Power BI dashboards/reports that reference a dataset from another workspace with the following error:
```
023-02-27 13:29:39:ERROR:metaphor:'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
File "/Users/marslan/Metaphor/connectors/metaphor/power_bi/extractor.py", line 92, in extract
self.map_wi_reports_to_dashboard(workspace, app_map)
File "/Users/marslan/Metaphor/connectors/metaphor/power_bi/extractor.py", line 191, in map_wi_reports_to_dashboard
self._virtual_views[wi_report.datasetId].logical_id,
KeyError: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
```
- Process datasets across all workspaces up front to avoid invalid cross-workspace references in datasets & reports. 
- Refactored …
=> Fix Power BI cross-workspace dataset references

metaphor/power_bi/extractor.py, metaphor/power_bi/power_bi_client.py, pyproject.toml, tests/power_bi/test_extractor.py
The [Datasets - Get Refresh History](https://learn.microsoft.com/en-us/rest/api/power-bi/datasets/get-refresh-history) can return empty strings or missing value for the [`status`](https://learn.microsoft.com/en-us/rest/api/power-bi/datasets/get-refresh-history#:~:text=of%20the%20refresh-,status,-string)  and [`endTime`](https://learn.microsoft.com/en-us/rest/api/power-bi/datasets/get-refresh-history#:~:text=Description-,endTime,-string) fields, which can lead to model validation error like the following,
```
validation errors for ParsingModel[List[metaphor.power_bi.power_bi_client.PowerBIRefresh]]
__root__ -> 18 -> endTime
field required (type=value_error.missing)
__root__ -> 19 -> status
value is not a valid enumeration member; permitted: 'Unknown', 'Completed', 'Failed', 'Disabled' …
```
=> Make Power BI connector more robust against unexpected API returns

metaphor/bigquery/README.md, metaphor/bigquery/config.py, metaphor/bigquery/extractor.py, metaphor/bigquery/logEvent.py, pyproject.toml, tests/bigquery/lineage/data/sample_log.json, tests/bigquery/lineage/test_parser.py
BigQuery audit metadata log has a size limit 100KB
https://cloud.google.com/bigquery/docs/reference/auditlogs#limitation
Longer SQL will be truncated, thus we need to call `jobs.get` to get the full job spec.
- Check `queryTruncated` flag and call `jobs` API to get full query SQL
tested locally against BigQuery instance
=> BigQuery truncate long SQL in audit log [sc-16983]

metaphor/unity_catalog/utils.py, pyproject.toml
Unity Catalog's Lineage API is only [available on AWS & Azure](https://www.databricks.com/blog/2022/12/12/announcing-general-availability-data-lineage-unity-catalog.html) for now. It'd return HTTP 503 error when running against a GCP instance.
Add try-catch to handle the missing API gracefully.
Verified against a production instance running on GCP.
=> Handle missing Unity Catalog lineage API gracefully

metaphor/bigquery/README.md, metaphor/bigquery/extractor.py, metaphor/bigquery/lineage/README.md, pyproject.toml
PR #474 added capability to query BigQuery job API to get full SQL. But that requires additional permission `jobs.get` which we didn't request from customer. This will result in access deny error.
- update README to add process for creating custom role and added to service account.
- reduced the required permissions to minimum
- add error handling to job detail fetching
created new service account following the process and verified the crawler
=> BigQuery access denied for jobs get API [sc-17038]

metaphor/power_bi/README.md, metaphor/power_bi/power_bi_client.py, pyproject.toml
When the client secret is invalid of missing, the Power BI extractor will throw the following cryptic exception:
```
File "/Users/marslan/Metaphor/connectors/metaphor/common/runner.py", line 54, in run_connector
entities = connector_func()
File "/Users/marslan/Metaphor/connectors/metaphor/common/base_extractor.py", line 32, in run_async
File "/Users/marslan/.pyenv/versions/3.9.6/lib/python3.9/asyncio/runners.py", line 44, in run
File "/Users/marslan/.pyenv/versions/3.9.6/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
File "/Users/marslan/Metaphor/connectors/metaphor/power_bi/extractor.py", line 71, in extract
self._client = …
```
=> Add error handling for Power BI access token retrieval

metaphor/thought_spot/utils.py, pyproject.toml
Currently the logs for different types of ThoughtSpot data objects get clobbered into one, making it difficult to debug.
Split the log files based on data object types.
Before:
After:
=> Fix logging for ThoughtSpot API calls

poetry.lock, pyproject.toml
sqllinage released an update that fixes the [monkey patch broken by sqlparse 0.4.4](https://github.com/reata/sqllineage/pull/360). Since newer versions of sqlllinage has [dropped the dependency on flask](https://github.com/reata/sqllineage/pull/305), it's safe to switch back to using it. Also avoided 1.4.x, which [replace sqlparse with sqlfluff](https://github.com/reata/sqllineage/issues/302), for now until further testing.
As titled.
=> Replace metaphor-sqllineage with sqllineage

metaphor/snowflake/extractor.py, metaphor/snowflake/utils.py, pyproject.toml
It seems that the ACCESS_HISTORY view also has a column "USER_NAME" now, so when joining it with QUERY_HISTORY view and adding the exclude username clause, it causes ambiguous column error
- add table qualifier to the "USER_NAME" column, the joining query already used `q` as the alias, so we reused that
added `excluded_usernames` config and crawler our testing Snowflake instance, previous code will throw error, but the updated code works fine.
=> ambiguous column name error for Snowflake [sc-17430]

metaphor/fivetran/extractor.py, pyproject.toml, tests/fivetran/data/v1__metadata__connectors__connector_2__columns.json, tests/fivetran/data/v1__metadata__connectors__connector_2__tables.json, tests/fivetran/expected.json
When a connector has multiple table, sourceEntityId field was incorrect. The reason was we use `@lru_cache` for generate `FiveTranConnector` object for not spending too much time on serializing json objects, which cause different `dataset` share the same `FiveTranConnector`; therefore the `SourceEntityId` will be the last table's ID.
- Drop the cache decorator
- Update test data to cover the case
=> SourceEntityId is incorrect

metaphor/common/models.py, metaphor/redshift/extractor.py, pyproject.toml, tests/bigquery/expected.json
We have deprecated `dataSize` field in favor of `dataSizeBytes` field and UI has already migrated.
- Stop crawlers from writing to `dataSize` field 
unit tests. Tested locally against Snowflake and BigQuery
=> Remove dataSize field [sc-17825]

metaphor/snowflake/README.md, metaphor/snowflake/auth.py, pyproject.toml
Sometimes it's more convenient to specify the content of the private key directly in the config file, instead of pointing it to an external file.
As titled.
Tested end-to-end against a production instance.
=> Add support to specify Snowflake private key data directly in the config

metaphor/common/snowflake.py, metaphor/dbt/catalog_parser_v1.py, metaphor/dbt/manifest_parser.py, metaphor/fivetran/extractor.py, pyproject.toml, tests/common/test_snowflake.py
Some systems (e.g. dbt & Fivetran) support [Snowflake PrivateLink](https://docs.snowflake.com/en/user-guide/admin-security-privatelink) and use the PrivateLink version of the account name (i.e. `<normal_account_name>.privatelink`). This can cause issues when matching datasets across systems.
Added `normalize_snowflake_account` function that is currently limited to stripping the `.privatelink` suffix from the account name. Will address any other variations listed in https://docs.snowflake.com/en/user-guide/admin-account-identifier#label-account-name in future PRs.
Tested against a production instance and manually verified the MCEs.
=> Normalize PrivateLink Snowflake account names for dbt & FiveTran

metaphor/tableau/extractor.py, pyproject.toml, tests/tableau/expected.json, tests/tableau/test_extractor.py
Currently the connector reference upstream datasets using entity IDs hoping that the datasets have already been created by the corresponding dataset connector (e.g. Snowflake, BigQuery, etc.). However, this can become confusing and very difficult to debug for the users. It'd be better to create placeholder datasets so at least they show up in the lineage. 
As titled.
Tested against a production instance and verified the MCEs manually.
=> [Tableau] Output placeholder upstream datasets in MCE

metaphor/common/utils.py, metaphor/dbt/manifest_parser.py, pyproject.toml, tests/common/test_utils.py
Seems like it's possible to specify empty tags in older versions of dbt. We should filter these out when creating the MCEs.
Added `filter_empty_strings` util method to filter out empty tags.
=> [dbt] Filter out empty tags

metaphor/common/file_sink.py, metaphor/common/utils.py, pyproject.toml, tests/common/test_file_sink.py, tests/common/test_utils.py
The current size-based chunking can lead to large files (100's of MB) for large individual items. These large files are slow to process and can also lead to OOM issues.
- Add a `batch_size_bytes` config to replace `batch_size`
- Add a generic `chunk_by_size` util method
- Update `FileSink` to chunk output by the size JSON-serialized string
Tested against a production instance:
=> Use size-based chunking when spliting MCE files

metaphor/common/file_sink.py, metaphor/common/utils.py, pyproject.toml, tests/common/test_utils.py
https://github.com/MetaphorData/connectors/pull/509 changed from count-based chunking to size-based chunking. While it works for most cases, it can lead to various ingestion difficulties (OOM, slow processing) when a file contains a large number of small records.
As titled. Added a `batch_size_count` config to control the maximum number of records in each MCE file.
Tested against a production instance with a `batch_size_count` of 40.
```
2023-05-27 10:46:24:INFO:metaphor:Ended running with RunStatus.SUCCESS at 2023-05-27 10:46:24.344648, fetched 163 entities, took 13.5s
2023-05-27 10:46:24:INFO:metaphor:Written 1-of-5.json (40 records)
2023-05-27 10:46:24:INFO:metaphor:Written 2-of-5.json (40 records)
2023-05-27 10:46:24:INFO:metaphor:Written 3-of-5.json (40 records)
2023-05-27 …
```
=> Add a per-chunk item count limit to chunk_by_size

metaphor/thought_spot/extractor.py, metaphor/thought_spot/utils.py, pyproject.toml
ThoughtSpot crawler cannot handle complex case of column lineage, this PR will catch the error to keep crawler running.
- Only get expression if possible, fill `None` otherwise
- Move `get_column_lineage` in try...catch
Test against production env.
=> [ThoughtSpot] Column' object has no attribute 'expression'

metaphor/fivetran/extractor.py, pyproject.toml, tests/fivetran/expected.json
To complete the lineage for known platform when we don't have the corresponding crawler, for example, SQL server.
- Add dummy dataset for source.
Update tests
=> Fivetran crawler should create "placeholder nodes" for systems that are natively supported.

metaphor/snowflake/lineage/extractor.py, pyproject.toml, tests/common/test_utils.py, tests/snowflake/lineage/test_extractor.py
Encountered the following error when ingesting Snowflake Lineage: 
```
MCE parsing error Error: Class MetadataChangeEvent2 validation error:  "sourceDatasets" is not a valid unique array of entity IDs
```
Turns out that Snowflake's [OBJECT_DEPENDENCY view](https://docs.snowflake.com/en/sql-reference/account-usage/object_dependencies) can contain rows with repeated content, leading to the same IDs added to `source_datasets` field multiple times.
Make sure the entity ID is unique before appending it to `source_datasets` in `_parse_object_dependencies`.
Verified against a production instance
=> [Snowflake] Make sure upstream datasets contain only unique IDs

metaphor/common/api_request.py, metaphor/fivetran/extractor.py, metaphor/fivetran/models.py, pyproject.toml
First, turned out the "name_in_source" was optional. Second, the validation part was too strict if the model didn't match the api response, the whole crawler stop.
- Make the field optional, verified the output json dump file, name_in_source in `SchemaMetadata` could be null
- add `try...except` around `parse_obj_as` to add more context to log.
- Add a random string to debug file to avoid duplicated name, repeated call with different query or body.
Test against production environment.
=> Fivetran validation error

Dockerfile, pyproject.toml
`GitPython` requires git to be installed. Instead of relying on child images to install git explicitly, it makes more sense to preinstall it in the base image.
As titled. Also added a script to automate docker image building.
```
% ./scripts/build_docker_image.sh
...
=> CACHED [1/7] FROM docker.io/library/python:3.8-slim@sha256:8f9d73f3f3ffcabcfbe7c8a0330c8cb054bde96dd46992e97539d43153434db  0.0s
=> [2/7] COPY . /src                                                                                                           0.2s
=> [3/7] RUN pip install '/src[all]'                                                                                         196.6s
=> [4/7] RUN rm -rf /src                                                                                                       0.4s
=> …
```
=> Install git in docker image

.pre-commit-config.yaml, metaphor/common/file_sink.py, metaphor/synapse/config.py, metaphor/thought_spot/extractor.py, metaphor/thought_spot/utils.py, poetry.lock, pyproject.toml, tests/common/test_utils.py
To resolve security issues such as https://github.com/MetaphorData/connectors/security/dependabot/32, https://github.com/MetaphorData/connectors/security/dependabot/27 https://github.com/MetaphorData/connectors/security/dependabot/31
- upgrade apache-airflow and other dev dependency versions, some of them are made possible after upgrading to Python 3.8
locally run snowflake, bigquery, TS crawlers
=> update dev dependencies include apache-airflow

metaphor/common/snowflake.py, pyproject.toml, tests/common/test_snowflake.py
While not explicitly documented in https://docs.snowflake.com/en/user-guide/admin-account-identifier, the Snowflake account name appears to be case insensitive. This makes sense since it's used as part of the URL (e.g. `https://acme-marketing-test-account.snowflakecomputing.com`). We need to normalize it as such across systems.
As titled.
Unit tests.
=> Lower case the Snowflake account name when normalizing

metaphor/monte_carlo/extractor.py, pyproject.toml, tests/monte_carlo/expected.json, tests/monte_carlo/test_extractor.py
To fill in the `url` field, which can be used to access the dataset page on Monte Carlo side.
- Extract MC dataset URL
- Normalize column names
- Store the raw GraphQL response JSON in `log.zip` to help debug issues.
Manually tested against a production instance.
=> Extract dataset URL from Monte Carlo

metaphor/tableau/extractor.py, pyproject.toml, tests/tableau/expected.json, tests/tableau/test_extractor.py
The current tableau workbook extractor only used the immediate project name but did not include the parent project name. This will result in a flattened hierarchy. 
- fetch all projects and build each project full name
- use project id to link to the project full name of each workbook
tested against tableau server
=> Display Tableau nested hierarchy in metaphor [sc-18850]

metaphor/common/docs/output.md, metaphor/common/storage.py, pyproject.toml, tests/common/test_storage.py
It was missing before, which prevents users from specifying all S3 credentials via config files.
As titled. Also updated README & added tests.
=> Add region_name to S3StorageConfig

metaphor/bigquery/profile/extractor.py, metaphor/common/utils.py, metaphor/snowflake/profile/extractor.py, pyproject.toml, tests/snowflake/profile/test_extractor.py
The data profiler may receive values that's python `NaN`, and that's put into JSON like `"maxValue": NaN` which can't be decoded.
- convert `NaN` value to None in the profiler
unit tests
=> NaN value in MCE [sc-19559]

metaphor/fivetran/extractor.py, pyproject.toml, tests/fivetran/expected.json
We have migrated to use the `upstream.pipeline_entity_id`, no need to keep the redundant information in `fivetran_connector` field
- stop filling the `dataset.upstream.five_tran_connector` field
unit tests
run locally and verified MCE file
=> Remove deprecated Fivertran field from crawler [sc-19619]

.github/workflows/cd.yml, poetry.lock, pyproject.toml
Since PyPI doesn't allow re-publishing an existing version, we should do the same for Docker to prevent the 2 versions from going out of sync.
As titled.
https://github.com/MetaphorData/connectors/actions/runs/5713625309/job/15479353312
=> Skip publishing docker imeage for existingt tags

metaphor/common/utils.py, pyproject.toml, tests/snowflake/profile/test_extractor.py
the table profiler may return statistic value as "INFINITY", which is serialized to JSON as `"field": Infinity`. This is an invalid json when deserialize. 
- check for Infinity value just like we check for NaN value, and return None
tested against the snowflake instance, though we don't have INF in the response.
=> Alert An error of type Programmatic Error [sc-19884]

metaphor/common/utils.py, metaphor/dbt/cloud/client.py, metaphor/dbt/cloud/config.py, metaphor/dbt/cloud/extractor.py, pyproject.toml, tests/dbt/cloud/config_legacy.yml, tests/dbt/cloud/test_client.py, tests/dbt/cloud/test_config.py, tests/dbt/cloud/test_extractor.py
Setting up separate connectors for multiple dbt jobs quickly becomes a maintenance headache. Given how quickly it is to fetch metadata for a single dbt job, supporting multiple jobs in a single connector seems like an obvious extension.
- Add `job_ids` config and deprecate `job_id`
- Update connector to support multiple job IDs
- Move `DbtAdminAPIClient` into a separate file and add tests
=> Support fetching metadata from multiple dbt cloud jobs

metaphor/fivetran/extractor.py, pyproject.toml, tests/fivetran/data/v1__connectors__connector_3.json, tests/fivetran/data/v1__groups__group_id_1__connectors_2.json, tests/fivetran/data/v1__metadata__connectors__connector_3__columns.json, tests/fivetran/data/v1__metadata__connectors__connector_3__schemas.json, tests/fivetran/data/v1__metadata__connectors__connector_3__tables.json, tests/fivetran/expected.json, tests/fivetran/test_extractor.py, tests/fivetran/test_get_account.py
We only fill account field in dataset logical ID for `Snowflake`, so the lineage associating with sqlserver connector was broken.
Fill account for MSSQL tables
unit tests
=> Fix Fivetran pipeline associating MSSQL

metaphor/monte_carlo/config.py, tests/monte_carlo/config.yml, tests/monte_carlo/test_config.py
The field has long been deprecated and unused.
As titled. Will bump up the minor version once all [breaking changes](https://github.com/MetaphorData/connectors/issues/523) are merged. 
=> Drop unused data_platform field from MC's config

metaphor/dbt/manifest_parser.py, pyproject.toml, tests/dbt/test_extractor.py
dbt 1.6.6 introduced changes that are not compatible with the latest manifest JSON schema: https://github.com/dbt-labs/dbt-core/issues/8851
Strip off the extra fields in metrics as a temporary work around. Also add tests for all current workarounds.
=> Fix dbt 1.6.6 manifest schema validation errors

metaphor/tableau/extractor.py, pyproject.toml
Variable `source_tables` is created and assigned inside a try-catch block. If the parser failed, the `source_tables` is not initialized, so later references will throw error: local variable 'source_tables' referenced before assignment
- initialize `source_tables` to empty array 
n/a
=> Tableau crawler throws exception when parsing [sc-21713]

poetry.lock, pyproject.toml
Power BI connector is throwing the following error:
```
2023-10-19 19:03:54:ERROR:metaphor:email-validator is not installed, run `pip install pydantic[email]`
File "pydantic/networks.py", line 578, in pydantic.networks.import_email_validator
ModuleNotFoundError: No module named 'email_validator'
```
As titled.
=> Add missing pydnatic email extra

metaphor/snowflake/config.py, pyproject.toml
10 MB still seems unreasonably large for queries.
As titled.
N/A
=> Lower the default query size limit to 512KiB

metaphor/unity_catalog/extractor.py, metaphor/unity_catalog/models.py, pyproject.toml, tests/unity_catalog/expected.json, tests/unity_catalog/test_extractor.py
The connector currently only extracts table-level descriptions but not column-level ones.
As titled.
=> Extract column description from Unity Catalog tables

metaphor/dbt/README.md, metaphor/dbt/config.py, metaphor/dbt/manifest_parser.py, metaphor/dbt/util.py, pyproject.toml, tests/dbt/data/trial_v4/results.json, tests/dbt/data/trial_v5/results.json, tests/dbt/data/trial_v6/results.json, tests/dbt/data/trial_v7/results.json, tests/dbt/data/trial_v8/results.json, tests/dbt/data/trial_v9/results.json, tests/dbt/test_util.py
Enables assigning ownership to dbt model's virtual views, or both the virtual view and the dataset itself.
Tracked by [SC20587](https://app.shortcut.com/metaphor-data/story/20587)
- Added a config field for meta_ownerships:
```yaml
meta_ownerships:
- meta_key: owner
ownership_type: Data Steward
assignment_target: materialized_table # assigns the owner to either "materialized_table" (the dataset), "dbt_model" (the virtual view), or "both". Default is the materialized table.
```
- Added support for parsing string values in dbt model's meta field, such that a string value containing commas will be parsed as a sequence of string values
Tested with the newly added config, the ownership information was added correctly.
=> Add `OwnershipAssignment` to dbt `VirtualView`

metaphor/common/dataclass.py, pyproject.toml
Because I am wary of seeing
```
UserWarning: Valid config keys have changed in V2:
* 'validate_all' has been renamed to 'validate_default'
```
Use properly typed `ConfigDict` instead of custom class as dataclass configs.
Ran unit tests.
=> Use v2 `ConfigDict` instead of custom class for pydantic dataclasses

metaphor/snowflake/extractor.py, pyproject.toml
It's possible to have email address as a Snowflake user ID. Query issued by these users should have the `email` address field set instead of `user_id`. 
As titled.
Verified against a production instance. Example:
```
...
{
"_id": "SNOWFLAKE:01b01a65-0603-c12b-0029-c00304f93dae",
"account": "metaphor-dev",
"bytesRead": 0.0,
"bytesWritten": 0.0,
"cost": 0.0,
"duration": 0.326,
"email": "mars@metaphor.io",
"platform": "SNOWFLAKE",
"queryId": "01b01a65-0603-c12b-0029-c00304f93dae",
"rowsWritten": 0.0,
"sources":
[],
"sql": "GET '@~/worksheet_data/metadata' 'file:///'",
"sqlHash": "70496b3935c36ec0fc4027d9a26d1dd5",
"startTime": "2023-11-04T03:49:52.298000-08:00",
"targets":
[]
},
...
```
=> Handle email-based Snowflake user ID in query logs

tests/unity_catalog/test_utils.py
The unity catalog unit test contains a `datetime.fromtimestamp` call without specifying timezone, thus causing the test to fail when run locally. This PR addresses that.
Add timezone to `fromtimestamp`.
Ran unit test locally.
=> Provide timezone for `fromtimestamp` in unity catalog test_utils

metaphor/common/logger.py, poetry.lock, pyproject.toml, tests/common/test_logger.py
Connectors can crash when writing a debug file using an invalid file name, e.g.
```
2023-11-07 14:28:53:ERROR:metaphor:[Errno 2] No such file or directory: '/tmp/tmpar3lvod6/<invalid_filename>.json'
File "/usr/local/lib/python3.8/site-packages/metaphor/common/runner.py", line 50, in run_connector
entities = connector_func()
File "/usr/local/lib/python3.8/site-packages/metaphor/common/base_extractor.py", line 32, in run_async
File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
File "/usr/local/lib/python3.8/site-packages/metaphor/unity_catalog/extractor.py", …
```
=> Sanitize debug log file names to avoid crashing

metaphor/dbt/artifact_parser.py, metaphor/dbt/util.py, pyproject.toml, tests/dbt/data/metaphor_subscriptions_v10/results.json
`DataMonitorTarget.dataset` is a stringified `EntityId`, not a normalized name.
Removed unnecessary assignment for `DataMonitorTarget.dataset`.
Fixed unit test.
=> `DataMonitorTarget.dataset` does not need to be specified

metaphor/unity_catalog/models.py, pyproject.toml, tests/unity_catalog/test_models.py
Removed `DataSourceFormat`, which is no longer used once we switched to `databricks-sdk-py`.
No need.
=> Remove unused UnityCatalog dataclass

metaphor/snowflake/README.md, metaphor/snowflake/extractor.py, poetry.lock, pyproject.toml
Running snowflake connector on macOS  returns the following error:
```
/<redacted>/python3.9/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (14.0.1), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
```
- Update `snowflake-connector-python` to the latest version and fix `pyarrow` to `10.0.1`
- Add additional logging for Streams
- Add required Snowflake Streams privileges to README
=> Fix incompatible pyarrow version for snowflake connector

metaphor/dbt/artifact_parser.py, metaphor/dbt/util.py, pyproject.toml, tests/dbt/data/jaffle_v10/results.json, tests/dbt/data/metaphor_subscriptions_v10/manifest.json, tests/dbt/data/metaphor_subscriptions_v10/results.json, tests/dbt/data/metaphor_subscriptions_v10/run_results.json
We didn't set `MonitorTarget.dataset` so the table level DQ status will be removed because all fields are none.
- Use `attatched_node` if possible because discovered that `test.depends_on[0]` is not always the real dataset.
- Set `MonitorTatget.dataset` to resolve the problem
Update unit tests
=> Get dbt table level test result

metaphor/dbt/artifact_parser.py, metaphor/looker/lookml_parser.py, metaphor/tableau/extractor.py, pyproject.toml, tests/dbt/data/jaffle_v10/results.json, tests/dbt/data/metaphor_subscriptions_v10/results.json, tests/dbt/data/trial_v4/results.json, tests/dbt/data/trial_v5/results.json, tests/dbt/data/trial_v6/results.json, tests/dbt/data/trial_v7/results.json, tests/dbt/data/trial_v8/results.json, tests/dbt/data/trial_v9/results.json, tests/looker/test_lookml_parser.py, tests/tableau/expected.json
All my homies want source info in entityUpstream instead of in the platform specific fields.
Added entityUpstream field for all virtual views.
Unit test.
=> All virtual view crawlers emit entityUpstream

metaphor/tableau/README.md, metaphor/tableau/config.py, metaphor/tableau/extractor.py, pyproject.toml, tests/power_bi/test_power_bi_client.py, tests/tableau/config_extra_excluded_projects.yml, tests/tableau/config_include_personal_space.yml, tests/tableau/test_config.py, tests/tableau/test_extractor.py
The `Personal Space` project should be ignored by the connector by default. Also, it would be nice to add configurations to allow users to either exclude other projects, or include `Personal Space`.
Ref: https://help.tableau.com/current/pro/desktop/en-us/personal_space.htm
- Added config values.
- Updated README.
- Modified unit test.
- Tested locally.
- Unit test.
=> Add Tableau config for ignoring certain projects

metaphor/unity_catalog/profile/extractor.py, pyproject.toml, tests/unity_catalog/profile/expected.json, tests/unity_catalog/profile/test_extractor.py
It is also possible to get column stats from databricks sql client, best if we can support that.
Parses column stats with databricks sql client, and stores the info in `Dataset.field_statistics`.
=> Add column stats to unity catalog profiler

metaphor/dbt/artifact_parser.py, poetry.lock, pyproject.toml, tests/dbt/data/jaffle_v11/manifest.json
The manifest contains null valued field under `metrics` that's not defined in json schema, causing pydantic validation error.
- manually strip the undefined field from manifest.json
tested against manifest generated from dbt cloud 1.7
=> dbt crawler failing on qa demo [sc-23181]

metaphor/monte_carlo/extractor.py, pyproject.toml, tests/monte_carlo/expected.json, tests/monte_carlo/test_extractor.py
[SC-23616]
`MISCONFIGURED` in Monte Carlo could mean an actual configuration issue or insufficient data for prediction. In either case, it shouldn't be treated as an `ERROR`.
As titled.
Manually ran against a production instance.
=> Map MC's MISCONFIGURED status to UNKNOWN

metaphor/dbt/artifact_parser.py, metaphor/dbt/cloud/README.md, metaphor/dbt/cloud/client.py, metaphor/dbt/cloud/config.py, metaphor/dbt/cloud/extractor.py, metaphor/dbt/extractor.py, pyproject.toml, tests/dbt/cloud/test_client.py, tests/dbt/cloud/test_extractor.py, tests/dbt/data/ride_share/expected.json, tests/dbt/data/ride_share/manifest.json, tests/dbt/data/ride_share/run_results.json
To filter collected dbt jobs by their environment ID.
If user specified a list of environment ids to include, and the crawler sees a job with an environment id not in that list, then the job will be ignored.
- Unit test.
- Tested locally.
=> Filter dbt cloud jobs by environment id

metaphor/dbt/artifact_parser.py, pyproject.toml
The dbt connector fails with the following error when encountering tests that reference inactive (disabled) dbt models:
```
2024-01-18 10:13:38:ERROR:metaphor:Failed to parse artifacts for run ID = <reacted>, project ID = <reacted>, job ID = <reacted>
File "/Users/marslan/Metaphor/connectors/metaphor/dbt/cloud/extractor.py", line 91, in _extract_last_run
entities = await DbtExtractor(
File "/Users/marslan/Metaphor/connectors/metaphor/dbt/extractor.py", line 71, in extract
artifact_parser.parse(manifest_json, run_results_json)
File "/Users/marslan/Metaphor/connectors/metaphor/dbt/artifact_parser.py", line 364, in parse
self.parse_manifest(manifest_json, run_results)
File "/Users/marslan/Metaphor/connectors/metaphor/dbt/artifact_parser.py", line 497, in …
```
=> Skip parsing tests that reference inactive models

metaphor/snowflake/extractor.py, pyproject.toml, tests/snowflake/test_extractor.py
Need to make sure the key prefix for tag is the entire name, i.e. if it's a database tag, then the tag's key prefix should represent the entire database name instead of a prefix of the name.
Fix the aforementioned bug.
=> Add delimiter after key prefix when matching dataset keys

metaphor/tableau/query.py, pyproject.toml
https://github.com/MetaphorData/connectors/pull/766 made the core logic compatible with older versions of Tableau server but forgot to remove the offending field from the GraphQL query.
As titled.
=> Drop projectLuid from Tableau GraphQL query

.github/workflows/cd.yml
https://github.com/MetaphorData/connectors/pull/770 locked down the token permission and led to the following [error](https://github.com/MetaphorData/connectors/actions/runs/7706967646/job/21003381772):
```
RequestError [HttpError]: Resource not accessible by integration
at /home/runner/work/_actions/actions/github-script/v5/dist/index.js:4560:21
at processTicksAndRejections (node:internal/process/task_queues:96:5) {
status: 403,
```
=> Fix CD by giving it the correct permissions

metaphor/common/base_extractor.py, metaphor/common/event_util.py, metaphor/common/file_sink.py, metaphor/common/runner.py, metaphor/common/sink.py, metaphor/snowflake/extractor.py, pyproject.toml, tests/common/test_file_sink.py, tests/snowflake/test_extractor.py
It is possible for large amount of query logs to exhaust crawler's memory in the serverless instance. To mitigate this issue, I created a route for connectors to extract query logs as an iterator, and the corresponding method in `FileSink` to export those parsed query logs one by one. The chunking is taken care of in `FileSink`.
Note: the boundary check for `batch_size_bytes` is not 100% precise, but should be close enough.
- Implemented `collect_query_logs` method in `BaseExtractor` and `SnowflakeExtractor`
- Implemented `QueryLogSink` in `file_sink.py` to support piping an iterator of `QueryLog` to files.
- Modified unit test.
Tested on personal dev env with Snowflake crawler:
crawler output:
ingestion logs:
Notice the `query_logs-0.json` is correctly ingested.
=> [sc-24431] Create generator based extract method specifically for `QueryLogs`

metaphor/notion/extractor.py, poetry.lock, pyproject.toml
[SC24473](https://app.shortcut.com/metaphor-data/story/24473/implement-notion-api-rate-limiting-higher-timeout)
After a couple title retrieval fails, the crawler fails to make any subsequent connections to the Notion API. Increasing the timeout on title seems to allow for enough time for a successful re-connection after failures. 
Changes the _get_title timeout from 5 to 15 seconds.
Tested locally and works with the test Notion instance.
=> Raised timeout to 15 seconds

metaphor/common/file_sink.py, metaphor/common/runner.py, pyproject.toml, tests/common/test_runner.py
Since we've separated the query logs dump logic from the others, we need to also include the query log MCE count in `CrawlerRunMetadata`.
Added `total_mces_wrote` to `QueryLogSink`, and add that to `CrawlerRunMetadata.entity_count`.
Unit test.
=> [sc-24626] Add query logs MCE count to CrawlerRunMetadata

metaphor/snowflake/extractor.py, pyproject.toml
[SHOW STREMS](https://docs.snowflake.com/en/sql-reference/sql/show-streams) can throw the following exception and stops the entire connector if the user doesn't have the correct privilege:
```
SQL compilation error:
Schema '<redacted>' does not exist or not authorized.
File "/usr/local/lib/python3.8/site-packages/metaphor/common/runner.py", line 51, in run_connector
entities = connector.run_async()
File "/usr/local/lib/python3.8/site-packages/metaphor/common/base_extractor.py", line 39, in run_async
File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
File …
```
=> Handle Snowflake SHOW STREAMS failures gracefully

metaphor/common/runner.py, pyproject.toml
The end time of the crawler run has to be collected after query logs are collected.
Fixed the logic in `runner.py` to address this bug.
=> [sc-24768] Generate CrawlerRunMetadata at the end of the run, after query logs are collected

metaphor/s3/README.md, metaphor/s3/config.py, metaphor/s3/extractor.py, pyproject.toml
Endpoint URL is not needed for AWS S3.
- Moved `endpoint_url` config value to optional.
- Remove unnecessary `list_buckets` call.
Tested locallly.
=> [sc-24788] Modify S3 crawler to not require endpoint url

poetry.lock, pyproject.toml
metaphor-models 0.31 is a breaking change that removed `upstream` field for dataset and dashboard
- update metaphor-models version
all unit tests passed
=> bump metaphor-models version

metaphor/redshift/extractor.py, pyproject.toml, tests/redshift/test_extractor.py
Redshift crawler is settings the output asset platform type to `POSTGRES` instead of `REDSHIFT`.
Fix the typo made in https://github.com/MetaphorData/connectors/pull/724 and add a rudimentary test to verify.
Before:
```
[{"dataset": {"logicalId": {"name": "metaphor.private.sample_sales_records2", "platform": "POSTGRESQL"}, ...]
```
After:
```
[{"dataset": {"logicalId": {"name": "metaphor.private.sample_sales_records2", "platform": "REDSHIFT"}, ...]
```
=> Output the correct platform for redshift crawler

metaphor/bigquery/extractor.py, pyproject.toml, tests/bigquery/query_logs.json, tests/bigquery/sample_log.json
When encountering queries issued by a [GCP service account](https://cloud.google.com/compute/docs/access/service-accounts), we should identify it as such by setting the `user_id` field instead of `email`.
As titled.
=> Set user_id field in BigQuery query log for service accounts

metaphor/snowflake/extractor.py, pyproject.toml, tests/snowflake/test_extractor.py
Some of the Snowflake tables are missing refresh time because the loop to get table info stops iterating if there is an error in `get_table_info`.
- Reduce query compilation error ( skip secure view )
- Add try-catch in the for loop
- Partition table by schema because it's likely we can't get table information under a certain schema.
- Add tests
Run crawler against testing Snowflake account
=> refresh time missing for snowflake tables

examples/custom_dashboard.py, examples/custom_dq.py, examples/custom_lineage.py, metaphor/common/cli.py, metaphor/common/runner.py, pyproject.toml, tests/common/test_runner.py
We can't initialize the class before entering `run_cli` or we can't catch the exceptions
- Revert the change to passing a function to `run_cli`
- Add unit tests
- Modify snowflake connector to throw exception locally and able to get the output files
=> Exceptions thrown in crawler constructors not handled gracefully

metaphor/snowflake/extractor.py, metaphor/snowflake/lineage/extractor.py, pyproject.toml
It takes an exceedingly long time (> 1.5 hours) to run the Snowflake lineage crawler against large `Snowflake.AccountUnage.QUERY_HISTORY` views.
Turns out that [similar to `ACCESS_HISTORY`](https://docs.snowflake.com/en/user-guide/access-history#querying-the-access-history-view), we must also specify a filter against `START_TIME` in order to query `QUERY_HISTORY` efficiently. 
- Specify the `START_TIME` filter for `QUERY_HISTORY` and use inner JOIN when joining with  `ACCESS_HISTORY` in Snowflake lineage connector
- Qualify the filters in the base Snowflake connector to avoid confusion.
Verified that the MCEs before & after the changes are identical. Observed an order of magnitude improvement in performance:
Before:
```
Ended running with RunStatus.SUCCESS at 2024-03-14 08:54:28.949943, …
```
=> Optimize queries used in Snowflake lineage connector

metaphor/common/runner.py, pyproject.toml
Currently no `log.zip` file is generated when an invalid crawler config is supplied. 
Fix the bug introduced in https://github.com/MetaphorData/connectors/pull/794.
Verified that log.zip is generated for invalid configs:
=> Output log.zip for invalid connector configs

metaphor/postgresql/profile/extractor.py, pyproject.toml, tests/postgresql/profile/test_extractor.py
Null count = `COUNT(1) - COUNT(column)`, not `COUNT(column)`.
Fix the above bug.
=> bugfix: redshift profiler null count should be `COUNT(1) - COUNT(column)`

metaphor/redshift/lineage/extractor.py, metaphor/redshift/profile/extractor.py, pyproject.toml
Similar to https://github.com/MetaphorData/connectors/pull/792, but for redshift profiler.
As titled. The changes to `redshift.lineage` connector aren't necessary but were still added just in case. 
Manually verified the MCE output against a production instance.
=> Output the correct data platform for Redshift profiler

metaphor/unity_catalog/extractor.py, pyproject.toml
The line is rendered useless by https://github.com/MetaphorData/connectors/pull/775.
As titled. 
While flake8 has a [rule](https://www.flake8rules.com/rules/F841.html) to detect unused local variables, it failed to do so in this case because `tag` was reassigned to another value a few lines down. Tried [pylint](https://pylint.readthedocs.io/en/latest/) and it too failed to detect.
=> Remove unused code

metaphor/dbt/artifact_parser.py, metaphor/dbt/extractor.py, pyproject.toml, tests/dbt/data/ride_share/manifest.json
Some dbt models are imported using [project-dependencies](https://docs.getdbt.com/docs/collaborate/govern/project-dependencies). That means the dbt crawler may generate two entities with the same logical ID but we should not generate the imported one.
- Filter models the `package_name` is not equal to `project_name` if `project_name` is set.
Add test case.
=> User get notifications when dbt crawler run

metaphor/snowflake/README.md, metaphor/snowflake/extractor.py, pyproject.toml, tests/snowflake/test_extractor.py
The `SHOW SHARES` will return all inbound/outbound shared databases, also including the inbound shared databases that have not been accepted by the receiver.
- Not use `SHOW SHARES`, and use only `information_schema` instead. This does require the access to the imported databases to be granted to the metaphor role.
tested on metaphor snowflake instance.
=> Not use SHOW SHARES [sc-25711]

metaphor/looker/lookml_parser.py, pyproject.toml, tests/looker/test_lookml_parser.py
Instead of putting the base view of a looker view in `query` field, we should treat is as the upstream of the looker view.
- convert the base view to virtual view id and put it in the upstream of the looker view
unit tests
tested against looker instance
=> Looker SQL server side parsing [sc-25997]

metaphor/metabase/README.md, metaphor/metabase/config.py, metaphor/metabase/extractor.py, pyproject.toml, tests/metabase/config.yml, tests/metabase/test_config.py, tests/metabase/test_extractor.py
Metabase does not know a SQL query's default schema on Snowflake, RedShift and BigQuery. This causes our lineage parser unable to locate the correct upstream dataset, and in some instances the lineage parser to straight up fail.
Since Metabase API does not provide us with the default schema, best we can do is to specify this in the configs.
- Add config for `database_defaults`, which contains `default_schema`
- Use a database's `default_schema` when parsing database info from metabase api
- Unit test
- Tested locally
=> [sc-25976] Add `database_defaults` to Metabase crawler config

metaphor/dbt/artifact_parser.py, metaphor/looker/lookml_parser.py, metaphor/snowflake/extractor.py, metaphor/tableau/extractor.py, metaphor/thought_spot/extractor.py, metaphor/unity_catalog/extractor.py, pyproject.toml, tests/looker/test_lookml_parser.py, tests/snowflake/test_extractor.py, tests/thought_spot/expected.json
Since we can't unset aspects in ingester, we need to give `systemTags` a default value of `SystemTags(tags=[])`, so that when the newly created MCE gets ingested, entities that no longer have system tags would get updated correctly.
Add default value for system tags.
Modified unit test.
=> [sc-26028] Set default value for entity system tags

metaphor/snowflake/extractor.py, metaphor/snowflake/utils.py, pyproject.toml, tests/snowflake/test_extractor.py, tests/snowflake/test_utils.py
Instead of deduping system tags, what we need to do is to properly override inherited system tags: 
>It is possible to override an inherited tag on a given object. For example, if a table column inherits the tag named cost_center with a string value called sales, the tag can be updated with a more specific tag string value such as sales_na, to specify the North America sales cost center. Additionally, a new tag can be applied to the table column. Use an [ALTER TABLE … ALTER COLUMN](https://docs.snowflake.com/en/sql-reference/sql/alter-table-column) statement to update the tag string value on the column and to set one or more additional tags on a column.
https://docs.snowflake.com/en/user-guide/object-tagging#tag-lineage
- Refactor
- Implement logic for overriding inherited system tags.
- …
=> [sc-26028] Override inherited system tags

poetry.lock, pyproject.toml
To prevent emitting `lookerView.query.referenecedView` field. The latest parser should have stopped using that field already.
- bump metaphor-models version
unit tests pass
=> bump models version

metaphor/snowflake/extractor.py, poetry.lock, pyproject.toml
Sometimes shared DB are no longer accessible to the user, resulting in SQL query errors. Didn't find a good way of knowing the accessibility of a database before query.
- Log the SQL exception instead of the throwing errors
tested against metaphor snowflake, will verify the effect after deployment to customer
=> Handle no longer available Snowflake shared [sc-25949]

metaphor/unity_catalog/README.md, metaphor/unity_catalog/config.py, metaphor/unity_catalog/extractor.py, metaphor/unity_catalog/profile/README.md, metaphor/unity_catalog/profile/extractor.py, metaphor/unity_catalog/utils.py, tests/unity_catalog/config.yml, tests/unity_catalog/expected.json, tests/unity_catalog/profile/test_extractor.py, tests/unity_catalog/test_config.py, tests/unity_catalog/test_extractor.py
Refactor the config to support both Databricks cluster & SQL warehouse and to better match Unity Catalog's terminology: https://docs.databricks.com/en/integrations/compute-details.html
- Replace `host`, `cluster_path`, and `warehouse_id` with `hostname` & `http_path`.
- Update README files
Verified against a production instance using the new config fields.
=> Refactor config for Unity Catalog connector

docs/migration.md, pyproject.toml
To kick of 0.14 with the breaking changes in https://github.com/MetaphorData/connectors/issues/621.
As titled. Also added migration guide.
N/A
=> Bump up to 0.14

metaphor/snowflake/lineage/extractor.py, pyproject.toml
This is so that we don't collapse the views along the lineage. 
Also includes `STREAM` in the object domains filter.
- Use `DIRECT_OBJECTS_ACCESSED` instead of `BASE_OBJECTS_ACCESSED` in `ACCESS_HISTORY`
- Includes `STREAM` in the object domains filter.
- SnowflakeLineage crawler run locally
=> [sc-26422] Use `DIRECT_OBJECTS_ACCESSED` instead of `BASE_OBJECTS_ACCESSED` in `ACCESS_HISTORY`

metaphor/dbt/artifact_parser.py, metaphor/dbt/generated/dbt_manifest_v12.py, pyproject.toml, tests/dbt/data/jaffle_v12/manifest.json, tests/dbt/data/jaffle_v12/run_results.json
When processing `manifest.json` file generated by dbt 1.8.0, the connector throws parsing errors like these:
```
nodes.`model.jaffle_shop.stg_locations`.AnalysisNode.resource_type
Input should be 'analysis' [type=literal_error, input_value='model', input_type=str]
For further information visit https://errors.pydantic.dev/2.6/v/literal_error
nodes.`model.jaffle_shop.stg_locations`.AnalysisNode.access
Extra inputs are not permitted [type=extra_forbidden, input_value='protected', input_type=str]
For further information visit https://errors.pydantic.dev/2.6/v/extra_forbidden
```
Turns out that some breaking changes have been introduced to the schema between dbt 1.8.0a1 & 1.8.0. 
Re-generated the data model using the [latest v12 JSON schema](https://schemas.getdbt.com/dbt/manifest/v12.json) …
=> Fix dbt 1.8 manifest parsing errors

metaphor/dbt/artifact_parser.py, metaphor/dbt/config.py, metaphor/dbt/util.py, pyproject.toml, tests/dbt/data/ride_share/expected.json, tests/dbt/data/ride_share/manifest.json, tests/dbt/data/ride_share/run_results.json, tests/dbt/test_extractor.py, tests/dbt/test_util.py
We're moving away from treating tags declared in dbt's [meta](https://docs.getdbt.com/reference/resource-configs/meta) field as Metaphor's governance tag. Instead, they should be treated just as additional "dbt tags".
- Add `meta_key_tags` to dbt connector config to point to the key name in `meta` field where the additional dbt tags are defined.
- Combining and deduping additional dbt tags defined in `meta` with the [tags](https://docs.getdbt.com/reference/resource-configs/tags) defined at the model level into `SystemTags` in MCE.
- Rename `get_tags_from_meta` to `get_metaphor_tags_from_meta` to disambiguate.
TODOs in follow-up PRs:
- Migrate Metaphor ownerships declared in `meta` into `SystemContacts`.
- Update models to support column-level tags.
> Note: …
=> Allow assigning additional dbt tags via meta field

metaphor/tableau/config.py, metaphor/tableau/extractor.py, metaphor/tableau/graphql_utils.py, metaphor/tableau/workbook.py, pyproject.toml, tests/tableau/config.yml, tests/tableau/test_config.py, tests/tableau/test_workbook.py
Currently we fetch up to 50 nodes when paginating through GraphQL connections in [Tableau Metadata API](https://help.tableau.com/current/api/metadata_api/en-us/index.html). However, the API can return partial/invalid data with a [NODE_LIMIT_EXCEEDED](https://help.tableau.com/current/api/metadata_api/en-us/docs/meta_api_errors.html#:~:text=may%20be%20returned.-,NODE_LIMIT_EXCEEDED,-Warning) error when the number of total nodes exceeds server's [configuration](https://help.tableau.com/current/server/en-us/dm_catalog_enable.htm#:~:text=the%20following%20message%3A-,NODE_LIMIT_EXCEEDED,-To%20resolve%20this).
Make the hard-coded batch size configurable and lower the default to 20.
=> Make the Tableau GraphQL pagination size configurable

metaphor/common/utils.py, metaphor/sharepoint/extractor.py, metaphor/static_web/extractor.py, metaphor/static_web/utils.py, pyproject.toml, tests/common/test_utils.py, tests/static_web/test_extractor.py, tests/static_web/test_utils.py
The `text_from_HTML` util function depends on the rather heavy `beautifulsoup` library. Since we don't expect it to be used by connectors other than `static_web` & `sharepoint`, it makes sense to move it out of `metaphor.common.utils`. 
- Move `text_from_HTML` to from `metaphor.common.utils` to`metaphor.static_web.util`, along with `title_from_HTML`.
- Refactor `static_web` & `sharepoint` connectors to make use of these util functions.
Unit tests.
=> Move text_from_HTML out of metaphor.common

metaphor/dbt/artifact_parser.py, metaphor/dbt/cloud/README.md, metaphor/dbt/cloud/config.py, metaphor/dbt/cloud/discovery_api.py, metaphor/dbt/cloud/extractor.py, metaphor/dbt/extractor.py, metaphor/dbt/util.py, pyproject.toml, tests/dbt/cloud/test_discovery_api.py, tests/dbt/cloud/test_extractor.py
It is possible for `run_results.json` to not have the results of previously run tests. Since dbt cloud provides the discovery API for metadata discovery, we should use that instead of only relying on `run_results.json`. We should not overwrite the data monitors collected by DbtCoreExtractor though; the monitors we collected via discovery API are only added to the collected entities if it does not exist before. 
- Added logic in `dbt.cloud.DbtCloudExtractor` to extend core's parsed entities with test results parsed from discovery api.
- Crawler run locally, seems normal
- Successfully ingested data monitors into andy.dev.metaphor.io.
=> [sc-26791][sc-26630] Parse test run results via discovery api, and fill in `DataMonitor.last_run` for dbt data monitors

metaphor/common/docs/output.md, metaphor/common/file_sink.py, metaphor/common/query_history.py, pyproject.toml, tests/common/test_file_sink.py
Ovative's lineage parser is timing out. Currently the lineage parser is able to handle individual queries, but the lineage lambda actually writes all parsed lineage into MongoDB one *all* queries have been parsed, which causes a single batch that contains multiple very long queries not being written to MongoDB at all.
One way to solve this is to reduce the number of query logs in a single batch file. Before it's hard-coded to 100,  but we probably want to expose this config value and try out different possible values to see if that'll fix the issue.
Exposed `query_log_batch_size_count` in `FileSinkConfig`. Set it like
```yaml
output:
file:
directory: ...
query_log_batch_size_count: ... /// Default is 100
```
Tested locally, verified that with different `query_log_batch_size_count` the …
=> [sc-26934] Expose `query_log_batch_size_count` as a config value

metaphor/snowflake/extractor.py, pyproject.toml, tests/snowflake/test_extractor.py
There is a typo when converting nanosecond to second timestamp...
- Fix the typo
- Update test cases, we are not using meaningful timestamp here.
- Check unit tests
- Check output MCEs
=> Snowflake last update time is not correct

metaphor/redshift/access_event.py, pyproject.toml
The Redshift crawler could fail while collecting query logs if there are a lot of queries in the cluster:
```
Invalid operation: Result size exceeds LISTAGG limit
```
To avoid that, we split `stl_querytext` with `OVER` clause before doing `LISTAGG`, so that we're doing `LISTAGG` on single queries instead of the whole column.
Reference: https://thedataguy.in/redshift-reconstructing-sql-from-sql-querytext/
- Split up `stl_querytext` table with OVER before aggregating query text rows
Run the updated query against our own Redshift cluster. Our cluster does not have much going on though, so it's hard to say how this change will impact the performance in production.
=> [sc-27082] Split up `stl_querytext` table with OVER before aggregating query text rows

metaphor/metabase/README.md, metaphor/metabase/config.py, metaphor/metabase/extractor.py, pyproject.toml, tests/metabase/config_exclude_paths.yml, tests/metabase/test_config.py
To be able to filter Metabase assets based on collection path
- add asset_filter in metabase config
- support filtering assets based on collection path (directory)
tested against Metaphor instance.
=> add exclude options to Metabase crawler [sc-27133]

metaphor/looker/config.py, metaphor/looker/extractor.py, metaphor/looker/folder.py, metaphor/looker/lookml_parser.py, pyproject.toml, tests/looker/config2.yml, tests/looker/expected.json, tests/looker/test_config.py, tests/looker/test_extractor.py, tests/looker/test_folder.py
Looker dashboards are [organized using folders](https://cloud.google.com/looker/docs/organizing-spaces), and they expect the asset hierarchy to match the folder structure.
- Set `AssetStructure` for dashboards based on their Looker folder path.
- Add `include_personal_folders` config to allow explicit inclusion of dashboards in personal folders. 
- Extend the default Looker API timeout to 5 mins as [all_dashboards](https://developers.looker.com/api/explorer/4.0/methods/Dashboard/all_dashboards) can take that long to return if there were thousands of dashboards.
=> Support Looker folder structure

metaphor/redshift/access_event.py, pyproject.toml
The `LISTAGG` expression was failing because there are SQL queries that are longer than 65535 characters. These really long queries are generated by things like DBT or Hex, and very likely not have any lineage in them.
Instead of trying to concatenate these queries in crawler code, it is perhaps better to just ignore them.
This PR stems from a Slack conversation with BioRender. _**This PR should not be merged until someone else gives the green light!**_
Filter out the queries that go beyond 65535 characters.
Tested on our own Redshift cluster:
- Import a large dataset
- Do a bunch of selects
- Set the size limit to 100
- Run the modified query in console
- Observe there are only a few queries that are below the size limit
=> [sc-27082] Filter out the query texts that go beyond the size limit

metaphor/redshift/access_event.py, pyproject.toml
I don't know why it is still failing, I guess it has to do with the order of execution within the entire SELECT statement?
Anyway I think the safest approach is to split the query collection into multiple stages:
1. Get the length of the queries
2. Filter out the queries that are too long
3. Do the LISTAGG
We then combine the queries back into the main SELECT.
Fix the access event query.
- Tested against our own redshift cluster.
- Tested on production:
=> [sc-27082] Do the query text concatenation as CTE

metaphor/unity_catalog/profile/extractor.py, pyproject.toml, tests/unity_catalog/profile/expected.json, tests/unity_catalog/profile/test_extractor.py
Because the the updated time is moved to `SourceInfo` so we need to remove these lines of code. We can't fill the `sourceInfo.lastUpdated` because the two crawler will overwrite this aspect. The UC connector already has the update time of tables so I think it's safe to remove it from the profile connector
- Stop filling `statistics.lastUpdated`
Unit tests
=> Should not fill out last update time in the UC profile crawler

metaphor/bigquery/profile/extractor.py, metaphor/common/fieldpath.py, metaphor/dbt/util.py, metaphor/glue/extractor.py, metaphor/hive/extractor.py, metaphor/kafka/schema_parsers/avro_parser.py, metaphor/kafka/schema_parsers/protobuf_parser.py, metaphor/kafka/schema_parsers/utils.py, metaphor/mssql/extractor.py, metaphor/mysql/extractor.py, metaphor/postgresql/extractor.py, metaphor/postgresql/profile/extractor.py, metaphor/snowflake/extractor.py, metaphor/trino/extractor.py, metaphor/unity_catalog/models.py, pyproject.toml, tests/common/test_fieldpath.py, tests/hive/expected.json, tests/hive/test_extractor.py, tests/kafka/schema_parsers/account_event/expected.json, tests/kafka/schema_parsers/complex/expected.json, tests/kafka/schema_parsers/nested_arrays/expected.json, tests/kafka/schema_parsers/simple_union/expected.json, tests/kafka/schema_parsers/union/expected.json, tests/kafka/test_schema_resolver.py, tests/trino/expected.json
to support more efficient regex matching on column path
- all crawlers emit column `fieldpath` as lowercase, and use `fieldName` to store the original string
tested various crawlers against metaphor instances
=> All crawlers emit normalized fieldPath [sc-27452]

metaphor/common/docs/process_query.md, metaphor/common/process_query/config.py, metaphor/common/process_query/process_query.py, metaphor/snowflake/extractor.py, pyproject.toml, tests/common/process_query/test_process_query.py
`INSERT INTO ... VALUES` means we're inserting static, explicit values into a table. There's no lineage for these queries, so we should just exclude them from the crawled query logs.
Allow ignoring `INSERT INTO ... VALUES` queries. By default these are ignored.
In our own environment there's no `INSERT INTO ... VALUES` query, so can't really test the crawler...
=> [sc-27536] Allow ignoring `INSERT INTO ... VALUES` queries

metaphor/unity_catalog/README.md, metaphor/unity_catalog/extractor.py, metaphor/unity_catalog/models.py, metaphor/unity_catalog/utils.py, pyproject.toml, tests/unity_catalog/expected.json, tests/unity_catalog/mocks.py, tests/unity_catalog/profile/test_extractor.py, tests/unity_catalog/test_extractor.py, tests/unity_catalog/test_models.py, tests/unity_catalog/test_utils.py
Using the [REST API](https://docs.databricks.com/en/data-governance/unity-catalog/data-lineage.html#retrieve-table-lineage) to extract table & column lineage turns out to be highly inefficient and can take an unacceptably long time for large number of tables & columns. It seems that the recommended way is to use [Lineage system tables](https://docs.databricks.com/en/admin/system-tables/lineage.html) instead.
- Refactor `list_table_lineage` & `list_column_lineage` util functions to batch fetch lineage information from the system tables at the schema level. 
- Add logging to help monitor the crawler progress.
- Factor out common SQL connection mocking in tests to a reusable function.
Note: The change broke the support for volume lineage, which will be restored in a follow-up PR.
Verified …
=> Extract Unity Catalog table & column lineage from system tables

metaphor/unity_catalog/config.py, metaphor/unity_catalog/extractor.py, pyproject.toml
Fetching 100 query logs at a time is rather inefficient.
- Bumpt the default batch size to 1000 (max allowed by the API)
- Add logging to improve progress monitoring
Tested against a production instance with 250k+ queries. Took < 4 mins.
=> Bump up default batch size for Unity Catalog query log fetching

metaphor/unity_catalog/config.py, metaphor/unity_catalog/profile/README.md, metaphor/unity_catalog/profile/extractor.py, pyproject.toml
To speed up the UC profile connector. Getting a table's stat takes about 5 seconds, not investigating too deep on the UC side. We can take the first step by executing the query in parallel.
Run the profile function in threads.
Verified against prod env. 5x improvement with 10 threads.
=> Improve unity catalog profiler speed

metaphor/unity_catalog/extractor.py, metaphor/unity_catalog/utils.py, pyproject.toml, tests/unity_catalog/expected.json, tests/unity_catalog/test_extractor.py, tests/unity_catalog/test_utils.py
If a Unity Catalog table is owned by a group, the [API](https://docs.databricks.com/api/workspace/tables/list) will automatically resolve the group's name. However, if the table is owned by a service principal, the API returns its [application ID](https://docs.databricks.com/en/admin/users-groups/service-principals.html) instead. 
Use the [API](https://docs.databricks.com/api/workspace/serviceprincipals/list) to build a list of service principals and resolve the application ID to the corresponding display name when processing the ownership info.
=> Resolve service principal owners to their display names

metaphor/common/sql/table_level_lineage/table.py, metaphor/unity_catalog/utils.py, pyproject.toml, tests/unity_catalog/test_utils.py
`QueriedDataset(db="", schema="", table="something")` causes the MCE validation to fail in our server application.
If a dataset isn't fully qualified, it is not an actually existing dataset. We'll just drop those from the TLL.
- Drop partially qualified dataset found during UC TLL.
Modified unit test.
=> bugfix: Drop partially qualified dataset found during UC TLL

metaphor/unity_catalog/profile/extractor.py, pyproject.toml
Unity Catalog profiler can output INF in MCEs, causing validation errors.
As titled.
=> Use safe_float in UC profiler to avoid outputting INF in MCEs

metaphor/unity_catalog/profile/extractor.py, metaphor/unity_catalog/utils.py, pyproject.toml
We try to format `None` as a float which will raise an exception in the threaded function. So the crawler stuck
- Handle the exception
- Fix the logging format
- Change the code to raise a exception in the helper function, and the crawler can finish
- Test against prod 
```
2024-07-23 14:34:31:INFO:metaphor:Ended running with RunStatus.SUCCESS at 2024-07-23 14:34:31.223049, fetched 2169 entities, took 2654.9s
```
=> Exception is not handled causing the crawler stuck 

metaphor/unity_catalog/profile/extractor.py, pyproject.toml, tests/unity_catalog/profile/expected.json, tests/unity_catalog/profile/test_extractor.py
https://github.com/MetaphorData/connectors/pull/923 didn't handle all the infinity values returned by Unity Catalog's DESCRIBE EXTENDED command, which includes the string literal "Infinity".
As titled.
Verified against a production instance and inspected the generated MCEs.
=> Handle "Infinity" values returned by DESCRIBE EXTENDED command

.github/workflows/cd.yml, .github/workflows/ci.yml
Looks like python core team has reverted the setuptools changes that broke our CICD pipeline: https://github.com/pypa/setuptools/issues/4519
If our CICD is no longer failing, might as well remove the workaround.
Remove workaround for CICD pipelines.
N/A.
=> [sc-27808] Undo workaround for CICD build

metaphor/informatica/extractor.py, pyproject.toml, tests/informatica/expected.json
The URL of INFA mappings is wrong.
- use `urljoin` to get the correct URL
Manually verified the URL in the MCE is correct.
=> Fix informatica mapping url

metaphor/bigquery/extractor.py, pyproject.toml
A [bug](https://github.com/googleapis/python-bigquery/issues/1986) in `google-cloud-bigquery` caused the bigquery connector to throw the following error  when processing some snapshot tables: 
```
File "/usr/local/lib/python3.8/site-packages/google/cloud/bigquery/table.py", line 976, in snapshot_definition
snapshot_info = SnapshotDefinition(snapshot_info)
File "/usr/local/lib/python3.8/site-packages/google/cloud/bigquery/table.py", line 1372, in __init__
self.snapshot_time = google.cloud._helpers._rfc3339_to_datetime(
File "/usr/local/lib/python3.8/site-packages/google/cloud/_helpers/__init__.py", line 252, in _rfc3339_to_datetime
return datetime.datetime.strptime(dt_str, _RFC3339_MICROS).replace(tzinfo=UTC)
File "/usr/local/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
tt, …
```
=> Add temporary try-catch to handle snapshot time parsing issue

metaphor/monte_carlo/extractor.py, pyproject.toml, tests/monte_carlo/expected.json, tests/monte_carlo/test_extractor.py
The MC connector throws the following exception when encountering a misconfigured MC monitor:
```
File "/connectors/metaphor/monte_carlo/extractor.py", line 122, in _fetch_monitors
self._parse_monitors(monitors)
File "/connectors/metaphor/monte_carlo/extractor.py", line 208, in _parse_monitors
for index, entity in enumerate(monitor["entities"]):
TypeError: 'NoneType' object is not iterable
```
Based the [API doc](https://apidocs.getmontecarlo.com/#definition-Monitor), both `entities` and `entityMcons` fields are optional.
- Skip misconfigured monitors.
- Derive the monitor severity from the `priority` field, instead of the deprecated `severity` field.
=> Handle misconfigured Monte Carlo monitors gracefully

metaphor/snowflake/README.md, metaphor/snowflake/config.py, metaphor/snowflake/extractor.py, pyproject.toml, tests/snowflake/config.yml, tests/snowflake/test_config.py
Granting access to the entire SNOWFLAKE database may not always be desirable. The connector should be able to query from a different schema that mirrors the minimally needed views (QUERY_HISTORY, ACCESS_HISTORY, TAG_REFERENCES).
As titled.
Verified against a production instance with mirrored views.
=> Add account_usage config to query a alternate schema

metaphor/tableau/extractor.py, pyproject.toml, tests/tableau/expected.json, tests/tableau/test_extractor.py
An embedded datasource is always in a workbook, so for its URL we just use the workbook's.
For embedded tableau datasources, their url should point to the workbooks containing them.
- Updated unit test.
- Ran crawler locally.
=> [sc-27547] Point embedded datasource url to workbook

metaphor/tableau/extractor.py, pyproject.toml
Should use `source_info.main_url` for embedded datasource url instead.
As titled.
=> Use source_info.main_url instead of crafting workbook url in tableau extractor

metaphor/oracle/extractor.py, pyproject.toml, tests/oracle/expected_query_logs.json
In order to make Metaphor's validator work, these properties need to be populated in the crawler.
Added `_id` and `sql_hash` properties in Oracle QueryLog.
Updated unit test.
=> [sc-28036] Oracle query logs need to have _id and sql_hash

metaphor/looker/extractor.py, metaphor/looker/folder.py, pyproject.toml, tests/looker/test_folder.py
We populate all folders as hierarchies, and we should exclude the folder that is not used. So the `include_personal_folder` flag can also be applied to the hierarchy not just the dashboard.
- Refactor `build_directory` to populate hierarchies as well
Verified no personal folder hierarchy in the output MCEs
=> Skip looker user folder hierarchies

.github/workflows/cd.yml, Dockerfile, docs/docker.md, pyproject.toml
https://github.com/MetaphorData/connectors/pull/919 improved the docker image rebuild speed but also introduced the requirement of manually generating `requirement.txt`. 
Use [multi-stage builds](https://docs.docker.com/build/building/multi-stage/) to automatically generate `requirements.txt` file as part of `docker build`.  Also updated doc & CD workflow accordingly 
```
% docker build --platform linux/amd64 -t metaphordata/connectors .
[+] Building 17.0s (19/19) FINISHED                                                                           docker:desktop-linux
=> [internal] load build definition from Dockerfile                                                                          0.0s
=> => transferring dockerfile: 669B …
```
=> Simplify docker image building process

metaphor/common/docs/process_query.md, metaphor/common/sql/process_query/config.py, metaphor/common/sql/process_query/process_query.py, pyproject.toml, tests/common/sql/process_query/test_process_query.py
It is possible to have PII values in CASE clauses. Our processor should be able to redact these.
- Added logic to redact PII values in CASE clauses.
- Unit test.
- Added config value.
- Updated readme.
=> [sc-28135] Redact literal values in CASE clauses

metaphor/snowflake/extractor.py, pyproject.toml
It was set to `REDSHIFT` incorrectly
As titled.
Verified the generated `metadata.run` file:
```
{
"crawlerName": "metaphor.snowflake.extractor.SnowflakeExtractor",
"description": "Snowflake metadata crawler",
"endTime": "2024-08-20T07:19:29.901330",
"entityCount": 193.0,
"platform": "SNOWFLAKE",
"startTime": "2024-08-20T07:18:57.189945",
"status": "SUCCESS"
}
```
=> Fix platform enum for Snowflake connector

metaphor/common/embeddings_config.py, poetry.lock, pyproject.toml, tests/common/test_embeddings_config.py
If the `azure_openai.version` set in the app is a regular version e.g. `2024-06-01` instead of a `-preview` version it can be misinterpreted as a datetime when the config is loaded, causing validation errors.
Adds a validator to force datetime to string to catch pesky validation errors.
Connector tested locally with a YAML file generated by `app`, runs successfuly.
=> Add validator to catch datetime azure_openai.version

metaphor/common/sql/process_query/process_query.py, pyproject.toml, tests/common/sql/process_query/process_query/redact_literal_values_in_where_clauses/expected.sql, tests/common/sql/process_query/process_query/redact_literal_values_in_where_clauses/query.sql, tests/common/sql/process_query/process_query/redact_literals_in_where_in/expected.sql, tests/common/sql/process_query/process_query/redact_literals_in_where_in/query.sql, tests/common/sql/process_query/process_query/redact_literals_in_where_or/expected.sql, tests/common/sql/process_query/process_query/redact_literals_in_where_or/query.sql, tests/common/sql/process_query/process_query/redact_merge_insert_when_not_matched/expected.sql, tests/common/sql/process_query/process_query/redact_merge_insert_when_not_matched/query.sql, tests/common/sql/process_query/process_query/redact_simple/expected.sql, tests/common/sql/process_query/process_query/redact_simple/query.sql, tests/common/sql/process_query/process_query/redact_where_clauses/expected.sql, tests/common/sql/process_query/process_query/redact_where_clauses/query.sql, tests/common/sql/process_query/process_query/snowflake_copy_into/expected.sql, tests/common/sql/process_query/process_query/snowflake_copy_into/query.sql, tests/common/sql/process_query/test_process_query.py
If a literal value should be redacted, we use the placeholder string `<REDACTED>`. However, if we are redacting a numeric value we need to turn it into a string, otherwise SQLGlot will think `<` is LT, and would not parse the thing.
For example, SQLGlot will not parse this:
```sql
INSERT INTO target_table (first_name, last_name, email, status)
SELECT
first_name,
last_name,
email,
CASE
WHEN age < <REDACTED> THEN '<REDACTED>'
WHEN age >= <REDACTED> AND age < <REDACTED> THEN '<REDACTED>'
ELSE '<REDACTED>'
END AS status
FROM source_table
WHERE NOT email IS NULL
```
On the other hand, this works:
```sql
INSERT INTO target_table (first_name, last_name, email, status)
SELECT
first_name,
last_name,
email,
CASE
WHEN age < '<REDACTED>' THEN '<REDACTED>'
WHEN age >= '<REDACTED>' AND age < …
```
=> [sc-28233] Redacted values should be strings

metaphor/postgresql/extractor.py, pyproject.toml
Postgres crawler is spamming a lot of warning logs when parsing precision
As title
Verified against sample table that contains these column types.
=> Better logging when parsing column type attributes

metaphor/snowflake/extractor.py, metaphor/snowflake/utils.py, pyproject.toml, tests/snowflake/test_extractor.py
Populating `system_tags.tags` in `_init_dataset` will set the aspect's `createdAt` field to the day the crawler run and saw the dataset, thus making datasets that are supposed to be soft deleted appear to be constantly updated with each crawler run.
Only populate `systemTags.tags` when there's a tag that's associated to the dataset.
- Modified unit test. If there is no tag for a dataset, its `system_tags` will be `None`.
=> [sc-28341] Populate systemTags.tags only when there are really tags

metaphor/common/docs/process_query.md, metaphor/common/sql/process_query/config.py, metaphor/common/sql/process_query/process_query.py, pyproject.toml, tests/common/sql/process_query/test_process_query.py
If we can't parse some queries, we want to be able to decide whether we want these queries to pass thru or be ignored altogether.
Added config to control whether to skip or pass through unparseable queries.
=> [sc-28404] Add config to drop or pass through unparseable queries

metaphor/postgresql/README.md, metaphor/postgresql/config.py, metaphor/postgresql/extractor.py, metaphor/postgresql/log_parser.py, metaphor/postgresql/profile/config.py, metaphor/postgresql/usage/config.py, metaphor/redshift/config.py, metaphor/redshift/extractor.py, pyproject.toml, tests/postgresql/config.yml, tests/postgresql/test_config.py, tests/postgresql/test_extractor.py, tests/postgresql/test_log_parser.py, tests/postgresql/usage/config.yml, tests/postgresql/usage/test_config.py, tests/redshift/config.yml, tests/redshift/test_config.py, tests/redshift/test_extractor.py
PostgreSQL does not store the query history, or user action in the database but can be configured as logging to its log file. Therefore, we can parse the Postgres log for query log extraction
- Extract query history from CloudWatch
Test against an RDS instance.
=> Query log extraction for Postgres crawler

metaphor/dbt/cloud/utils.py, pyproject.toml
Can not directly map the adapter type to `DataPlatform`
- Add a dictionary for the conversion
Run the crawler against an Postgres project in dbt cloud
=> Fix dbt env platform

metaphor/bigquery/README.md, metaphor/bigquery/config.py, metaphor/bigquery/extractor.py, metaphor/postgresql/README.md, metaphor/postgresql/config.py, metaphor/postgresql/extractor.py, metaphor/redshift/README.md, metaphor/redshift/extractor.py, metaphor/unity_catalog/README.md, metaphor/unity_catalog/config.py, metaphor/unity_catalog/extractor.py, metaphor/unity_catalog/utils.py, pyproject.toml, tests/unity_catalog/test_utils.py
We added SQL preprocessor, but currently only Snowflake crawler makes use of it. The other data platform that we get query history from should also have the ability to preprocess their queries.
Add `process_query` function call in the following crawler's `collect_query_logs` method:
- BigQuery
- Redshift
- Postgresql
- Unity Catalog
- Modified UC unit test
- Run all four crawlers with stage configuration with `redact_literals.enabled` set to True, all run without error and the literals are all redacted.
=> [sc-28469] Enable `process_query` for BQ, Postgres, Redshift and UC

metaphor/common/sql/utils.py, metaphor/postgresql/extractor.py, pyproject.toml
Encounter MCE validation when processing the query log.
The `database` and `schema` can not be empty strings or null so add a function to drop query logs that don't have `schema`
So MCE error after the patch
=> Fix: MCE validation error

metaphor/common/sql/process_query/config.py, metaphor/common/sql/process_query/process_query.py, metaphor/postgresql/extractor.py, pyproject.toml, tests/common/sql/process_query/test_config.py, tests/common/sql/process_query/test_process_query.py, tests/postgresql/test_extractor.py
Some statements with neither sources nor targets are important allowing us to generate CLL, we should not skip them. In addition, we still want to skip statements like `CREATE USER`
- Add a config `process_query.ignore_command_statement`
- Skip commands if it's configured true.
- Collect other logs
Unit test and ingest MCE to dev.
=> Collect all valid query history

metaphor/snowflake/extractor.py, metaphor/snowflake/utils.py, metaphor/tableau/extractor.py, pyproject.toml, tests/snowflake/test_extractor.py, tests/tableau/expected.json, tests/tableau/test_extractor.py
Tableau crawler populated the datasets only to set their system tags, but these system tags will conflict with existing dataset tags, and we don't want that.
This also reverts #968 , since we want the empty array to be there if no system tag is found for an entity.
- Reverted #968 
- Removed `_init_dataset` logic in Tableau crawler.
- Crawler run locally.
- Modified unit test.
=> [sc-27944] Do not populate dataset in Tableau crawler

.dockerignore, metaphor/__main__.py, metaphor/common/cli.py, pyproject.toml
Factor out arg parsing to a function so we can call it from the launcher script to write a `run.metadata` when time out
- Factor out arg parsing
- Update `.dockerignore`
Deploy crawler image to dev with this change, and it will create `run.metadata`
=> Handle crawler timeout gracefully

metaphor/common/sql/table_level_lineage/table_level_lineage.py, pyproject.toml
We should catch RecursionError in the try catch block so that the crawler does not fail midway through the process.
Catch RecursionError in TLL parsing.
=> [sc-28620] Catch RecursionError in TLL parsing

metaphor/dbt/cloud/extractor.py, metaphor/dbt/cloud/http.py, pyproject.toml, tests/dbt/cloud/test_http.py
For the ease of debugging.
- Logs GQL calls
Verified locally
=> Add logs for dbt cloud crawler

metaphor/common/docs/process_query.md, metaphor/common/sql/process_query/config.py, metaphor/postgresql/config.py, pyproject.toml, tests/common/sql/process_query/test_config.py, tests/common/sql/process_query/test_process_query.py
`ignore_command_statement` was defaulted to True, which made all crawlers that parses SQL queries in all environments started processing queries.
Instead of doing it by default, our users should explicitly opt-in to query processing.
The actual SQL query that could not be parsed by sqlglot is tracked in a [separate ticket](https://app.shortcut.com/metaphor-data/story/28750/metaphor-crawler-big-query-integrations-error)
- Set `ignore_command_statement` default to `False`
- Modified unit test
- Updated readme
Modified unit test.
=> [sc-28750] Set `ignore_command_statement` default to `False`

metaphor/common/hierarchy.py, metaphor/looker/folder.py, metaphor/quick_sight/extractor.py, metaphor/quick_sight/folder.py, metaphor/thought_spot/extractor.py, metaphor/thought_spot/utils.py, poetry.lock, pyproject.toml, tests/quick_sight/expected.json
To place QuickSight dashboards and datasets in the predefined folders.
- Fill `structure.directories`
- Refactor `create_hierarchy`
Updated unit tests and verified end-to-end on dev.
=> Top level folders for QuickSight entities

metaphor/snowflake/README.md, metaphor/snowflake/config.py, metaphor/snowflake/extractor.py, pyproject.toml
To reduce the amount of notifications on platform tag changes, a config is added to Snowflake to disable tag collection. Users can have 2 Snowflake crawlers that do different things: one is the full-scale crawler, crawls the query logs and the tags; the other is the lightweight one, doesn't do query logs or collect tags.
Added a config value to disable collecting tags in Snowflake.
Crawler run locally.
=> [sc-27944] Add config to disable tag collection in Snowflake

README.md, metaphor/athena/README.md, metaphor/athena/__init__.py, metaphor/athena/config.py, metaphor/athena/extractor.py, metaphor/athena/models.py, poetry.lock, pyproject.toml, tests/athena/data/batch_get_query_executions_ef77e890-ca4f-4e46-b4d3-ee90915237ae.json, tests/athena/data/list_data_catalogs_f8346904-fad9-4b57-a4ca-4a5df6392d62.json, tests/athena/data/list_databases_3039188f-6f71-4c41-b79c-cac7bcb905bc.json, tests/athena/data/list_query_executions_3ec07c89-d2ee-414a-8490-c0a63471bd47.json, tests/athena/data/list_table_metadata_e6d7f820-7a9d-46ff-b479-df064d0c8c65.json, tests/athena/expected.json, tests/athena/expected_query_logs.json, tests/athena/test_extractor.py
To extract tables, views, and queries in Athena
- Extract tables
- Extract query logs
Ingest MCEs to dev instance.
=> Athena crawler

metaphor/common/aws.py, metaphor/common/sql/process_query/process_query.py, metaphor/postgresql/README.md, metaphor/postgresql/config.py, metaphor/postgresql/extractor.py, pyproject.toml, tests/postgresql/expected_logs_execute.json, tests/postgresql/test_extractor.py
Since `log_duration` does not always default to `true`, we should be able to extract query history without duration.
- Add `log_duration_enabled` flag to default to `false` to extract log without duration
- Add `filter_pattern` to speed up query log extraction
- fix skipping `execute` statement and add testcase
Update unit tests, verified against dev postgres instance.
=> Support Postgres log extraction with log_duration disabled

.github/workflows/cd.yml, .github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, pyproject.toml
CICD action versions are pretty outdated, causing some weird Github checking issues
- update actions versions in CICD
- bump version to verify the docker and pypi job is running correctly
let CICD do its work
=> update cicd action versions

metaphor/athena/extractor.py, pyproject.toml, tests/athena/data/list_data_catalogs_f8346904-fad9-4b57-a4ca-4a5df6392d62.json, tests/athena/data/list_databases_3039188f-6f71-4c41-b79c-cac7bcb905bc.json, tests/athena/data/list_table_metadata_e6d7f820-7a9d-46ff-b479-df064d0c8c65.json, tests/athena/test_extractor.py
Crawler filter is not implemented in #995 
- Add filter
Unit test
=> Filter is not working in athena crawler

metaphor/mongodb/README.md, metaphor/mongodb/config.py, metaphor/mongodb/extractor.py, pyproject.toml
We are not supposed to crawl the [system collections](https://www.mongodb.com/docs/manual/reference/system-collections/#database-specific-collections) in MongoDB.
- Exclude the system collections by default.
N/A.
=> [sc-29393] MongoDB crawler ignore system collections

metaphor/athena/README.md, metaphor/athena/config.py, metaphor/athena/extractor.py, pyproject.toml, tests/athena/data/batch_get_query_executions_ef77e890-ca4f-4e46-b4d3-ee90915237ae.json, tests/athena/expected_query_logs.json, tests/athena/test_extractor.py
To redact literal in query logs
- Add `query_log` config
- Use `process_and_init_query_log` to redact literal
- Do not output query log out of (-lookback_days, now) time range.
Updated unit tests and verified against dev.
=> Improve query log extraction for Athena connector

metaphor/athena/README.md, metaphor/athena/config.py, metaphor/athena/extractor.py, pyproject.toml
Currently, we only get the query log for the primary workgroup, and we should support specifying workgroup
As title, add a new config and update the README.
Test against dev.
=> Allow to config workgroup to collection query log from

metaphor/bigquery/profile/extractor.py, metaphor/common/fieldpath.py, metaphor/postgresql/profile/extractor.py, metaphor/snowflake/profile/extractor.py, metaphor/unity_catalog/profile/extractor.py, pyproject.toml, tests/snowflake/profile/expected.json
We have normalized the dataset column `field path` in table crawlers, but the profile crawlers missed this normalization and thus caused some mismatch. 
- normalize the profiled column field path
unit test
tested against snowflake instance
=> Snowflake profiler is not normalizing the [sc-29479]

metaphor/common/utils.py, metaphor/dbt/cloud/extractor.py, metaphor/dbt/cloud/parser/common.py, metaphor/dbt/cloud/parser/dbt_metric_parser.py, metaphor/dbt/cloud/parser/dbt_node_parser.py, metaphor/dbt/cloud/parser/dbt_source_parser.py, metaphor/dbt/cloud/parser/dbt_test_parser.py, metaphor/dbt/cloud/parser/parser.py, metaphor/dbt/util.py, metaphor/fivetran/extractor.py, pyproject.toml, tests/dbt/cloud/expected.json
It is possible for a single dbt model to be referenced by tests in jobs in different projects. To avoid writing to different virtual view MCEs, we want to write to the same virtual view and only update the necessary bits.
- Pass crawler-wide entities to dbt cloud sub-parsers.
- Added dedup method.
- Updated unit test.
- Ran the crawler locally.
The model `jaffle_shop.stg_supplies` has two tests:
This model is referenced in 2 projects: `jaffle_shop` and `jaffle_shop_postgres` (basically a clone of the first one, just run on top of postgres.) Both projects are included in my crawler config.
When we run the extractor, in the model there's only 1 `not_null_stg_supplies_supply_uuid` test.
But when we look at data quality for the referenced dataset, we see there are two monitors. This is …
=> [sc-29305] Merge dbt cloud metadata before writing to file

metaphor/s3/README.md, metaphor/s3/path_spec.py, pyproject.toml, tests/s3/test_path_spec.py
If the excluded path ends in `/*`, all files within the directory should be excluded.
- If the excluded path ends in `/*`, all files within the directory should be excluded.
- The other issue where the exclusion rule contains wildcard in template label part name will be addressed in a separate PR. It requires much more work to do properly.
=> [sc-29500] Exclude should work if it ends in `/*`

metaphor/postgresql/profile/extractor.py, pyproject.toml, tests/postgresql/profile/test_extractor.py
The `include_view` config was used incorrectly, doing the exact opposite.
- fix the dataset filtering based on `include_view`, also excluding `external`, `stream`, `snapshot` types
- also remove the dataset entities with empty field statistics from the MCE
tested with `include_view` set to True and False, verified the results.
=> Redshift profiler missing tables [sc-29514]

metaphor/s3/path_spec.py, pyproject.toml, tests/s3/test_path_spec.py
If the exclude path has a wildcard in the template label component, the crawler would not be able to filter the path out.
The original logic to decide if a path should be excluded is hard to follow, and even harder to fix the bug. Rewrote the whole thing to make it easier to follow.
- PathSpec._path_is_excluded method to check if the path is excluded.
Added unit test. Previously skipped unit test is now passing.
=> [sc-29504] `PathSpec._path_is_excluded` to check if path is excluded

metaphor/common/embeddings.py, tests/confluence/expected.json, tests/monday/expected.json, tests/notion/expected.json, tests/sharepoint/expected.json, tests/sharepoint/expected_no_text.json, tests/static_web/expected.json
We have removed `documentId` in search documents, but the crawler-generated search documents still have it, causing ingestion validation errors.
- remove `documentId` field
tested confluence crawler, verified the generated MCE
=> Confluence ingestion error [sc-29555]

metaphor/unity_catalog/extractor.py, pyproject.toml
A `SystemDescription` with empty string as description Metaphor ingestion, we should only populate it if the comment is a non-empty string.
As titled.
Tested against our stage environment.
=> [sc-29652] Skip SystemDescription if comment is empty string

metaphor/common/utils.py, metaphor/unity_catalog/README.md, metaphor/unity_catalog/config.py, metaphor/unity_catalog/extractor.py, metaphor/unity_catalog/queries.py, pyproject.toml, tests/common/test_utils.py, tests/great_expectations/basic_sql/gx/.gitignore, tests/great_expectations/snowflake/gx/.gitignore, tests/unity_catalog/config.yml, tests/unity_catalog/expected.json, tests/unity_catalog/test_config.py
A few small fixed/improvements after https://github.com/MetaphorData/connectors/pull/1022.
- Add `has_select_permissions` config to enable/disable all queries that require SELECT permission.
- Avoid printing the full stack when encountering permission issues.
- Properly handle empty descriptions.
- Properly JSON-encode table property values.
- Add files missed by https://github.com/MetaphorData/connectors/pull/1025
=> Add config to disable queries that require SELECT permission

metaphor/common/docs/requests.md, metaphor/common/requests_config.py, metaphor/fivetran/README.md, metaphor/fivetran/config.py, metaphor/fivetran/extractor.py, pyproject.toml, tests/common/test_api_request.py
Fivetran can be slow with responses, sometimes even exceeding 10 seconds. To address this, we are exposing timeout for requests as a configuration value.
Added `RequestsConfig` for requests configuration values, and added it to fivetran's config.
=> [sc-29679] `RequestsConfig` for HTTP request configuration values

metaphor/looker/lookml_parser.py, metaphor/power_bi/extractor.py, metaphor/tableau/extractor.py, metaphor/thought_spot/extractor.py, pyproject.toml, tests/looker/test_lookml_parser.py, tests/power_bi/expected.json, tests/tableau/expected.json, tests/thought_spot/expected.json
To show the web extension tab for entities
- Fill in `sourceInfo.mainUrl` as much as possible
Unit tests
=> Fill sourceInfo mainUrl for all entities

metaphor/openapi/extractor.py, pyproject.toml, tests/openapi/data/no_tag_30/expected.json, tests/openapi/data/no_tag_30/openapi.json, tests/openapi/test_extractor.py
APIs without tags have empty hierarchy but they should belongs to top-level OpenAPI hierarchy
- Fix `directories` logic
Add unit tests.
=> Fix OpenAPI hierarchy

metaphor/bigquery/README.md, metaphor/snowflake/extractor.py, metaphor/snowflake/profile/extractor.py, pyproject.toml
Turns out it's a misconfiguration caused by the documentation. Added more detail about the big query crawler `filter` config. 
Also discovered a bug about the snowflake filtering. if the `include` database contains wildcard, it is used as a plain text and causes all databases to be bypassed.
- update readme of big query crawler filter
- fix snowflake `fetch_database`
tested against big query and snowflake instances with wildcard in filter config, and verified the results.
=> BigQuery crawler filtering not working with [sc-29743]

metaphor/common/filter.py, metaphor/common/sink.py, metaphor/postgresql/extractor.py, metaphor/postgresql/profile/extractor.py, pyproject.toml, tests/common/test_filter.py
The filter action `include_schema` was using plain text matching for database name, which caused the wildcard to be ignored.
- Fix the `filter.include_schema` method to match both database and schema using pattern.
- Fix Postgresql database filter to use filter methods instead of listing the database names
unit test
tested both BQ and PQL crawler using wildcard filter config and verified the MCEs
=> BQ crawler filtering support as project [sc-29768]

metaphor/unity_catalog/models.py, metaphor/unity_catalog/queries.py, pyproject.toml, tests/unity_catalog/test_models.py
Our crawler did not take into account for the case when `row["columns"]` is a `None`.
- Fix NoneType not iterable error
- Refactor to make testing easier
- Added tests
- Tested against stage environment.
=> [sc-29773] Handle tables without columns

metaphor/unity_catalog/models.py, pyproject.toml, tests/unity_catalog/test_models.py, tests/unity_catalog/test_queries.py
Dataset tags should be populated into `TableInfo.tags`.
Populate `TableInfo.tags` with tags gathered from SQL query.
- Tested against stage configuration. Previously no tags were found, now tags are being populated properly.
=> [sc-29767] Populate `TableInfo.tags`

metaphor/power_bi/extractor.py, metaphor/power_bi/power_bi_client.py, pyproject.toml, tests/power_bi/test_extractor.py
Most of the Power BI [Admin APIs](https://learn.microsoft.com/en-us/rest/api/power-bi/admin) have a rate limit of 200 requests/hour. We reach the limit quickly when crawling a large number of workspaces.
Replace the following per-workspace API calls with global API calls. These global APIs appear to be equivalent and are able to scale to thousands of items without any issues.
- [GetDatasetsInGroupAsAdmin](https://learn.microsoft.com/en-us/rest/api/power-bi/admin/datasets-get-datasets-in-group-as-admin) => [GetDatasetsAsAdmin](https://learn.microsoft.com/en-us/rest/api/power-bi/admin/datasets-get-datasets-as-admin)
- [GetReportsInGroupAsAdmin](https://learn.microsoft.com/en-us/rest/api/power-bi/admin/reports-get-reports-in-group-as-admin) => …
=> Fix rate limiting issues with Power BI admin APIs

metaphor/openapi/config.py, pyproject.toml
```yaml
specs:
- base_url: <url>
openapi_json_url: <url>
- base_url: <url>
openapi_json_url: <url>
output:
file:
directory: <path>
```
didn't not pass the config validation
Fix `OpenAPIRunConfig` validation function
Verified locally
=> [sc-29929] invalid multi oas config

metaphor/monte_carlo/extractor.py, pyproject.toml
MC's GraphQL API places limit the max response size to 6 MB. The current non-paginated [getMonitors](https://apidocs.getmontecarlo.com/#query-getMonitors) call can exceed that limit when is a large number monitors configured.
As titled.
Verified that before & after output are identical against a production instance.
=> Add pagination to Monte Carlo getMonitors call

metaphor/monte_carlo/README.md, metaphor/monte_carlo/config.py, metaphor/monte_carlo/extractor.py, pyproject.toml, tests/monte_carlo/config.yml, tests/monte_carlo/expected.json, tests/monte_carlo/test_config.py, tests/monte_carlo/test_extractor.py
In addition to [user-defined monitors](https://docs.getmontecarlo.com/docs/monitors-overview), Monte Carlo also supports [automatic anomaly detection](https://docs.getmontecarlo.com/docs/detectors-overview). We'd like to surface these anomalies as data quality issues, only if they're triggered and not marked as handled (acknowledged/expected/fixed) by the user 
- Use [getAlerts](https://apidocs.getmontecarlo.com/#query-getAlerts) GraphQL query to retrieve all `ANOMALIES` alerts and map unhandled ones to failed data monitors.
- Generalize `_convert_dataset_name` into `_extract_dataset_name` for MCON to dataset name parsing.
- Add configs to opt into the new behavior and to control the lookback length.
Verified before & after against a production instance.
=> Treat unhandled Monte Carlo anomalies as data quality errors

metaphor/monte_carlo/extractor.py, pyproject.toml
[prevExecutionTime](https://apidocs.getmontecarlo.com/#definition-Monitor) returned by [getMonitors](https://apidocs.getmontecarlo.com/#query-getMonitors) can be null and must be handled gracefully.
As titled. Also defensively applied the same to`createdTime` from [getAlerts](https://apidocs.getmontecarlo.com/#query-getAlerts).
=> Use safe date parsing in Monte Carlo connector

metaphor/quick_sight/client.py, pyproject.toml
The quickSight DescribeDataSet API may throw error for some dataset type such as file formats (csv, s3 file, etc)
- add try catch to not fail the entire crawler when DescribeDataSet error is thrown
- dump the list API response for debugging
tested against Metaphor instance, but need to test on customer env to log the issue
=> QuickSight crawler unsupported dataset type [sc-30088]

metaphor/quick_sight/client.py, metaphor/quick_sight/data_source_utils.py, metaphor/quick_sight/lineage.py, metaphor/quick_sight/models.py, pyproject.toml, tests/quick_sight/test_extractor.py
The dataSource.type returns value that is not defined in https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DataSource.html, causing the pydantic enum validation to throw error.
- Relex model field dataSource.type to string instead of enum
- update source type mapping and handle unsupported type
- move each asset process to be within try-catch
- minor update to logging info
tested against Metaphor instance, needs to run against customer env.
=> QuickSight data source validation error [sc-30088]

metaphor/quick_sight/client.py, poetry.lock, pyproject.toml
The QuickSight API can hang sometimes, possibly due to rate limit.
- Add a function wrapper around the API to timeout and retry
tested on Metaphor instance, will test on customer env.
=> quicksight rate limiting [sc-30089]

metaphor/common/sql/table_level_lineage/table_level_lineage.py, metaphor/quick_sight/lineage.py, pyproject.toml
The SQL parser may stuck for some particular SQL queries.
- Add timeout to SQL parsing
tested on Metaphor instance, add sleep to trigger timeout
=> add timeout to SQL parsing

metaphor/common/sql/table_level_lineage/table_level_lineage.py, metaphor/quick_sight/client.py, metaphor/quick_sight/extractor.py, poetry.lock, pyproject.toml
Quicksight crawler may stuck at the parsing phase.
- Use `func-timeout` lib instead of the `signal`
- Add timeout at the dataset parsing level
- add a bit more progress tracker
tested on Metaphor instance, also manually triggered timer
=> update quicksight parsing timeout

metaphor/common/snowflake.py, metaphor/quick_sight/data_source_utils.py, metaphor/quick_sight/extractor.py, metaphor/quick_sight/lineage.py, pyproject.toml, tests/common/test_snowflake.py, tests/quick_sight/data/data_sources.json, tests/quick_sight/expected.json
The upstream snowflake URL sometimes contains the default region `us-west-2` that needs to be stripped to match the account name from Snowflake crawler.
Also in some cases, when the lineage parser needs to find an existing dataset, it used quicksight dataset_id but the dictionary used arn as key, should all use id instead.
- update snowflake account to remove default region
- update MCE dictionary to use id as key instead of arn
- refactor lineage parsing
- in the Virtual View and Dashboard logical ID, use the Quicksight ID instead of ARN as name.
tested on Metaphor instance
=> update quicksight lineage

metaphor/quick_sight/README.md, metaphor/quick_sight/config.py, metaphor/quick_sight/extractor.py, metaphor/quick_sight/lineage.py, pyproject.toml, tests/quick_sight/config.yml, tests/quick_sight/expected.json, tests/quick_sight/expected_with_filter.json, tests/quick_sight/test_config.py, tests/quick_sight/test_extractor.py
This is to avoid fetching all the metadata from quicksight and causing noise. 
- add a filter based on dashboard IDs to selectively include dashboards and data sets in the final results
tested on metaphor instance
=> quicksight crawler add filter [sc-30103]

metaphor/thought_spot/extractor.py, metaphor/thought_spot/models.py, pyproject.toml
ThoughtSpot recently introduced [models](https://docs.thoughtspot.com/cloud/latest/models) in favor or [Worksheets](https://docs.thoughtspot.com/cloud/latest/worksheet-create). This has caused the crawler to crash when extracting formula from models:
```
File "/usr/local/lib/python3.9/site-packages/metaphor/common/runner.py", line 61, in run_connector
entities = connector.run_async()
File "/usr/local/lib/python3.9/site-packages/metaphor/common/base_extractor.py", line 39, in run_async
File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
File …
```
=> Handle formula extraction from TML models

metaphor/quick_sight/lineage.py, pyproject.toml
For certain quicksight data sets with custom SQL, if the SQL can't be parsed, the dummy virtual view and table won't be created, so if a logical table referenced that table, it will throw error. 
- When processing quicksight dataset physical table, init the table and virtual view first, so the entity skeleton is created and can be referenced.
tested against the failure case
=> Quicksight crawler error physical table not [sc-30132]

metaphor/monte_carlo/config.py, metaphor/monte_carlo/extractor.py, pyproject.toml, tests/monte_carlo/expected.json, tests/monte_carlo/test_extractor.py
Monte Carlo crawler has been incorrectly reporting non-active monitors as DQ errors, and not treating breached monitors as errors.
- Filter out non-active monitors (i.e.  `consolidatedStatusTypes = ENABLED`) when calling [get_monitors](https://apidocs.getmontecarlo.com/#query-getMonitors).
- Use the `breached` field instead of `monitorStatus` field to determine if there's a DQ issue.
- Drop exception process logic since it's only for monitors that failed to execute (i.e. `consolidatedStatusTypes = ERROR`).
=> Filter out non-active MC monitors

metaphor/metabase/extractor.py, metaphor/thought_spot/utils.py, pyproject.toml
For one particular customer asset, the API query throws `HTTPError: 400 Client Error: Bad Request for url: https://endpointclosing.thoughtspot.cloud/api/rest/2.0/metadata/answer/sql`
- add try catch to no let the error terminate the crawler
- log the HTTP error
tested on customer env
=> ThoughtSpot crawler HTTP 400 error [sc-30171]

metaphor/thought_spot/extractor.py, pyproject.toml, tests/thought_spot/data/answers.json, tests/thought_spot/expected.json
To make the TS verified label more visible on UI and searchable.
- if the TS asset is verified, add a "Verified" system tag
tested against production env
=> Add ThoughtSpot Verified system tag [sc-29423]
